### ISSUE TITLE
scenario.write how to provide custom title name?

### ISSUE THREAD

**Issue by kprasadbio** [damianszczepanik/cucumber-reporting#1002]
Hi,

when i use scenario.write, i get default title as output1, i would like to change the title, is it possible?
if so, please guide how can it be done.
![image](https://user-images.githubusercontent.com/17196589/116504696-8bfccb80-a8d6-11eb-856a-0d459d0d8df1.png)

**Comment by damianszczepanik** [comment]
It takes information from JSON what is not present there would be rather hard to add to web report
