### ISSUE TITLE
OWASP dependency vulnerability check failure

### ISSUE THREAD

**Issue by wenqiglantz** [damianszczepanik/cucumber-reporting#1005]
I ran OWASP dependency vulnerability check on my app, which uses cucumber reporting, specifically the following dependency lib.

```
<dependency>
<groupId>net.masterthought</groupId>
<artifactId>cucumber-reporting</artifactId>
<version>5.5.3</version>
</dependency>
```

The dependency vulnerability check showed the following results, complaining about four dependency libs within net.masterthought:cucumber-reporting:5.5.3, any suggestion on how this can be fixed?

![image](https://user-images.githubusercontent.com/13189654/123531120-e1cfd300-d6cf-11eb-8ab2-0e0d0db4e90d.png)

**Comment by RahulSharma19021996** [comment]
Hi @damianszczepanik , any update on the above issue?

**Comment by damianszczepanik** [comment]
#1011

**Comment by damianszczepanik** [comment]
guava is fixed, haven't found new software versions for other violations

**Comment by elans3** [comment]
@damianszczepanik , Can you update the release schedule for the vulnerability check failures

**Comment by damianszczepanik** [comment]
Also versions you have provided looks like they are incorrect
https://github.com/damianszczepanik/cucumber-reporting/blob/master/pom.xml#L222-L224

**Comment by RahulSharma19021996** [comment]
https://repo1.maven.org/maven2/net/masterthought/cucumber-reporting/5.5.3/cucumber-reporting-5.5.3.pom

Hi @damianszczepanik, In the above link, latest version(2.3) of velocity-engine-core is not available. Could you please release the latest code. It would be a great help

**Comment by damianszczepanik** [comment]
I will, soon
