### ISSUE TITLE
CucumberHtmlReport.Close() is taking more than 10 minutes to execute

### ISSUE THREAD

**Issue by RamaLaxmi-462** [damianszczepanik/cucumber-reporting#1009]
Hi Guys,

I am using Cucumber BDD framework using jUnit and my reporting creates 2 types of files .html and .mht
A step(CucumberHtmlReport.Close()) in after hooks is taking lot of time for execution ..Please find the snippet of code below and let me know if any possible fix exists for the issue.
If I comment out this line ,only .html report is getting generated where as my expected reporting o/p files should be both .html and .mht and hence, I can't comment out or ignore that line.
![image](https://user-images.githubusercontent.com/86734267/123994199-c3791880-d9ea-11eb-8d82-e0f819538103.png)

Thanks for your valuable responses in advance!

**Comment by damianszczepanik** [comment]
Can't see any code that is part of my project
