### ISSUE TITLE
Scenario Level reporting

### ISSUE THREAD

**Issue by gitissuepost** [damianszczepanik/cucumber-reporting#1021]
As part of this reporting capability, I am able to generate report for Features/Tags. However, I couldn't generate a scenario level report to understand, which scenario got passed and which got failed.

If my feature has 7 scenarios, I see 7 entries of same feature in Feature overview which doesn't give an overview of which scenario got failed or passed unless I open a specific entry in that.

Is there a way to generate scenario overview report?

**Comment by damianszczepanik** [comment]
Report is generated from the JSON file so if you have such structure in JSON report then HTML reflects to that.

**Comment by gitissuepost** [comment]
> Report is generated from the JSON file so if you have such structure in JSON report then HTML reflects to that.

Yes. The cucumber jsons contain these information. And I see scenario names when I drill down to see the steps and hooks.

But, like overview-features.html and overview-tags.html, no files get generated with name overview-scenarios which will give a high level picture of what scenario got passed and what failed. And how much time it took for its execution

**Comment by damianszczepanik** [comment]
Attach JSON file and explain what do you need

**Comment by gitissuepost** [comment]
Attached is a josn file list and the generated report out of it
[Archive.zip](https://github.com/damianszczepanik/cucumber-reporting/files/7229699/Archive.zip)


I am expecting a report like below to see Scenario level out come.
![Screenshot 2021-09-25 at 1 17 37 PM](https://user-images.githubusercontent.com/10003447/134771262-39b0a812-9ca7-45a5-b198-b29aacee37b1.png)

**Comment by damianszczepanik** [comment]
I think rowspan will disable ability to sort rows

**Comment by gitissuepost** [comment]
That's okay.. a feature level report like above will solve the purpose
