### ISSUE TITLE
Could not load plugin class 'de.monochromata.cucumber.report.PrettyReports'

### ISSUE THREAD

**Issue by robininrola** [damianszczepanik/cucumber-reporting#1022]
I am using above error mentioned in description  while running the test.

**### Below are the details of env and versions :**

**NOTE : It is working fine Java 13.0.02 and gradle 6.1.1  below are the  dependencies**  
`apply plugin: 'java'

sourceCompatibility = 11
targetCompatibility = 11

compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"

repositories {
       jcenter()
       mavenCentral()
}

dependencies {
       implementation 'io.cucumber:cucumber-java:4.7.1'
       implementation 'io.cucumber:cucumber-core:4.7.1'
       implementation 'io.cucumber:cucumber-guice:4.7.1'
       implementation 'io.cucumber:cucumber-junit:4.7.1'
       implementation 'io.cucumber:datatable:1.1.14'

       implementation 'com.google.inject:guice:4.2.0'

       implementation 'ch.qos.logback:logback-classic:1.2.3'
       implementation 'ch.qos.logback:logback-core:1.2.3'

       implementation 'org.yaml:snakeyaml:1.21'

       implementation 'junit:junit:4.12'
       implementation 'javax.inject:javax.inject:1'

       implementation 'de.monochromata.cucumber:reporting-plugin:2.0.0'

       implementation 'org.seleniumhq.selenium:selenium-api:3.14.0'
       implementation 'org.seleniumhq.selenium:selenium-support:3.14.0'
       implementation 'org.seleniumhq.selenium:selenium-remote-driver:3.14.0'
       implementation 'org.seleniumhq.selenium:selenium-firefox-driver:3.14.0'
       implementation 'org.seleniumhq.selenium:selenium-chrome-driver:3.14.0'
       implementation 'org.seleniumhq.selenium:selenium-ie-driver:3.14.0'
       implementation 'org.seleniumhq.selenium:selenium-ie-driver:3.14.0'
       implementation 'com.google.code.gson:gson:2.8.5'
       implementation 'org.apache.poi:poi:5.0.0'
       implementation 'org.apache.poi:poi-ooxml:5.0.0'
       

       configurations {
              cucumberRuntime {
                     extendsFrom testImplementation
              }
       }
}

task cucumberEuDesktop() {
       dependsOn assemble, compileTestJava
       def cucumberArguments = ['-p', 'pretty',
                                                '-p', 'html:build/cucumber-reports',
                                                '-p', 'json:build/cucumber-reports/cucumber-' + new Date().format('dd-MM-yyyy-HH-mm-ss-SSS') + '.json',
                                                '-p', 'de.monochromata.cucumber.report.PrettyReports:build',
                                                '-g', 'com.mk.testframework.core',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.eu',
                                                '-g', 'com.mk.testframework.stepdefs.desktopSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.desktopSteps.eu']
       doLast {
              javaexec {
                     main = "io.cucumber.core.cli.Main"
                     systemProperties System.getProperties()
                     cucumberArguments << '-t' << (systemProperties.tags != null ? systemProperties.tags : '@example')
                     cucumberArguments << (systemProperties.location != null ? systemProperties.location : 'src/test/resources/features')
                     classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
                     args = cucumberArguments
              }
       }
}

task cucumberEuMobile() {
       dependsOn assemble, compileTestJava
       def cucumberArguments = ['-p', 'pretty',
                                                '-p', 'html:build/cucumber-reports',
                                                '-p', 'json:build/cucumber-reports/cucumber-' + new Date().format('dd-MM-yyyy-HH-mm-ss-SSS') + '.json',
                                                '-p', 'de.monochromata.cucumber.report.PrettyReports:build',
                                                '-g', 'com.mk.testframework.core',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.eu',
                                                '-g', 'com.mk.testframework.stepdefs.mobileSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.mobileSteps.eu']
       doLast {
              javaexec {
                     main = "io.cucumber.core.cli.Main"
                     systemProperties System.getProperties()
                     cucumberArguments << '-t' << (systemProperties.tags != null ? systemProperties.tags : '@example')
                     cucumberArguments << (systemProperties.location != null ? systemProperties.location : 'src/test/resources/features')
                     classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
                     args = cucumberArguments
              }
       }
}

task cucumberGlobalDesktop() {
       dependsOn assemble, compileTestJava
       def cucumberArguments = ['-p', 'pretty',
                                                '-p', 'html:build/cucumber-reports',
                                                '-p', 'json:build/cucumber-reports/cucumber-' + new Date().format('dd-MM-yyyy-HH-mm-ss-SSS') + '.json',
                                                '-p', 'de.monochromata.cucumber.report.PrettyReports:build',
                                                '-g', 'com.mk.testframework.core',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.global',
                                                '-g', 'com.mk.testframework.stepdefs.desktopSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.desktopSteps.global']
       doLast {
              javaexec {
                     main = "io.cucumber.core.cli.Main"
                     systemProperties System.getProperties()
                     cucumberArguments << '-t' << (systemProperties.tags != null ? systemProperties.tags : '@example')
                     cucumberArguments << (systemProperties.location != null ? systemProperties.location : 'src/test/resources/features')
                     classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
                     args = cucumberArguments
              }
       }
}

task cucumberGlobalMobile() {
       dependsOn assemble, compileTestJava
       def cucumberArguments = ['-p', 'pretty',
                                                '-p', 'html:build/cucumber-reports',
                                                '-p', 'json:build/cucumber-reports/cucumber-' + new Date().format('dd-MM-yyyy-HH-mm-ss-SSS') + '.json',
                                                '-p', 'de.monochromata.cucumber.report.PrettyReports:build',
                                                '-g', 'com.mk.testframework.core',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.global',
                                                '-g', 'com.mk.testframework.stepdefs.mobileSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.mobileSteps.global']
       doLast {
              javaexec {
                     main = "io.cucumber.core.cli.Main"
                     systemProperties System.getProperties()
                     cucumberArguments << '-t' << (systemProperties.tags != null ? systemProperties.tags : '@example')
                     cucumberArguments << (systemProperties.location != null ? systemProperties.location : 'src/test/resources/features')
                     classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
                     args = cucumberArguments
              }
       }
}

task cucumberUsDesktop() {
       dependsOn assemble, compileTestJava
       def cucumberArguments = ['-p', 'pretty',
                                                '-p', 'html:build/cucumber-reports',
                                                '-p', 'json:build/cucumber-reports/cucumber-' + new Date().format('dd-MM-yyyy-HH-mm-ss-SSS') + '.json',
                                                '-p', 'de.monochromata.cucumber.report.PrettyReports:build',
                                                '-g', 'com.mk.testframework.core',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.na.allNaRegions',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.na.us',
                                                '-g', 'com.mk.testframework.stepdefs.desktopSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.desktopSteps.na.allNaRegions',
                                                '-g', 'com.mk.testframework.stepdefs.desktopSteps.na.us']

       doLast {
              javaexec {
                     main = "io.cucumber.core.cli.Main"
                     systemProperties System.getProperties()
                     cucumberArguments << '-t' << (systemProperties.tags != null ? systemProperties.tags : '@example')
                     cucumberArguments << (systemProperties.location != null ? systemProperties.location : 'src/test/resources/features')
                     classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
                     args = cucumberArguments
              }
       }
}

task cucumberUsMobile() {
       dependsOn assemble, compileTestJava
       def cucumberArguments = ['-p', 'pretty',
                                                '-p', 'html:build/cucumber-reports',
                                                '-p', 'json:build/cucumber-reports/cucumber-' + new Date().format('dd-MM-yyyy-HH-mm-ss-SSS') + '.json',
                                                '-p', 'de.monochromata.cucumber.report.PrettyReports:build',
                                                '-g', 'com.mk.testframework.core',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.na.allNaRegions',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.na.us',
                                                '-g', 'com.mk.testframework.stepdefs.mobileSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.mobileSteps.na.allNaRegions',
                                                '-g', 'com.mk.testframework.stepdefs.mobileSteps.na.us']

       doLast {
              javaexec {
                     main = "io.cucumber.core.cli.Main"
                     systemProperties System.getProperties()
                     cucumberArguments << '-t' << (systemProperties.tags != null ? systemProperties.tags : '@example')
                     cucumberArguments << (systemProperties.location != null ? systemProperties.location : 'src/test/resources/features')
                     classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
                     args = cucumberArguments
              }
       }
}

task cucumberCaDesktop() {
       dependsOn assemble, compileTestJava
       def cucumberArguments = ['-p', 'pretty',
                                                '-p', 'html:build/cucumber-reports',
                                                '-p', 'json:build/cucumber-reports/cucumber-' + new Date().format('dd-MM-yyyy-HH-mm-ss-SSS') + '.json',
                                                '-p', 'de.monochromata.cucumber.report.PrettyReports:build',
                                                '-g', 'com.mk.testframework.core',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.na.allNaRegions',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.na.ca',
                                                '-g', 'com.mk.testframework.stepdefs.desktopSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.desktopSteps.na.allNaRegions',
                                                '-g', 'com.mk.testframework.stepdefs.desktopSteps.na.ca']

       doLast {
              javaexec {
                     main = "io.cucumber.core.cli.Main"
                     systemProperties System.getProperties()
                     cucumberArguments << '-t' << (systemProperties.tags != null ? systemProperties.tags : '@example')
                     cucumberArguments << (systemProperties.location != null ? systemProperties.location : 'src/test/resources/features')
                     classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
                     args = cucumberArguments
              }
       }
}

task cucumberCaMobile() {
       dependsOn assemble, compileTestJava
       def cucumberArguments = ['-p', 'pretty',
                                                '-p', 'html:build/cucumber-reports',
                                                '-p', 'json:build/cucumber-reports/cucumber-' + new Date().format('dd-MM-yyyy-HH-mm-ss-SSS') + '.json',
                                                '-p', 'de.monochromata.cucumber.report.PrettyReports:build',
                                                '-g', 'com.mk.testframework.core',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.na.allNaRegions',
                                                '-g', 'com.mk.testframework.stepdefs.crossPlatformSteps.na.ca',
                                                '-g', 'com.mk.testframework.stepdefs.mobileSteps.allRegions',
                                                '-g', 'com.mk.testframework.stepdefs.mobileSteps.na.allNaRegions',
                                                '-g', 'com.mk.testframework.stepdefs.mobileSteps.na.ca']

       doLast {
              javaexec {
                     main = "io.cucumber.core.cli.Main"
                     systemProperties System.getProperties()
                     cucumberArguments << '-t' << (systemProperties.tags != null ? systemProperties.tags : '@example')
                     cucumberArguments << (systemProperties.location != null ? systemProperties.location : 'src/test/resources/features')
                     classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
                     args = cucumberArguments
              }
       }
}
`

### **_Getting Error is while running the tests  with below Dependencies_** 

`java.lang.IllegalArgumentException: The plugin specification 'de.monochromata.cucumber.report.PrettyReports:build' has a problem:

Could not load plugin class 'de.monochromata.cucumber.report.PrettyReports'.

Plugin specifications should have the format of PLUGIN[:[PATH|[URI [OPTIONS]]]

Valid values for PLUGIN are: default_summary, html, json, junit, message, null_summary, pretty, progress, rerun, summary, teamcity, testng, timeline, unused, usage

PLUGIN can also be a fully qualified class name, allowing registration of 3rd party plugins. The 3rd party plugin must implement io.cucumber.plugin.Plugin
	at io.cucumber.core.options.PluginOption.createCouldNotLoadClass(PluginOption.java:168)
	at io.cucumber.core.options.PluginOption.parsePluginName(PluginOption.java:146)
	at io.cucumber.core.options.PluginOption.parse(PluginOption.java:105)
	at io.cucumber.core.options.RuntimeOptionsBuilder.addPluginName(RuntimeOptionsBuilder.java:68)
	at io.cucumber.core.options.CucumberOptionsAnnotationParser.addPlugins(CucumberOptionsAnnotationParser.java:87)
	at io.cucumber.core.options.CucumberOptionsAnnotationParser.parse(CucumberOptionsAnnotationParser.java:41)
	at io.cucumber.junit.Cucumber.<init>(Cucumber.java:122)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:36)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createFilteredTest(JUnit4TestLoader.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:74)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:513)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.NoClassDefFoundError: cucumber/api/Plugin
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:855)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at io.cucumber.core.options.PluginOption.parsePluginName(PluginOption.java:140)
	... 25 more
Caused by: java.lang.ClassNotFoundException: cucumber.api.Plugin
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 35 more

<img width="788" alt="Dependencies" src="https://user-images.githubusercontent.com/62716580/133294280-92d8f807-7fe6-4ac9-b4d6-6a042fbd837e.PNG">
`

java 
`java version "16.0.2" 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)`

gradle version 
`------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16.0.2 (Oracle Corporation 16.0.2+7-67)
OS:           Windows 10 10.0 amd64`

`dependencies {
	implementation 'io.cucumber:cucumber-java:6.11.0'
	implementation 'io.cucumber:cucumber-core:6.11.0'
	implementation 'io.cucumber:cucumber-guice:6.11.0'
	implementation 'io.cucumber:cucumber-junit:6.11.0'
	implementation 'io.cucumber:datatable:1.1.14'
	implementation 'org.apache.commons:commons-lang3:3.12.0'

	implementation 'com.google.inject:guice:4.2.0'

	implementation 'ch.qos.logback:logback-classic:1.2.3'
	implementation 'ch.qos.logback:logback-core:1.2.3'

	implementation 'org.yaml:snakeyaml:1.21'

	implementation 'junit:junit:4.13.2'
	implementation 'javax.inject:javax.inject:1'

	implementation 'de.monochromata.cucumber:reporting-plugin:2.0.0'

	implementation 'org.seleniumhq.selenium:selenium-api:3.14.0'
	implementation 'org.seleniumhq.selenium:selenium-support:3.14.0'
	implementation 'org.seleniumhq.selenium:selenium-remote-driver:3.14.0'
	implementation 'org.seleniumhq.selenium:selenium-firefox-driver:3.14.0'
	implementation 'org.seleniumhq.selenium:selenium-chrome-driver:3.14.0'
	implementation 'org.seleniumhq.selenium:selenium-ie-driver:3.14.0'
	implementation 'org.seleniumhq.selenium:selenium-ie-driver:3.14.0'
	implementation 'com.google.code.gson:gson:2.8.5'
	implementation 'org.apache.poi:poi:5.0.0'
	implementation 'org.apache.poi:poi-ooxml:5.0.0'
		

	configurations {
		cucumberRuntime {
			extendsFrom testImplementation
		}
	}
}`

**Comment by damianszczepanik** [comment]
Can't see here anything that is related to this plugin. Looks like you have reported but for wrong project

**Comment by robininrola** [comment]
Hi ,

I have got this project 

https://gitlab.com/groups/monochromata-de/-/archived

![image](https://user-images.githubusercontent.com/62716580/133400594-9972288e-0b78-434b-9df2-d08ade9d1dda.png)

**Comment by damianszczepanik** [comment]
Based on above logs it looks like the problem is not related to this plugin even you have it as dependency.
