### ISSUE TITLE
Support for the keyword "Rule" in Cucumber report

### ISSUE THREAD

**Issue by UweBahls** [damianszczepanik/cucumber-reporting#1030]
Hi there,
for us it will be very helpfull when the keyword "Rule" can be supported.
It is available since Gherkin 6 and we use it very often in our projects. 
[Gherkin page for "rule"](https://cucumber.io/docs/gherkin/reference/#rule)

**Comment by flatstep** [comment]
Hi Damian,

I just stumbled on this ticket. We've been using Cucumber for quite a while. Over a year ago we started to introduce BDD and to use the rule keyword:

   

    Regel: Die Anmeldung an der Anwendung ist nur mit korrekten Zugangsdaten möglich

       Szenario: Nicht angemeldete Benutzer können sich mit Benutzerkennung und Passwort in der Anwendung anmelden

         Angenommen ich befinde mich als nicht angemeldeter Benutzer auf der Loginseite der Anwendung
         Wenn ich versuche mich mit meiner Benutzerkennung und meinem Passwort anzumelden
         Dann kann ich die Anmeldung erfolgreich abschließen


In addition to the HTML report, Cucumber also generates the JSON file for us:
![cucumber-report-plugins](https://user-images.githubusercontent.com/1461558/179173871-b6ad28e9-c2f3-4351-b959-a96c3e6aa7e7.png)

The HTML report groups as expected:
![rule-keyword-in-report](https://user-images.githubusercontent.com/1461558/179173965-3dcf548e-66e1-4b27-b00b-4d3447b824ed.png)

But there is no rule in our JSON-based report. What really surprises me is the fact that the rule keyword seems to be missing in the JSON:
[cucumber-result-with-rule-keyword.json.txt](https://github.com/damianszczepanik/cucumber-reporting/files/9118830/cucumber-result-with-rule-keyword.json.txt)

Is this keyword, introduced with Gherkin v6, simply not generally supported by the JSON export and reports based on this file?

Best regards
Stephan

**Comment by damianszczepanik** [comment]
This project is about to generate HTML report from JSON file but I understand you have problem with generating JSON file which is not the scope of this project

**Comment by flatstep** [comment]
**Thanks for your reply!**

I have no problem generating the JSON file. We have a JSON file generated and then use this project to create an HTML report.

Since the rule keyword does not appear in the HTML report, I wanted to know whether it is **generally supported by this project**.

**Comment by flatstep** [comment]
Hello Damian. Thank you for your reply. We have been using your Report Publisher on a daily basis for many years in a fairly large project (1,371 features, 6,274 scenarios, 18,992 steps). Thanks for that.

The only thing we miss are the rules we use to structure our features.

Rules were introduced with Gherkin 6, see: https://cucumber.io/docs/gherkin/reference/#rule
Since that was a few years ago.

I could not find any statement on the project homepage if rules are supported. If they are not supported, I think a corresponding note should be added. If they are supported, I would know that we are doing something wrong.

**Comment by damianszczepanik** [comment]
Problem you are describing is not about missing attribute in report but in JSON file

**Comment by senerh** [comment]
Any update on this ? I face the same issue : the "rules" are present in html but not in json.
