### ISSUE TITLE
Option setSkippedAsNotFailing works incorrectly

### ISSUE THREAD

**Issue by ilya-corp** [damianszczepanik/cucumber-reporting#1035]
Hi!
I have Cucumber project with testNG.
To skip scenario which I don't want to run, I use throw new SkipException("Scenario skipped"); in the @Before hook.
I want to avoid skipped scenarios count as failed in the final report. So, if I have 10 scenarios, 2 of them are skipped and 8 are passed successfully, I expect success rate equals to 100%. 
To do that, yesterday I have enabled option <setSkippedAsNotFailing>true</setSkippedAsNotFailing> in my pom.xml.
Today our environment was down and huge part of tests were failed (exception at the first step like "Unable to find Login field").
Unfortunately, in the final report I have found scenarios statistic, where major part of the pie is green and small part is red.

![features](https://user-images.githubusercontent.com/36953132/145414258-2c82e949-a17c-499c-855a-618556c59451.png)

In this case my expectation is following: 90% red, 10% green.

maven-cucumber-reporting.version: 5.6.2

Thanks,
Ilya

**Comment by damianszczepanik** [comment]
First attach JSON, then clarify what project are you using, https://github.com/damianszczepanik/maven-cucumber-reporting ?

**Comment by damianszczepanik** [comment]
Reduce this file to the content which is problematic - analyses of such big file is quite complex

**Comment by ilya-corp** [comment]
Hello! 
I have minimized suite size to 2 tests in one feature.
I have attached 2 new screenshots and new small JSON file.
All my comments are in the screenshots.
I have switched on option <setSkippedAsNotFailing>true</setSkippedAsNotFailing>

Hope it's clear to reproduce.
If I'm not right, please describe what is "skipped", how you defined that?
[cucumber2.zip](https://github.com/damianszczepanik/cucumber-reporting/files/7762233/cucumber2.zip)

Thanks,
Ily
![Report-1](https://user-images.githubusercontent.com/36953132/147083678-22208d0c-2fab-480e-842e-7a0cdacc96d7.png)
![Report-2](https://user-images.githubusercontent.com/36953132/147083679-765558ad-746e-4893-b223-af795afc71e3.png)
![Report-3](https://user-images.githubusercontent.com/36953132/147083681-a48d6ba1-4ff3-45d9-8f6b-02d70a9099d2.png)
a

**Comment by ilya-corp** [comment]
Hi, does that have sense?

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/maven-cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/CucumberReportGeneratorMojo.java#L227 will count skipped statuses as passed so that's why you have chart green

**Comment by ilya-corp** [comment]
1. In my understanding there is strange logic. 
If "setSkippedAsNotFailed" is ON, then scenario must be calculated as successful and highlighted by blue. For example, for 5 scenarios where 1 is skipped, 4 are passed, success rate must be 80%. If "setSkippedAsNotFailed" is OFF, success rate must be 60%.

2. If all scenarios of the feature are **not failed**, then feature also must be not failed -> currently feature is failed.

3. If scenario skipped because SkipException was thrown and "setSkippedAsNotFailed" is ON, then this scenario must be  not failed.

**Comment by damianszczepanik** [comment]
This is not about how your results is present. This is how you should end the report generation - with our without an exception https://github.com/damianszczepanik/maven-cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/CucumberReportGeneratorMojo.java#L226
