### ISSUE TITLE
hpi generation

### ISSUE THREAD

**Issue by cmsoconsistent** [damianszczepanik/cucumber-reporting#1040]
I cloned this repo and did mvn clean install package and expect an hpi in the target directory.

Maybe that is not a correct expectation, so I try to run mvn hpi:hpi

I receive error:
 No plugin found for prefix 'hpi' in the current project and in the plugin groups [org.jenkins-ci.tools, org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\e55aem7\.m2\repository), repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/), central (https://repo.maven.apache.org/maven2)]

So I follow some advice from elsewhere online and add a dependency to the pom file:
<groupId>org.jenkins-ci.plugins</groupId>
<artifactId>plugin</artifactId>
<version>4.37</version>
<type>pom</type>

And try again. Now I receive 
Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.25:hpi (default-cli) on project cucumber-reporting: The parameters 'minimumJavaVersion' for goal org.jenkins-ci.tools:maven-hpi-plugin:3.25:hpi are missing or invalid

It's at that point that my attempts to resolve this error become a tangled mess of spaghetti, 30 open tabs, etc. What on earth am I doing wrong here?

**Comment by damianszczepanik** [comment]
This is not jenkins project then it does not produce hpi artifact. Check https://github.com/jenkinsci/cucumber-reports-plugin
