### ISSUE TITLE
Failing Checkmarx In Maven Dependencies

### ISSUE THREAD

**Issue by astromness** [damianszczepanik/cucumber-reporting#1056]
![image](https://user-images.githubusercontent.com/5544102/179059467-a74c017c-0b4d-4e7d-bec7-04a6a0ff07dc.png)

When adding the MasterThought dependency Maven marks it for the https://advisory.checkmarx.net/advisory/vulnerability/Cx78f40514-81ff/ vulnerability. 

The simple fix would be to update the dependency

<dependency>
    <artifactId>commons-collections</artifactId>
    <groupId>commons-collections</groupId>
    <version>3.2.2</version>
</dependency>

to be the v4 commons-collections
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-collections4</artifactId>
    <version>4.4</version>
</dependency>
v4.4 is the latest today
then refactor anything using the collections library

**Comment by damianszczepanik** [comment]
Nice!
