### ISSUE TITLE
Sanboxed HTML attachment preventing links

### ISSUE THREAD

**Issue by lucashirsch** [damianszczepanik/cucumber-reporting#1067]
The sandbox attribute on the HTML embedding is preventing me from adding custom links to the report.

I am generating a table of results in HTML and embedding that into my reports. Downloading links works as intended (for local csv files generated during execution using ctrl+click on the <a> element), however any buttons I create to dynamically download a csv file based on the HTML table are prevented. I have manually added multiple sandbox attributes to the html, but the only thing that has worked so far is removing the attribute entirely.

The flow is as follows:
1. Test is run and generates an object of some results (7 fields)
2. Before report generation, an HTML page is created with a table containing these results
3. HTML page also includes a basic button which takes the table, generates a csv blob and creates a hidden download link which is clicked through js
4. HTML page is embedded into the report json

When opening the HTML attachment directly, the script works and the file is downloaded. But when opened within the report iframe, the download is blocked (even with allow-popups injected).

I could just save the csv beforehand, but would rather do this client side to save on build space.

**Comment by lucashirsch** [comment]
Update: injecting allow-downloads does allow for the iframe to download the file.

**Comment by damianszczepanik** [comment]
Does the https://github.com/damianszczepanik/cucumber-reporting/pull/1068 solve this issue at all?

**Comment by lucashirsch** [comment]
Yes, thank you! Just installed the snapshot to check and the button is working as intended!
