### ISSUE TITLE
Java Heap Exception for larger number of test cases

### ISSUE THREAD

**Issue by gitissuepost** [damianszczepanik/cucumber-reporting#1072]
We have a test suite of around 5000 test cases mostly with API flows and a very minimal interaction with UI ad screenshots. Average size of cucumber json files getting generated, for each of the test cases is around 450kb While generating report, it processes some files and then ends up with Heap Space issue.

Is there any additional config do I need to add to resolve this issue? Below is the plugin config I have.

`<plugin>
                        <groupId>net.masterthought</groupId>
                        <artifactId>maven-cucumber-reporting</artifactId>
                        <version>5.7.1</version>
                        <executions>
                            <execution>
                                <id>report</id>
                                <phase>post-integration-test</phase>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                                <configuration>
                                    <projectName>${project.name}</projectName>
                                    <skip>false</skip>
                                    <outputDirectory>${project.build.directory}</outputDirectory>
                                    <inputDirectory>${project.build.directory}/cucumber-repotr-space</inputDirectory>
                                    <jsonFiles>
                                        <param>**/*.json</param>
                                    </jsonFiles>
                                    <classificationDirectory>${project.build.directory}</classificationDirectory>
                                    <classificationFiles>
                                        <param>html-report.properties</param>
                                    </classificationFiles>
                                    <mergeFeaturesById>false</mergeFeaturesById>
                                    <mergeFeaturesWithRetest>false</mergeFeaturesWithRetest>
                                    <checkBuildResult>false</checkBuildResult>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
`

**Comment by damianszczepanik** [comment]
I have no experience with such big reports but you need to configure JVM parameters.

**Comment by gitissuepost** [comment]
I have passed that in surefire plugin but not sure if the same can be used for this plugin as I couldn't find any param key for such jvm args for this plugin.

**Comment by gitissuepost** [comment]
Does cucumber-reporting maven plugin has any configuration property that will take JVM params like XmX?

**Comment by damianszczepanik** [comment]
No it does not have
