### ISSUE TITLE
we need to use this plugin for our gradle project

### ISSUE THREAD

**Issue by SavitaKhilnani** [damianszczepanik/cucumber-reporting#1073]
please help us with the steps how we can use this plugin with our gradle project

**Comment by jamietanna** [comment]
I've been using this successfully through my project https://gitlab.com/jamietanna/cucumber-reporting-plugin ([more discussion](https://gitlab.com/jamietanna/cucumber-reporting-plugin/-/issues/19)) which has information in it how to use it :+1:

**Comment by SavitaKhilnani** [comment]
Thanks @jamietanna , definitely would go through the repo.
Also we need to use the functionality with github actions to deploy cucumber reports with build history trend on Github-pages. How can we do that?

**Comment by jamietanna** [comment]
That I'm not sure, sorry. I would assume there's already something you can use for the build history trend and you can just point it to the Cucumber (JUnit) reports

**Comment by damianszczepanik** [comment]
> Thanks @jamietanna , definitely would go through the repo. Also we need to use the functionality with github actions to deploy cucumber reports with build history trend on Github-pages. How can we do that?

As this is done on this project https://github.com/damianszczepanik/cucumber-reporting/blob/master/.github/workflows/github-pages.yml
