### ISSUE TITLE
Not able to see Previous Build and Lastest Build option in top menu

### ISSUE THREAD

**Issue by SavitaKhilnani** [damianszczepanik/cucumber-reporting#1076]
Not able to see Previous Build and Lastest Build option in top menu
Do I need to do any configuration changes to be able to reflect the same

![image](https://user-images.githubusercontent.com/89079744/194059437-b633572b-9525-4d15-a719-e8fe94de6673.png)

**Comment by damianszczepanik** [comment]
Jenkins plugin has this feature, this library is context-less
