### ISSUE TITLE
net.masterthought.cucumber.ValidationException: Passed files have no features! after upgrade to 7.3.0

### ISSUE THREAD

**Issue by adarshhm6** [damianszczepanik/cucumber-reporting#1085]
With [Cucumber-Core-7.0.0](io.cucumber:cucumber-core) and             
me.jvt.cucumber:reporting-plugin:7.0.0 which internally brings net.masterthought:cucumber-reporting:5.6.0 able to get the PrettyReport and HTML report successfully. 

Without any changes to feature file and source code,
On upgrading dependency Cucumber-core to 7.3.0 and me.jvt.cucumber-reporting-plugin to 7.3.0 which internally brings net.masterthought:cucumber-reporting:5.7.0 getting Passed files have no features error.

Intention was to update to latest version which is 7.9.0 and use latest version of html-formatter but however reporting-plugin still is with 7.3.0 so tried to keep it sync with both modules used 7.3.0 resulting in Passed file have no features error. Any significant changes  or version compatibility needs to be checked or we should use 7.0.0 only for reporting to get Pretty Reports.

net.masterthought.cucumber.ValidationException: Passed files have no features!
![image](https://user-images.githubusercontent.com/56758173/206518747-e36b86b8-f5ca-4bac-b025-2bf5895640e2.png)

**Comment by JamieFlournoy** [comment]
@adarshhm6 , I am seeing the same issue with Cucumber from 7.0.0 through 7.1.0 when using this (net.masterthought:cucumber-reporting:5.7.4) project.

You closed this issue as completed - what was your resolution for this? https://xkcd.com/979/

**Comment by adarshhm6** [comment]
@JamieFlournoy I didn't checked that there was already an issue(https://github.com/damianszczepanik/cucumber-reporting/issues/1033) where resolution provided as files which are passed has no features. 
Since my plan was to upgrade to 7.9.0 of Cucumber, I didn't wish to keep this open with half information as I am trying to upgrade Cucumber to 7.9.0 and see with me.jvt.cucumber:reporting-plugin to 7.3.0 which internally takes net.masterthought:cucumber-reporting:5.7.0. You can reopen the issue and share further details.

**Comment by adarshhm6** [comment]
Reopening this as this issue still persists with 7.3.0 version of Cucumber 

On upgrading dependency Cucumber-core to 7.3.0 and me.jvt.cucumber-reporting-plugin to 7.3.0 which internally brings net.masterthought:cucumber-reporting:5.7.0 getting Passed files have no features error.

**Comment by damianszczepanik** [comment]
you have provided invalid JSON files and that's why you get this error - check JSON file you passed as input

**Comment by adarshhm6** [comment]
@damianszczepanik 
I am running from command line. There is no change in the command. Only vetrsion is modified from 7.0.0 to 7.3.0
java -DAUTOMATION_LOG_PATH=<LogPath> -DAUTOMATION_CONFIG=<ConfigPath> -cp   <PathToConf>\conf -cp <PathToJar>\target\automation\lib\automation-glue-1.0-SNAPSHOT-fat.jar io.cucumber.core.cli.Main  <PathToMainFile>\conf --glue <gluePackagePath> -t ""@Sanity"" -p me.jvt.cucumber.report.PrettyReports:<reportPath>\pretty -
p html:<reportPath>\html\report.html  -p rerun:<reportPath>\rerun\rerun.txt

When I try with cucumber 7.0.0 I get json has 1 feature for tag @Sanity but with 7.3.0 it's getting 0 features. There are no changes other than the version.
