### ISSUE TITLE
Is there a way to store cucumber reports into Jenkins workspace?

### ISSUE THREAD

**Issue by Enigmaderockz** [damianszczepanik/cucumber-reporting#1086]
I can see that cucumber report is getting generated and displaying on the main page but is there any location where we can store this HTML in jenkins workspace?
I am running Jenkins in unix.

**Comment by damianszczepanik** [comment]
Stored on the directory where build hosts its information https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/ReportBuilder.java#L46
