### ISSUE TITLE
Build Execution Date on horizontal axis

### ISSUE THREAD

**Issue by SavitaKhilnani** [damianszczepanik/cucumber-reporting#1096]
Is it by any chance possible to get the **date of build execution** on horizonal axis instead of build number?
![image](https://github.com/damianszczepanik/cucumber-reporting/assets/89079744/c635ba7e-965f-426f-b281-c41870f57625)

**Comment by damianszczepanik** [comment]
Yes but this won't work comfortable if you build several times per day. That's why I have decided to put build number here

**Comment by SavitaKhilnani** [comment]
yeah understood, can you help where would the changes be required if we want to see the date of execution instead of build number

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/resources/templates/js/trends-chart.js.vm#L3 and `buildNumbers` is created by Java code
