### ISSUE TITLE
Remove Flash

### ISSUE THREAD

**Issue by wokier** [damianszczepanik/cucumber-reporting#110]
Please find a web standard alternative to flash for the graphs

**Comment by damianszczepanik** [comment]
You can use JS or Flash depends how you configure plugin.

[Here](https://github.com/masterthought/cucumber-reporting) you have an example

**Comment by wokier** [comment]
Nice, and i have seen the option on the jenkins plugin configuration

**Comment by SirLenz0rlot** [comment]
As flash :zap: isn't much of a standard anymore, 
I wouldn't mind if flashCharts was disabled by default 
(even though I have to admit they look a bit prettier than the javascript ones).

**Comment by damianszczepanik** [comment]
Default option should be implemented in jenkins plugin project (not this one) however I think that UI is better for Flash :)
