### ISSUE TITLE
 Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"

### ISSUE THREAD

**Issue by SavitaKhilnani** [damianszczepanik/cucumber-reporting#1102]
facing issue while deploying reports to gh-pages
  **_! [rejected]          gh-pages -> gh-pages (fetch first)_**
few scheduled Workflow run in parallel, which is causing this issue
to overcome this we tried adding a step before deploying reports to gh-pages,  to sync local gh-pages with remote gh-pages by taking the lates pull of gh-pages, but that does not seem to work

![screenshot1](https://github.com/damianszczepanik/cucumber-reporting/assets/89079744/8bae0261-02b0-471f-8867-4b10d5628702)

**Comment by damianszczepanik** [comment]
Not the scope of this project
