### ISSUE TITLE
Qualifier missing from the report-feature html

### ISSUE THREAD

**Issue by itkhanz** [damianszczepanik/cucumber-reporting#1105]
Hi,
I am running tests in parallel (same feature files in parallel on different devices).
I added a qualifier for my json reports to be able to differentiate the test results from multiple cucumber json files:

```
configuration.setQualifier("android-cucumber-report", System.getProperty("ANDROID_INFO"));
configuration.setQualifier("ios-cucumber-report", System.getProperty("IOS_INFO"));
```

This is how the overview-feature html looks like:

![Screenshot 2023-07-27 at 02 18 56](https://github.com/damianszczepanik/cucumber-reporting/assets/62521743/bb91ad9a-34c2-4805-80af-197e5cff3344)

However when I click on any feature to navigate to report-feature html file, then this qualifier information is missing over there.

![Screenshot 2023-07-27 at 02 19 20](https://github.com/damianszczepanik/cucumber-reporting/assets/62521743/4653e905-1781-4888-a0b8-ca2ead23857b)

I would like to be able to access this qualifier information on the feature pages of the report as well. Ideally both in the table in top and next to the feature name. So while looking at the feature i can easily recognise the qualifier without having to navigate back to the overview page.

I also added the presentation mode as parallel
`configuration.addPresentationModes(PresentationMode.PARALLEL_TESTING);
`
but it is not displaying the target column probably because the Runner is different for each platform. Although the cucumber runner is different but the same feature files are getting executed, so should not it add target column?

Could you please provide some information if this is possible with the existing reports?

I am using following version of libraries:
cucumber-java 7.13.0
cucumber-testng 7.13.0
cucumber-reporting 5.7.5
JDK 17.0.2

**Comment by damianszczepanik** [comment]
Looks like this is a gap. Will take a look what is the effort to improve it
