### ISSUE TITLE
Not able to log in cucumber-reporting

### ISSUE THREAD

**Issue by itkhanz** [damianszczepanik/cucumber-reporting#1106]
Hi,
Is it possible to attach the log4j log files to report? or add logging capability to the report just like we can add the logging information in other reporting libraries like Extent Reports.

I could not find any information about logging in masterthought cucumber-reporting.

Since the report gets generated from cucumber json files so I am not sure whether it is possible to add logs to our test steps in the report.

Could you provide some information in this context?

**Comment by damianszczepanik** [comment]
Only if you attach logs to json report
