### ISSUE TITLE
Reporting url changed

### ISSUE THREAD

**Issue by vanatomas** [damianszczepanik/cucumber-reporting#1112]
My team recently upgraded from 4.1.1 to 5.7.6 version as we did cucumber ver upgrade as well. Reports are generated and available. Yet url changed as not showing from which folder and which feature file is in question
old report - https://xxxxxxxxx/BE-BDD-Cloud/BDD-Regression/feature%252FGTA-CLOUD/915/Cucumber_report/report-feature_balances-PR_Balance_CAN_WORKED_TIME_FTPT_EX_Accural_SetUp-feature.html
so we would know feature name  is PR_Balance_CAN_WORKED_TIME_FTPT_EX_Accural_SetUp and located under balances folder
yet with new url is changed
https://cxxxxxxxxxBE-BDD-Cloud/BDD-Regression/feature%252FGTA-CLOUD/920/Cucumber_report/report-feature_116_3781429189.html
116_3781429189 seems like corresponds to balances-PR_Balance_CAN_WORKED_TIME_FTPT_EX_Accural_SetUp, but when there are over several hundred features, this will not help

**Comment by damianszczepanik** [comment]
This is why new version is 5.x and not 4.2
New features require redesign url name to hash. This is by design

**Comment by vanatomas** [comment]
@damianszczepanik thank you on reply, is there a way to modify this? As it is useful for opening tickets and locating correct feature.

**Comment by damianszczepanik** [comment]
Downgrade the plugin or fix it by implementing expected solution by forking this git repository.
