### ISSUE TITLE
Any current way or future plans to support reports while running Cukes with the parallel_tests gem?

### ISSUE THREAD

**Issue by farooqyousuf** [damianszczepanik/cucumber-reporting#114]

**Comment by kingsleyh** [comment]
You mean when running with sandwich or mojo? Or in Jenkins

**Comment by farooqyousuf** [comment]
Jenkins. I want the reports to be accessible from Jenkins (either consolidated or separate, consolidated would be nice)

**Comment by kingsleyh** [comment]
I’m not sure. It sounds unlikely since cucumber reports is written in Java. running in parallel would not be such an issue but there is no way I can think of that would integrate with a ruby gem.

**Comment by damianszczepanik** [comment]
I also don't see reason for this request. Reports should be generated within a few seconds and adding support for parallel execution doesn't make sense
