### ISSUE TITLE
Can we customize the new cucumber report 

### ISSUE THREAD

**Issue by Karthi29** [damianszczepanik/cucumber-reporting#115]
1) I want to generate more graph instead of the standard graph display in cucumber. and if so how to do.

2) or else can we give the different input as json which cucumber will accept and generate new report.

**Comment by damianszczepanik** [comment]
We'd rather don't add more reports but you are more than welcome to fork this project and add reports that are helpful for you!

**Comment by damianszczepanik** [comment]
Reports are not ready for this change and big refactoring needs to be done before this. Including new template framework
