### ISSUE TITLE
Cucumber html report screen is blur and couldn't able to access the report 

### ISSUE THREAD

**Issue by lavanya-vnix** [damianszczepanik/cucumber-reporting#1151]
Using cucumber-js automation testing, after all test cases run html report screen is not visible properly and looks like blur screen action couldn't perform on it.

1. Imported - `
const fs = require('fs');
const path = require('path');
const reporter = require('cucumber-html-reporter');

2. In package.json using version - "cucumber-html-reporter": "^7.1.0"

3. Command to run - "sudo npx cucumber-js features/ -f json:test/report/cucumber_report.json && node index.js"
Can anyone help me to fix this issue?

when run all test cases html report looks like blur and not actionable, 
![image](https://github.com/damianszczepanik/cucumber-reporting/assets/50191833/add947a6-94b3-46e6-800c-64de51d49212)

When run for single module like login able to view proper screen as below, 
![image](https://github.com/damianszczepanik/cucumber-reporting/assets/50191833/88833ed9-855d-4237-b1b0-4c6ee4863156)

**Comment by damianszczepanik** [comment]
Screenshots you have attached are not generated by this project
