### ISSUE TITLE
Publish cucumber results as a report is not displayed in Jenkins Post build actions

### ISSUE THREAD

**Issue by Aswini999** [damianszczepanik/cucumber-reporting#116]
* Installed the cucumber-reporting  plugin.  
* "Publish cucumber results as a Report" is not displaying in "Post Build Actions list" 

Please help us as soon as possible as I'm in very much need of it.

Note: FYI... , We are able to see the reports when it was cucumber-jvm-reporting.
![post-build-actions](https://cloud.githubusercontent.com/assets/5479114/8613005/58d29ada-26f7-11e5-8f59-ed35fc727063.png)

**Comment by damianszczepanik** [comment]
Which Jenkins version are you using?
Did you check console/log to see if there is no exception?

**Comment by damianszczepanik** [comment]
Looks like problem with Jenkins, not plugin
