### ISSUE TITLE
LICENSE error reported by Snyk scan

### ISSUE THREAD

**Issue by JitendraSingh2TR** [damianszczepanik/cucumber-reporting#1196]
I scanned our automation project with Snyk. 
our team uses cucumber-reporting as a dependency. 

The output displays the following error:

```
License issues:
 

  ✗ LGPL-2.1 license [Medium Severity][https://snyk.io/vuln/snyk:lic:maven:net.masterthought:cucumber-reporting:LGPL-2.1] in net.masterthought:cucumber-reporting@5.7.8
    introduced by net.masterthought:cucumber-reporting@5.7.8
```

I see that the cucumber-reporting project is already Snyk monitored.

![image](https://github.com/user-attachments/assets/eceedda1-6221-4e6a-9000-ee567b0c2541)

How to get this resolved?

**Comment by SoumyaRathiTR** [comment]
Hi @damianszczepanik, can you please help us out with above license issue as it's causing vulnerabilities in our project.

**Comment by damianszczepanik** [comment]
Scanning was fixed, no more issues
