### ISSUE TITLE
Is it possible to not create html file for each tag on the project?

### ISSUE THREAD

**Issue by MikeSurio** [damianszczepanik/cucumber-reporting#1200]
![image](https://github.com/user-attachments/assets/0ac33c34-b0a7-46fc-a2a2-52a7b8335e54)
![image](https://github.com/user-attachments/assets/f0bc13ca-e823-443d-9d8d-6aaf54928e4f)

**Comment by damianszczepanik** [comment]
You can configure this but setting https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/Configuration.java#L199
