### ISSUE TITLE
[Question] Is there any way to choose only specific columns to display in report ?

### ISSUE THREAD

**Issue by chik145** [damianszczepanik/cucumber-reporting#1206]
i want to hide below columns sections from report.

![image](https://github.com/user-attachments/assets/28bb1b5c-3c2b-401c-822a-6f5bebf0668d)

please let me know if it's possible or not?
if not then, would you please provide an option in code implementation for choosing only required columns??

**Comment by damianszczepanik** [comment]
There is no such feature
