### ISSUE TITLE
Our jenkins storge is getting full as the cucumber reports are generated for multiple pipelines.

### ISSUE THREAD

**Issue by sant0sh** [damianszczepanik/cucumber-reporting#1207]
Our jenkins storge is getting full as the cucumber reports are generated for multiple pipelines. Our Jenkins has a storage restriction and we wanted to store jenkins results to any external storage like COS or Git. Is there a way to do it without loosing the pretty ui provided by jenkins and cucumber.

**Comment by damianszczepanik** [comment]
You can publish results with https://github.com/jenkinsci/build-history-manager-plugin then zip and copy to external storage and delete artifacts with https://github.com/jenkinsci/build-history-manager-plugin so then you can release storage and have long build retention
