### ISSUE TITLE
How to add classification level or generate a new HTML file with more custom classification level

### ISSUE THREAD

**Issue by ArthurRallon** [damianszczepanik/cucumber-reporting#1211]
Hi there,
I’ve been using cucumber-reporting for a while now and I’m loving it.
I want to add a new classification level to create a hierarchy like Application -> Feature -> Scenario -> Step.
Currently, it only provides Feature -> Scenario -> Step.
Could you please tell me how to do this?
Thanks! :)

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/java/LiveDemoTest.java -> https://damianszczepanik.github.io/cucumber-html-reports/overview-features.html
