### ISSUE TITLE
HTML report generation taking unusually long time

### ISSUE THREAD

**Issue by sanintel3** [damianszczepanik/cucumber-reporting#122]
With json file of size ~150MB it's taking an hour to generate HTML reports. When I profiled the execution I found out that ReportInformation.processFeatures() is taking very long time. Looks like  time complexity of algorithm that has been used to derive the relationships is becoming worse with growing size of cucumber steps.

**Comment by kingsleyh** [comment]
if you send me the big json file I can look into performance improvement - kingsley at masterthought dot net

**Comment by sanintel3** [comment]
I'm afraid I can't do that due to confidentiality.

**Comment by damianszczepanik** [comment]
150? I'm  impressed.  That would be a challenge  for performance!

**Comment by kingsleyh** [comment]
ok - If someone sends me a valid very large json file I will attempt to improve performance

**Comment by kingsleyh** [comment]
I guess its full of image snapshots? I would try to reduce the images and increase the heap on your jenkins master

**Comment by kingsleyh** [comment]
Maybe you could sanitize it before sending

**Comment by sanintel3** [comment]
kingsleyh,
Apologies for delayed response. 
I have tried to generate the reports by tweaking heap size up to 4GB locally and I haven't really seen any improvement in the performance.  It's really hard to sanitize the file, so I can't share that file. Below is the metadata which might be helpful to reproduce the issue.

Total Features: 539
Total Scenarios: 11214
Total Steps: 152405
Json file size: 110 MB

I'm suspecting there is some performance issue in ReportInformation.processFeatures() method which basically loops through the json file to process tags. 

Would it be possible to process tags information optionally based on a flag/plugin property? i.e. if any one is not really interested to know the statistics based on tags can we disabled tag processing (which definitely improves performance of reports generation)?

**Comment by sanintel3** [comment]
I have made changes locally to disable tag processing and it just took 20 secs to generate the html reports with the same json file. Please let me know is there any feasibility to incorporate disabling tag processing functionality based on plugin configuration?

**Comment by damianszczepanik** [comment]
Just to be sure: you have removed all @tags from the json report and then generation took 20sec?

If this speeds up processing that it might be helpful to find what is going on with tags that it takes so long to complete report.

**Comment by sanintel3** [comment]
I have commented out code relating to processing tags, that updates tagMap
data structure in ReportInformation class's processFeatures method.

**Comment by sanintel3** [comment]
I have created pull request to make tag report generation optional. Could you please review and let me know whether it's a valid feature that can be accepted

**Comment by sanintel3** [comment]
We use lot of tagging on feature files and this what is slowing down the report generation. Even though we don't much rely on tags to run a subset of cucumber features, still for some legacy reason we keep on adding tags to feature files. So, after cleaning up all tags report generation is pretty quick. It's now taking 30 secs and previously it was over an hour.

**Comment by kingsleyh** [comment]
I believe the tag reporting is actually incorrect and needs fixing - but it needs better tests to catch the issues.

The current tag code is based on a simple tagging case. The code is fairly convoluted and I have tried in the past to increase accuracy but it was ways at the expense of performance.

I think the tag code needs a complete rewrite Based on a new set of more in depth test cases

--k

**Comment by sanintel3** [comment]
Thanks for letting me know that, in fact that was my gut feeling after looking at the failed tests when I apply my changes related to re-factoring tag related logic. Let me submit my changes for a review and see how it goes.

**Comment by Seploid** [comment]
Hi guys! 
I think, that "bottleneck" is the U2U method in Util class. We managed to use  separate method to substitute Unicode symbols in JSON in our Framework. So U2U method nothing left to do. 
You can look on org.apache.commons.lang3.StringEscapeUtils.unescapeJava(string) method. 
It really faster - spent time is 1-3 minutes instead of 2-3 hours to build report.

**Comment by damianszczepanik** [comment]
I will check but my candidate is that complexity for tags i much more than expected. I'm looking at this and will try to make is O(n) times faster.

**Comment by damianszczepanik** [comment]
@sanintel3 
I have reduced complexity of the code a lot however there is still lot of stuff that can be rewrite to improve performance.
Can you let me know how current master is compared to previous? Can you now generate report?

**Comment by damianszczepanik** [comment]
Several patches have been applied to improve this process. Let me know if you still have this problem

**Comment by sanintel3** [comment]
Apologies for delayed response and at the moment I dont have access to that
data and I'm afraid I can't test that. But as stated earlier issue has been
resolved by deleting cucumber tags from scenarios, anyhow as we dont need
tags anymore.
