### ISSUE TITLE
Collapse Scenario results on the feature page

### ISSUE THREAD

**Issue by dkirrane** [damianszczepanik/cucumber-reporting#130]
It would be nice is the Feature results page was collapsed.

If the feature results page has many Scenarios it can be cumbersome to find the failing Scenario.
If all Scenarios were collapsed down to the Scenarios Text only and then the user can clickable to expand to see the entire Scenarios with steps

**Comment by damianszczepanik** [comment]
Quite nice feature and should not be hard to implement

**Comment by tommywo** [comment]
i think this was implemented in damianszczepanik/cucumber-reporting/pull/13

**Comment by damianszczepanik** [comment]
That's correct. Hopefully there is not much to do to make it competed.

**Comment by damianszczepanik** [comment]
This is proposal, you may take a look before it will be merged. Not perfect UX but hopefully nice improvement :)![screenshot](https://cloud.githubusercontent.com/assets/9612911/14655017/a38477ec-0680-11e6-905e-f2f922f09f07.png)
