### ISSUE TITLE
wrong description on steps overview page

### ISSUE THREAD

**Issue by tommywo** [damianszczepanik/cucumber-reporting#148]
![steps](https://cloud.githubusercontent.com/assets/11270518/9343713/db4b832a-4603-11e5-93b2-30377b02d7d5.PNG)

**Comment by damianszczepanik** [comment]
This message is generic for all overview pages - parameters needs to be done to make it more flexible.

Thank you for quick review.

**Comment by damianszczepanik** [comment]
Merged
