### ISSUE TITLE
Trouble with viewing flash-based graphs

### ISSUE THREAD

**Issue by restagner** [damianszczepanik/cucumber-reporting#15]
I'm currently using version 0.0.17 of the standalone version.  It's working quite well when run locally.  We've recently created a Bamboo build plan to the tests and we run them using 'mvn clean verify'

This produces the expected reports based on our pom file settings -- we're using Bamboo's artifacts feature to view the reports.  However, the graphs presented on the feature-overview.html page are not being displayed.  They display just fine if the command is run locally (i.e., not through Bamboo).  I've noticed a recent enhancement associated with the "jenkins-cucumber-jvm-reports-plugin-java" plugin
- added an option in the advanced config to turn off the default flash charts and replace them with javascript charts

is this possible to do with the standalone plugin? And, if so, how?

**Comment by somanianands** [comment]
Any update on below thread.. Is Bamboo plugin ready ?

**Comment by kingsleyh** [comment]
Sorry I did not finish it and have no plans to make one now
