### ISSUE TITLE
Tables Disappear Past release 0.3.0

### ISSUE THREAD

**Issue by sfcme19001** [damianszczepanik/cucumber-reporting#182]
If you have steps with data tables in them they do not show up in the reports (with version >= 0.3.0), specifically in the Feature report and Tag report. The reason as far as I can tell, is in this commit 14a07d076f80ab33b8b2d3e4d870697c5f83d9a2 the getCells method was removed from Row.java. However the velocity template needs that getter to access the cells. If I add the getCells method back to Row.java everything works as expected.

**Comment by damianszczepanik** [comment]
Thanks for reply. Yes, this method is required. Let me know if this fixes the problem.

By data tables you mean [this](https://thomassundberg.wordpress.com/2014/06/30/cucumber-data-tables/) example?

**Comment by sfcme19001** [comment]
Thanks for the quick turnaround. I verified your patch resolves the issue. 
Lastly, yes your data table example is what I meant. To be completely clear any step in a normal scenario (not scenario outline) that has a table of pipe delimitated data. For example:
Given some step:
| header1 | header2 |
| value1   | value2    |

What was happening is velocity would create the row and not be able to access the cells. So in the report we would see empty lines for every row in the table. Thanks again for the fix.

**Comment by damianszczepanik** [comment]
I will try to release soon.

Can you give me the json file with data table so I can put this into an example to the project (to avoid next regression)?

**Comment by sfcme19001** [comment]
just created a pull request with an example json in src/test/resources/tableErrorExample.json

**Comment by sfcme19001** [comment]
https://github.com/damianszczepanik/cucumber-reporting/pull/187
