### ISSUE TITLE
Table has wrong header for tag

### ISSUE THREAD

**Issue by tommywo** [damianszczepanik/cucumber-reporting#185]
![screen shot 2015-09-10 at 07 22 50](https://cloud.githubusercontent.com/assets/11270518/9780721/b05eb520-578c-11e5-9945-70f00519416a.png)

**Comment by damianszczepanik** [comment]
What's wrong with this table?

**Comment by tommywo** [comment]
First column has 'Feature' header instead of 'Tag' like before: 
![Tag overview](https://github.com/damianszczepanik/cucumber-reporting/raw/master/.README/tag-overview.png)
