### ISSUE TITLE
Bitmaps not supported anymore

### ISSUE THREAD

**Issue by kipliklotrika** [damianszczepanik/cucumber-reporting#197]
Version 0.4.0 reports that it doesn't support embedded bitmaps.
> Attachment number 1, has unsupported mimetype 'image/bmp'.

**Comment by tommywo** [comment]
Before such embedding was handled like it would be 'image/png' type. Oddly browser displays it poperly.
I've created a PR with a fix.
By the way, selenium's `((TakesScreenshot)driver).getScreenshotAs(OutputType.BYTES)` provides screenshot in a png format, but when embedding it in cucumber you have to delare it's mimetype, so you could declare it wrongly.

**Comment by damianszczepanik** [comment]
I'm using PNG as screenshot. Would be useful, thanks!
