### ISSUE TITLE
All links to screenshot opens first first screenshot, not selected

### ISSUE THREAD

**Issue by damianszczepanik** [damianszczepanik/cucumber-reporting#202]
When having more than single screenshots on the page links always opens the first screenshtot instead of selected

**Comment by tommywo** [comment]
I'm not sure if its the same issue but if I embedd the same screenshot in multiple scenarios, i get image embedded in 1st scenario, and links that opens that screenshot in next scenarios. My guess is that [contentID](https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/json/Embedded.java#L18) is the same, but should be different.

**Comment by damianszczepanik** [comment]
Fixed
