### ISSUE TITLE
Report generation and consolidation for Multi maven components

### ISSUE THREAD

**Issue by sagarshah1983** [damianszczepanik/cucumber-reporting#210]
Is there a way to generate consolidated HTML reports from different/multiple JSON reports.
I have multiple maven components, each generated JSON reports for specific components. But I need a summary of all components together in HTML format.

Does this plugin support consolidating and parsing multiple JSON reports and then generating single HTML report for all maven components together or are there any plans further? 
If not, is there a way to generate common JSON report (in first place) for all different maven components.

Please advise.

Appreciate!

Regards,
Sagar

**Comment by damianszczepanik** [comment]
like this?
https://github.com/damianszczepanik/cucumber-reporting#usage

**Comment by sagarshah1983** [comment]
Great! That's exactly what I am looking for.
But is there a way to configure this as part of Maven build plugins. Does the maven plugin supports multiple JSON file as input?

Appreciate!

Regards,
Sagar

**Comment by damianszczepanik** [comment]
I believe it does. If not you can make it happen by pulling this feature

https://github.com/damianszczepanik/maven-cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/CucumberReportGeneratorMojo.java#L107

**Comment by sagarshah1983** [comment]
That worked like a charm!.
Thanks.

Regards,
Sagar
