### ISSUE TITLE
Not able to generate reports Java (java.lang.IllegalArgumentException: URI is not hierarchical)

### ISSUE THREAD

**Issue by saikrishna321** [damianszczepanik/cucumber-reporting#216]
This is ma below code when i run, i get java.lang.IllegalArgumentException: URI is not hierarchical

public static void generateReports() throws VelocityException, IOException{
		String pluginUrlPath = "";
		String buildNumber = "1";
		String buildProject = "cucumber-jvm";
		boolean skippedFails = true;
		boolean pendingFails = true;
		boolean undefinedFails = true;
		boolean missingFails = true;
		boolean flashCharts = true;
		boolean runWithJenkins = false;
		boolean highCharts = true;
		boolean parallelTesting = false;
        list.add("/Users/saikrisv/Documents/workspace/com.dry.run2/target/Second.json");
        list.add("/Users/saikrisv/Documents/workspace/com.dry.run2/target/Second.json");
        ReportBuilder reportBuilder = new ReportBuilder(list, reportOutputDirectory, pluginUrlPath, buildNumber,
        	    buildProject, skippedFails, pendingFails, undefinedFails, missingFails, flashCharts, runWithJenkins, highCharts, parallelTesting);
		reportBuilder.generateReports();
	}

**Comment by saikrishna321** [comment]
@kingsleyh  can u help me with this ?

**Comment by saikrishna321** [comment]
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.(File.java:418)
	at net.masterthought.cucumber.ReportBuilder.copyResource(ReportBuilder.java:181)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:149)
	at com.test.ImageComp.generateReports(ImageComp.java:81)
	at com.test.ImageComp.main(ImageComp.java:31)

**Comment by damianszczepanik** [comment]
Can you check whether #215 fixes your problem?

**Comment by damianszczepanik** [comment]
It does, looks like problem after upgrading Jenkins to newer version. I will release new plugin.
