### ISSUE TITLE
File not found exception related to too many open files

### ISSUE THREAD

**Issue by pchoi0** [damianszczepanik/cucumber-reporting#218]
Version: 0.4.0
OS: Linux Redhat
There seems to be a problem when there is a large number of cucumber result json files provided to the ReportBuilder.  We were ok with report generation until the number of json files have reached around 6000.  In ReportParser, it seems the FileReader objects constructed from json files are not explicitly closed and we’re thinking this could be the cause of the exception.  If this is a bug, can a fix be provided to close the FileReader after each read?  The exception occurs after a few seconds of report generation kick off.

build   08-Nov-2015 05:27:13    Caused by: java.lang.RuntimeException: Error configuring Log4JLogChute :
build   08-Nov-2015 05:27:13            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
build   08-Nov-2015 05:27:13            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
build   08-Nov-2015 05:27:13            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
build   08-Nov-2015 05:27:13            at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
build   08-Nov-2015 05:27:13            at org.apache.velocity.util.ExceptionUtils.createWithCause(ExceptionUtils.java:67)
build   08-Nov-2015 05:27:13            at org.apache.velocity.util.ExceptionUtils.createRuntimeException(ExceptionUtils.java:45)
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.log.Log4JLogChute.initAppender(Log4JLogChute.java:133)
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.log.Log4JLogChute.init(Log4JLogChute.java:85)
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.log.LogManager.createLogChute(LogManager.java:157)
build   08-Nov-2015 05:27:13            ... 16 more
build   08-Nov-2015 05:27:13    Caused by: java.io.FileNotFoundException: build_dir/acceptance/target/cucumber/cuc
umber-reports/velocity.log (Too many open files)
build   08-Nov-2015 05:27:13            at java.io.FileOutputStream.open(Native Method)
build   08-Nov-2015 05:27:13            at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
build   08-Nov-2015 05:27:13            at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
build   08-Nov-2015 05:27:13            at org.apache.log4j.FileAppender.setFile(FileAppender.java:301)
build   08-Nov-2015 05:27:13            at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:194)
build   08-Nov-2015 05:27:13            at org.apache.log4j.FileAppender.<init>(FileAppender.java:109)
build   08-Nov-2015 05:27:13            at org.apache.log4j.RollingFileAppender.<init>(RollingFileAppender.java:72)
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.log.Log4JLogChute.initAppender(Log4JLogChute.java:118)

**Comment by damianszczepanik** [comment]
Can you paste full stacktrace since this one does not look like cucumber problem?

**Comment by pchoi0** [comment]
Here it is.

build   08-Nov-2015 05:27:13    ERROR   2015-11-08 05:27:13,107 [proj_pkg.plugins.reportgenerator.ReportGenerator.main()] ReportGenerator - There were issues with the report generation:
build   08-Nov-2015 05:27:13    org.apache.velocity.exception.VelocityException: Error initializing log: Failed to initialize an instance of org.apache.velocity.runtime.log.Log4JLogChute with the current runtime configuration.
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.RuntimeInstance.initializeLog(RuntimeInstance.java:875)
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:262)
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:646)
build   08-Nov-2015 05:27:13            at org.apache.velocity.app.VelocityEngine.init(VelocityEngine.java:116)
build   08-Nov-2015 05:27:13            at net.masterthought.cucumber.generators.AbstractPage.generatePage(AbstractPage.java:47)
build   08-Nov-2015 05:27:13            at net.masterthought.cucumber.generators.ErrorPage.generatePage(ErrorPage.java:20)
build   08-Nov-2015 05:27:13            at net.masterthought.cucumber.ReportBuilder.generateErrorPage(ReportBuilder.java:272)
build   08-Nov-2015 05:27:13            at net.masterthought.cucumber.ReportBuilder.<init>(ReportBuilder.java:201)
build   08-Nov-2015 05:27:13            at proj_pkg.plugins.reportgenerator.ReportGenerator.main(ReportGenerator.java:73)
build   08-Nov-2015 05:27:13            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
build   08-Nov-2015 05:27:13            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
build   08-Nov-2015 05:27:13            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
build   08-Nov-2015 05:27:13            at java.lang.reflect.Method.invoke(Method.java:483)
build   08-Nov-2015 05:27:13            at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
build   08-Nov-2015 05:27:13            at java.lang.Thread.run(Thread.java:745)
build   08-Nov-2015 05:27:13    Caused by: org.apache.velocity.exception.VelocityException: Failed to initialize an instance of org.apache.velocity.runtime.log.Log4JLogChute with the current runtime configuration.
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.log.LogManager.createLogChute(LogManager.java:220)
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.log.LogManager.updateLog(LogManager.java:269)
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.RuntimeInstance.initializeLog(RuntimeInstance.java:871)
build   08-Nov-2015 05:27:13            ... 14 more
build   08-Nov-2015 05:27:13    Caused by: java.lang.RuntimeException: Error configuring Log4JLogChute :
build   08-Nov-2015 05:27:13            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
build   08-Nov-2015 05:27:13            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
build   08-Nov-2015 05:27:13            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
build   08-Nov-2015 05:27:13            at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
build   08-Nov-2015 05:27:13            at org.apache.velocity.util.ExceptionUtils.createWithCause(ExceptionUtils.java:67)
build   08-Nov-2015 05:27:13            at org.apache.velocity.util.ExceptionUtils.createRuntimeException(ExceptionUtils.java:45)
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.log.Log4JLogChute.initAppender(Log4JLogChute.java:133)
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.log.Log4JLogChute.init(Log4JLogChute.java:85)
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.log.LogManager.createLogChute(LogManager.java:157)
build   08-Nov-2015 05:27:13            ... 16 more
build   08-Nov-2015 05:27:13    Caused by: java.io.FileNotFoundException: /build_dir/acceptance/target/cucumber/cucumber-reports/velocity.log (Too many open files)
build   08-Nov-2015 05:27:13            at java.io.FileOutputStream.open(Native Method)
build   08-Nov-2015 05:27:13            at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
build   08-Nov-2015 05:27:13            at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
build   08-Nov-2015 05:27:13            at org.apache.log4j.FileAppender.setFile(FileAppender.java:301)
build   08-Nov-2015 05:27:13            at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:194)
build   08-Nov-2015 05:27:13            at org.apache.log4j.FileAppender.<init>(FileAppender.java:109)
build   08-Nov-2015 05:27:13            at org.apache.log4j.RollingFileAppender.<init>(RollingFileAppender.java:72)
build   08-Nov-2015 05:27:13            at org.apache.velocity.runtime.log.Log4JLogChute.initAppender(Log4JLogChute.java:118)
build   08-Nov-2015 05:27:13            ... 18 more

**Comment by damianszczepanik** [comment]
Looks like the source of the problem comes was born here:
``
 build 08-Nov-2015 05:27:13 org.apache.velocity.exception.VelocityException: Error initializing log: Failed to initialize an instance of org.apache.velocity.runtime.log.Log4JLogChute with the current runtime configuration.
``

but it does not look like problem with cucumber or some dependency on Jenkins

**Comment by stanislav-antufeev** [comment]
Hi Damian.
Regarding that issue, I was dealing with the same problem.
If you take a loot at the class ReportParser:38
Feature[] features = gson.fromJson(new FileReader(jsonFile), Feature[].class);
Here we are creating Reader from File and then just pass it into GSON library, but don't close it at all.
In that case cucumber-reporting library generates a lot of opened file descriptors in file system and can reach threshold value. On Linux system you can see that value using command ulimit -n.

**Comment by damianszczepanik** [comment]
In case of big number json files that might be a problem. That was fixed and will be released with next version.
