### ISSUE TITLE
when to create a new report ?

### ISSUE THREAD

**Issue by atomsk81** [damianszczepanik/cucumber-reporting#228]
I'm trying to create a new report but it seems that it is always being generated prior the cucumber.json file. As a result my report is empty of scenarios and steps run. 

should i create the report in my test runner classs ? do you have any examples ? At the moment I have defined a class as a service which has a method named createReport. I autowire this class within my tests and call the createReport method, but as i told earlier , cucumber.json is the last thing that gets generated by cucumber whereas createReport() is executed during test runtime.

i have also tried calling the method with the @after hook but still the json report is generated after that

**Comment by damianszczepanik** [comment]
If you have problem with generating report you'd better check with https://github.com/cucumber/cucumber-jvm where I believe you can find some useful examples and answers for you question :-)
