### ISSUE TITLE
Continually getting NullPointerException

### ISSUE THREAD

**Issue by kschurr** [damianszczepanik/cucumber-reporting#237]
Hi,
I am trying to set up running cucumber reports in a project as smoke tests, and cannot get around a NullPointerException when triggering the profile that runs the plugin.  Can you please help?  

The error is as follows:
[INFO] --- maven-cucumber-reporting:0.0.6:generate (execution) @ **project name here**

About to generate
java.io.FileNotFoundException: **\target\cucumber.json (The system cannot find the file specified)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.590 s
[INFO] Finished at: 2015-11-23T11:25:52-05:00
[INFO] Final Memory: 10M/204M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.masterthought:maven-cucumber-reporting:0.0.6:
generate (execution) on project rxspend-app: Error Found: NullPointerException -
> [Help 1]

Applicable code from POM
		<profile>
			<id>smoketest</id>
			<build>
				<plugins>
					<plugin>
            			<groupId>org.codehaus.mojo</groupId>
            			<artifactId>build-helper-maven-plugin</artifactId>
            			<version>1.9.1</version>
            			<executions>
              				<execution>
                				<id>add-source</id>
                				<phase>generate-sources</phase>
                				<goals>
                  					<goal>add-test-source</goal>
                				</goals>
                				<configuration>
                  					<sources>
                    					<source>src/smoketest/java</source>
                  					</sources>
                				</configuration>
              				</execution>
              				<execution>
                				<id>add-resource</id>
                				<phase>generate-sources</phase>
                				<goals>
                  					<goal>add-test-resource</goal>
                				</goals>
                				<configuration>
                  					<resources>
                    					<resource>
                      						<directory>src/smoketest/resources</directory>
                    					</resource>
                  					</resources>
                				</configuration>
              				</execution>
            			</executions>
          			</plugin>
          			<plugin>
		                <groupId>org.apache.maven.plugins</groupId>
		                <artifactId>maven-surefire-plugin</artifactId>
		                <configuration>
		                    <testFailureIgnore>true</testFailureIgnore>
		                </configuration>
		            </plugin>
		            <plugin>
		                <groupId>net.masterthought</groupId>
		                <artifactId>maven-cucumber-reporting</artifactId>
		                <version>0.0.5</version>
		                <executions>
		                    <execution>
		                        <id>execution</id>
		                        <phase>verify</phase>
		                        <goals>
		                            <goal>generate</goal>
		                        </goals>
		                        <configuration>
		                            <projectName>cucumber-jvm-example</projectName>
		                            <outputDirectory>${project.build.directory}/cucumber-html-reports</outputDirectory>
		                            <cucumberOutput>${project.build.directory}/cucumber.json</cucumberOutput>
		                            <enableFlashCharts>false</enableFlashCharts>
		                        </configuration>
		                    </execution>
		                </executions>
		            </plugin>
				</plugins>
			</build>
			<properties>
        		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    		</properties>
		</profile>

			<dependency>
    			<groupId>info.cukes</groupId>
    			<artifactId>cucumber-core</artifactId>
    			<version>${cucumber.version}</version>
    			<scope>test</scope>
			</dependency>
			<dependency>
    			<groupId>info.cukes</groupId>
    			<artifactId>cucumber-java</artifactId>
    			<version>${cucumber.version}</version>
    			<scope>test</scope>
			</dependency>
			<dependency>
    			<groupId>info.cukes</groupId>
    			<artifactId>cucumber-junit</artifactId>
    			<version>${cucumber.version}</version>
    			<scope>test</scope>
			</dependency>
			<dependency>
    			<groupId>info.cukes</groupId>
    			<artifactId>cucumber-picocontainer</artifactId>
    			<version>${cucumber.version}</version>
    			<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>net.masterthought</groupId>
        		<artifactId>maven-cucumber-reporting</artifactId>
        		<version>0.2.1</version>
			</dependency>
<repositories>
	<repository>
		<id>sonatype-releases</id>
                <url>https://oss.sonatype.org/content/repositories/releases/</url>
	</repository>
</repositories>

**Comment by damianszczepanik** [comment]
The problem is not about configuring the plugin but cucumber-jvm itself. Try to run with maven debug mode or ask on https://github.com/cucumber/cucumber-jvm
