### ISSUE TITLE
 Failure to find com.googlecode.totallylazy:totallylazy.jar:991

### ISSUE THREAD

**Issue by Shivaraj05** [damianszczepanik/cucumber-reporting#24]
Hi Kingsleyh,

I am trying to generate cucumber reports using Maven Mojo.

But I am not able to build project. Getting the below error while building using "mvn clean install" command.

[ERROR] Failed to execute goal on project XXXXX(Project_Name): Could not
resolve dependencies for project xxx.xxxx.xxxx.xxx:XXXXX(Project_Name):jar:1.0.0-SNAPSHOT: Failure to find com.googlecode.totallylazy:totally
lazy:jar:991 in https://nexus:8443/nexus/content/groups/public was cached in the
 local repository, resolution will not be reattempted until the update interval
of NexusExternal has elapsed or updates are forced -> [Help 1]

I have added dependency and repository in pom.xml file as below,

<dependency>
            <groupId>com.googlecode.totallylazy</groupId>
            <artifactId>totallylazy</artifactId>
            <version>991</version>
</dependency>

<repositories>
        <repository>
            <id>repo.bodar.com</id>
            <url>http://repo.bodar.com</url>
        </repository>
</repositories>

Please provide solution for this.

Thanks in advance.

**Comment by damianszczepanik** [comment]
The problem with this library might be that it was available over different (not maven-central) repository and somehow it could not be downloaded. This library is not longer present because it was removed in #171

**Comment by TassSinclair** [comment]
(For the benefit of anyone finding this link from a search engine)

totallylazy is available from a custom Maven repository; add the following to your `settings.xml`

```
<repository>
    <id>repo.bodar.com</id>
    <url>http://repo.bodar.com</url>
</repository>
```
