### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1 at templates/pages/featureReport.vm

### ISSUE THREAD

**Issue by paymand** [damianszczepanik/cucumber-reporting#252]
Hi!

I am using Jenkins cucumber-reports-plugin 0.6.0 to display json reports generated by 'cucumber-js'.
Yes, I know that the Javascript implementation is not supported, but it works well when everything is passing.

However, if there's fail in the results I get:
```
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getName' in  class net.masterthought.cucumber.json.Step threw exception java.lang.ArrayIndexOutOfBoundsException: 1 at templates/pages/featureReport.vm[line 64, column 25]
```
You can see the full stack trace here:
https://gist.github.com/paymand/fdc357667060803f1ee9

The json for the failing step which causes the error above:
```json
          {
            "name": "a customer order with status \"Planned\" should be added",
            "line": 9,
            "keyword": "Then ",
            "result": {
              "status": "failed",
              "duration": 63372100,
              "error_message": "AssertionError: expected { Object (_readableState, readable, ...) } to have a deep property 'body.state'"
            },
            "match": {}
          },
```

You can see the same step when passing (which causes no troubles) for comparison:
```json
          {
            "name": "a customer order with status \"Planned\" should be added",
            "line": 9,
            "keyword": "Then ",
            "result": {
              "status": "passed",
              "duration": 112899
            },
            "match": {}
          },
```
Any idea why this happens?

**Comment by damianszczepanik** [comment]
The problem was that error message was formatted assuming that it looks like stacktrace. Yours does not even look like stacktrace so exception was thrown during formatting process.

Will be fixed in next release.

**Comment by paymand** [comment]
Thanks for the quick and smooth fix. I built tested it and it works just fine :+1:

**Comment by tutaidalal** [comment]
Is it alreday fixed ? Can someone please share the verion number where it has been fixed.. I am using 4.7.0 and still getting the issue in very simple step.

Error I am getting after returning from glue code -

Aug 06, 2019 2:56:54 PM net.masterthought.cucumber.ReportParser parseJsonFiles
INFO: File 'C:\Users\nandroy\workspace_New\UnitTest_PATS\report\JSON\AllSanityTestCases.json' contains 1 features
Aug 06, 2019 2:56:55 PM net.masterthought.cucumber.ReportBuilder generateErrorPage
INFO: Unexpected error
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'format' in class net.masterthought.cucumber.util.StepNameFormatter threw exception java.lang.ArrayIndexOutOfBoundsException: 23 at /templates/macros/json/stepName.vm[line 3, column 47]
at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:243)
at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:187)
at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:567)

**Comment by damianszczepanik** [comment]
There is something unusual with JSON file. Needs to be attached for reference.

**Comment by tutaidalal** [comment]
This is only happening if I modify the JSON content with some other value. Below is the Example: 
I am trying to replace the  {Config.MyName} to "tutai" in feature file. Also I have checked that if the replaced value length is more than the variable length then it works fine. here length of "tutai" is 5 which is less than length of "{Config.MyName}". If I use "Tutai Kumar Dalal" it works fine 

Feature File: 

Feature: SamplePrintFile
	Scenario: SamplePrintFile
	Given I print: {Config.MyName}

JSON Output: 

"elements": [
      {
        "line": 9,
        "name": "SamplePrintFile",
        "description": "",
        "id": "sampleprintfile;sampleprintfile",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 652908188,
              "status": "passed"
            },
            "line": 11,
            "name": "I print: tutai",
            "match": {
              "arguments": [
                {
                  "val": " ",
                  "offset": 8
                },
                {
                  "val": "{Config.MyName}",
                  "offset": 9
                }
              ],
              "location": "CommonFrameworkStepDefGlue.printData(String,String)"
            },
            "keyword": "Given "
          }
        ]
      }
    ]

**Comment by damianszczepanik** [comment]
Plugin does not support manual modifications
