### ISSUE TITLE
css files in repository should not be ziped 

### ISSUE THREAD

**Issue by tommywo** [damianszczepanik/cucumber-reporting#256]
having css files zipped makes tracking changes difficult.
I think it would be best to keep it unziped and zip it before building using grunt

**Comment by damianszczepanik** [comment]
Zipped files are not changed but if you have plan to change it to improve ux you are welcome

**Comment by tommywo** [comment]
I've changed css in #206 same as it was in #13. I will move changes from zip, so changes would be tracked. I'm closing it - if I figure something out with grunt, I'll make a pull request
