### ISSUE TITLE
Tags not being reported correctly

### ISSUE THREAD

**Issue by ShoopIndy** [damianszczepanik/cucumber-reporting#26]
Unless I misunderstand intention of the tagging, the per-tag summary and individual tag reports are including scenarios for all tags.

Below is a simple example of this problem.

<pre><code>Given that I have a feature file containing 4 scenarios
And 2 scenarios are tagged with @tag1
And other 2 scenarios are tagged with @tag2
When I view the tag1 report
Then the tag1 report should have a total of 2 scenarios</pre></code>

However, the tag1 report has a total of 4 scenarios.

The source json looks correct to me and I have validated it using http://cucumber-reporting.masterthought.net/.

This problem happens with
- net.masterthought.cucumber-reporting:0.0.21
- Ubuntu 12 and 13
- Ruby 1.9.3 and Ruby 2
- JDK 1.7 and openJDK6 and openJDK7
- chrome and firefox

Please let me know if any other info would help troubleshoot this problem.

This report looks correct to me:
![cukerpt_allscens](https://f.cloud.github.com/assets/873455/549312/bbfab230-c2f6-11e2-9184-c8d7845f8ed9.png)

However, this report shows each tag having 4 scenarios each when they only have 2 each:
![cukerpt_tagstats](https://f.cloud.github.com/assets/873455/549467/025dcac0-c2fa-11e2-83cd-07c467c122c1.png)

...and this report (just for tag1) shows it as having 4 scenarios when it only has 2.

![cukerpt_singletagreport](https://f.cloud.github.com/assets/873455/549471/04e06f32-c2fa-11e2-9577-2b5130553641.png)

**Comment by arjunvk** [comment]
Hey,

Do you have any update on the issue?

PFA the tag report overview that gets generated.

PFB the json code that gets generated:

[
  {
    "id": "view-reports-submitted-by-clients",
    "description": "",
    "name": "View Reports submitted by Clients",
    "keyword": "Feature",
    "line": 1,
    "elements": [
      {
        "after": [
          {
            "result": {
              "duration": 421416607,
              "status": "passed"
            },
            "match": {
              "location": "reports_Submitted_By_Clients.tearDown()"
            }
          }
        ],
        "id": "view-reports-submitted-by-clients;officer-can-view-ers-reports-on-console;;2",
        "tags": [
          {
            "name": "@View_Report",
            "line": 3
          }
        ],
        "before": [
          {
            "result": {
              "duration": 6166754112,
              "status": "passed"
            },
            "match": {
              "location": "reports_Submitted_By_Clients.setup(Scenario)"
            }
          }
        ],
        "description": "",
        "name": "Officer_Can_View_ERS_Reports_On_Console",
        "keyword": "Scenario Outline",
        "line": 12,
        "steps": [
          {
            "result": {
              "duration": 2966412953,
              "status": "passed"
            },
            "name": "The officer has logged into the ERS Management console",
            "keyword": "Given ",
            "line": 5,
            "match": {
              "location": "reports_Submitted_By_Clients.loginIntoERS()"
            }
          },
          {
            "result": {
              "duration": 5442853741,
              "status": "passed"
            },
            "name": "The officer \"Acosta, Mike\" selects a client \"Clyburn, Earl\"",
            "keyword": "When ",
            "line": 6,
            "match": {
              "arguments": [
                {
                  "val": "Acosta, Mike",
                  "offset": 13
                },
                {
                  "val": "Clyburn, Earl",
                  "offset": 45
                }
              ],
              "location": "reports_Submitted_By_Clients.officerSelectsClient(String,String)"
            },
            "matchedColumns": [
              0,
              1
            ]
          },
          {
            "result": {
              "duration": 534167960,
              "status": "passed"
            },
            "name": "Clicks on report 2",
            "keyword": "And ",
            "line": 7,
            "match": {
              "arguments": [
                {
                  "val": "2",
                  "offset": 17
                }
              ],
              "location": "reports_Submitted_By_Clients.selectReport(int)"
            },
            "matchedColumns": [
              2
            ]
          },
          {
            "result": {
              "duration": 975309752,
              "status": "passed"
            },
            "name": "The bottom half of the screen should display the basic information",
            "keyword": "Then ",
            "line": 8,
            "match": {
              "location": "reports_Submitted_By_Clients.verifySummaryReportFields()"
            }
          }
        ],
        "type": "scenario"
      },
      {
        "after": [
          {
            "result": {
              "duration": 355735235,
              "status": "passed"
            },
            "match": {
              "location": "reports_Submitted_By_Clients.tearDown()"
            }
          }
        ],
        "id": "view-reports-submitted-by-clients;officer-can-view-different-clients-reports;;2",
        "tags": [
          {
            "name": "@View_Another_Officer_Client_Report",
            "line": 14
          }
        ],
        "before": [
          {
            "result": {
              "duration": 4980431641,
              "status": "passed"
            },
            "match": {
              "location": "reports_Submitted_By_Clients.setup(Scenario)"
            }
          }
        ],
        "description": "",
        "name": "Officer_Can_View_Different_Clients_Reports",
        "keyword": "Scenario Outline",
        "line": 22,
        "steps": [
          {
            "result": {
              "duration": 2482864087,
              "status": "passed"
            },
            "name": "The officer has logged into the ERS Management console",
            "keyword": "Given ",
            "line": 16,
            "match": {
              "location": "reports_Submitted_By_Clients.loginIntoERS()"
            }
          },
          {
            "result": {
              "duration": 4957179102,
              "status": "passed"
            },
            "name": "The officer \"Acosta, Mike\" selects a client \"Ingram, Larry\"",
            "keyword": "When ",
            "line": 17,
            "match": {
              "arguments": [
                {
                  "val": "Acosta, Mike",
                  "offset": 13
                },
                {
                  "val": "Ingram, Larry",
                  "offset": 45
                }
              ],
              "location": "reports_Submitted_By_Clients.officerSelectsClient(String,String)"
            },
            "matchedColumns": [
              0,
              1
            ]
          },
          {
            "result": {
              "duration": 585502624,
              "status": "passed"
            },
            "name": "A list of reports should be displayed",
            "keyword": "Then ",
            "line": 18,
            "match": {
              "location": "reports_Submitted_By_Clients.displayReportCount()"
            }
          }
        ],
        "type": "scenario"
      },
      {
        "after": [
          {
            "result": {
              "duration": 346389306,
              "status": "passed"
            },
            "match": {
              "location": "reports_Submitted_By_Clients.tearDown()"
            }
          }
        ],
        "id": "view-reports-submitted-by-clients;officer-can-view-different-clients-reports;;3",
        "tags": [
          {
            "name": "@View_Another_Officer_Client_Report",
            "line": 14
          }
        ],
        "before": [
          {
            "result": {
              "duration": 4419922244,
              "status": "passed"
            },
            "match": {
              "location": "reports_Submitted_By_Clients.setup(Scenario)"
            }
          }
        ],
        "description": "",
        "name": "Officer_Can_View_Different_Clients_Reports",
        "keyword": "Scenario Outline",
        "line": 23,
        "steps": [
          {
            "result": {
              "duration": 2363842567,
              "status": "passed"
            },
            "name": "The officer has logged into the ERS Management console",
            "keyword": "Given ",
            "line": 16,
            "match": {
              "location": "reports_Submitted_By_Clients.loginIntoERS()"
            }
          },
          {
            "result": {
              "duration": 6380753093,
              "status": "passed"
            },
            "name": "The officer \"Frisby, Suzette\" selects a client \"Brown, Sonya\"",
            "keyword": "When ",
            "line": 17,
            "match": {
              "arguments": [
                {
                  "val": "Frisby, Suzette",
                  "offset": 13
                },
                {
                  "val": "Brown, Sonya",
                  "offset": 48
                }
              ],
              "location": "reports_Submitted_By_Clients.officerSelectsClient(String,String)"
            },
            "matchedColumns": [
              0,
              1
            ]
          },
          {
            "result": {
              "duration": 496225502,
              "status": "passed"
            },
            "name": "A list of reports should be displayed",
            "keyword": "Then ",
            "line": 18,
            "match": {
              "location": "reports_Submitted_By_Clients.displayReportCount()"
            }
          }
        ],
        "type": "scenario"
      }
    ],
    "uri": "src/FeatureFile/reports_Submitted_By_Clients.feature"
  }
]

Kindly let me know if you need more info.

Thanks,
Arjun

![json](https://cloud.githubusercontent.com/assets/10672569/5877888/d7a07070-a2f0-11e4-9c73-40dc329ac484.jpg)

**Comment by damianszczepanik** [comment]
First problem is already fixed, second example will be fixed with next release. The problem happened when two scenarios have the same name
