### ISSUE TITLE
Scenario count wrong after upgrade from 0.4.0

### ISSUE THREAD

**Issue by kevyau** [damianszczepanik/cucumber-reporting#268]
Previously when running 0.4.0 of the jenkins/cucumber plugin, the total number of scenarios was 404 scenarios, this is consistent with running cucumber locally. 

After upgrading the plugin, the total number of scenarios has now changed to 739 (without any changes to the tests). This looks like it's counting our background steps as passing scenarios.

**Comment by kevyau** [comment]
Is this related to https://github.com/damianszczepanik/cucumber-reporting/issues/86 ?

**Comment by damianszczepanik** [comment]
This is because: background tests are not counted separately any more, there were issue related to tag (counting), some hooks were not counted at all previously.
