### ISSUE TITLE
Build not breaking when a scenario fails

### ISSUE THREAD

**Issue by mehdijouan** [damianszczepanik/cucumber-reporting#275]
Hi,
I've a maven configuration of your plugin like this:
```xml
<plugin>
   <groupId>net.masterthought</groupId>
   <artifactId>maven-cucumber-reporting</artifactId>
   <version>${maven.cucumber.reporting.version}</version>
   <configuration>
      <cucumberOutput>${project.build.directory}/cucumber.json</cucumberOutput>
      <outputDirectory>${project.build.directory}/cucumber-html-reports</outputDirectory>
      <enableFlashCharts>false</enableFlashCharts>
      <checkBuildResult>true</checkBuildResult>
      <skippedFails>true</skippedFails>
      <pendingFails>true</pendingFails>
      <missingFails>true</missingFails>
      <undefinedFails>true</undefinedFails>
   </configuration>
   <executions>
      <execution>
         <id>execution</id>
         <phase>verify</phase>
         <goals>
            <goal>generate</goal>
         </goals>
      </execution>
   </executions>
</plugin>
```

And if I have this results:
```
...
1 Scenarios (1 undefined)
4 Steps (1 undefined, 3 passed)
```
Here is what I got in the html report:
![screen shot 2015-12-23 at 2 43 56 pm](https://cloud.githubusercontent.com/assets/7910165/11977506/c492c33a-a983-11e5-9ef9-3ba19480a6e4.png)

The build is successful as the method ReportBuilder.getBuildStatus() only checks if steps are failed and not if scenario are failed.

My proposal is to check failures on scenario instead of steps : 

```java
   public boolean getBuildStatus() {
        return reportInformation.getTotalScenariosFailed() == 0;
    }
```

**Comment by damianszczepanik** [comment]
There is significant different between build failure and result failure. Build fails when you pass invalid json files, when app crashes etc. It is used for Jenkins. If you want to check if all stesps/scenarios/feature pass you can't check the build status.

**Comment by tommywo** [comment]
Maven-cucumber-reporting is not intended to fail/make maven build unstable, but only generate a report.
Build should be unstable/fail before when running test.

**Comment by RobotWarden** [comment]
How do I make a Jenkins build fail if there are failures in the cucumber results? I've tried setting ignoreFailedTests to false but the build passes in Jenkins.

**Comment by damianszczepanik** [comment]
Plugin provides such functionality, upgrade to recent version and check configuration

**Comment by RobotWarden** [comment]
Confirmed, thanks. Used the following in my Jenkinsfile

cucumber fileIncludePattern: '**/target/cucumber.json', ignoreFailedTests: false, buildStatus: "failed"
