### ISSUE TITLE
1.0.0 version doesn't allow to use custom html tags in the reports

### ISSUE THREAD

**Issue by rommy1204** [damianszczepanik/cucumber-reporting#276]
Hi Damian,

Could you please take a look at the following situation
Previously we used 0.0.23 version of reporting tool
And we used custom tags to add expandable screenshots links or highlighting some key actions like opening / clicking / typing 
You can see them on the screenshot below:
![2015-12-23_1740](https://cloud.githubusercontent.com/assets/10895964/11977445/7213c99c-a99c-11e5-9993-2e33a1d523e9.png)
And for now all tags "<" and ">" escape to &lt; and /&gt;
This makes unavailable using custom html tags inside the report

Do we have any workarounds here or now we can't use them without making a sin for HTML pages replacing escaped characters to initial ones? 

I think it is appeared after fixing this issue: https://github.com/damianszczepanik/cucumber-reporting/issues/49
probably here: https://github.com/damianszczepanik/cucumber-reporting/commit/2491aeee8f530ffe635a92de18ecd6630b357dc7

**Comment by rommy1204** [comment]
Current view of the report is:
![2015-12-23_1749](https://cloud.githubusercontent.com/assets/10895964/11977588/97501e80-a99d-11e5-8661-75b145156ec0.png)
New paddings don't look better. This is new style:
    text-indent: 50px;
I'll be glad to you if you can remove it :)

**Comment by damianszczepanik** [comment]
Honestly, I'm not sure what is the problem. Can you attach json report with the tag and the screenshot diff?

UX has been just improved https://github.com/damianszczepanik/cucumber-reporting/commit/ed16046b6096b782a831fcece23d0b69353f9dab however I'm not sure if this will satisfy you :)

**Comment by rommy1204** [comment]
Hi Damian,
I've created a separated issue for the second comment https://github.com/damianszczepanik/cucumber-reporting/issues/278

**Comment by rommy1204** [comment]
As for the first one - you add screenshots as a BYTE CODE inside JSON file
We are using just links for them and we have these files in the separate folder near from report
It allows as to have screenshots as a separate files and it decreases json size to make easier it's parsing
Even if use initial screenshot functionality - we can't add html tags inside the report, it removes all our tags because of StringEscapeUtils.escapeHtml(text) functions
Can we somehow avoid this escaping?

**Comment by tommywo** [comment]
escaping html was added in #200, to sanitize input and maintaining the same output as other formatters (f.e pretty formatter - since text is printed in console - by default it should not be changed to html elements in report). It would be a great idea to add "do not escape html tags" as opt-in  - there is similar option in ReportNg (org.uncommons.reportng.escape-output property).

**Comment by rommy1204** [comment]
Hi tommywo, I've checked your comment and I agree with you that text printed in console should not be changed to html elements. And we follow this - we don't have html elements in our console, because additional tags we are adding in ReportNgAppender. So we see them only in our reports
Seems like you have changed it here: https://github.com/tommywo/cucumber-reporting/commit/91a6aef951dc2dfe1fe97fbdf0237a5c5c62a928 

Could you please make this escaping optional?

**Comment by damianszczepanik** [comment]
I can switch off escaping so if someone wants to render logs/output/etc as HTML code it should make it by him self.

What is your opinion?

**Comment by Ryxmedia** [comment]
We also use HTML tags in the reports, which are now escaped.
Adding the ability to render the HTML tags correctly again would be great.

**Comment by rommy1204** [comment]
It would be great if we could use html code in output as optional parameter which doesn't use it by default

**Comment by tommywo** [comment]
I've also noticed that html tags error messages aren't escaped. So it is posiible to have selenenium error like this: Element is not clickable at point (167, 403). Other element would receive the click: \<img src="img.png"/> with image embedded. Should escaping html in error messages also be configurable?
