### ISSUE TITLE
Unfriendly padding

### ISSUE THREAD

**Issue by rommy1204** [damianszczepanik/cucumber-reporting#278]
New style 
text-indent: 50px;
This style adds padding from the left side for every new row, but if string is longer than one row - it displays on the second row without this padding
now it looks this way:
![padding_now](https://cloud.githubusercontent.com/assets/10895964/11994379/b035f4ec-aa56-11e5-91bb-fb87a8a4bfd5.png)
before it was like this:
![padding_before](https://cloud.githubusercontent.com/assets/10895964/11994386/baca35ee-aa56-11e5-8403-097f0b97ea4f.png)

Could you please remove/update this style?

**Comment by damianszczepanik** [comment]
Can you share JSON file? my report does not wrap lines but looks like your json has different logs so I need to verify this before patch will be released.

**Comment by rommy1204** [comment]
Hi Damian, yes, sure:
[cucumber.zip](https://github.com/damianszczepanik/cucumber-reporting/files/91789/cucumber.zip)

**Comment by damianszczepanik** [comment]
Fixed. Mind that you need to removed additional \n and br tags which you appended to the end of each line
