### ISSUE TITLE
Blocked script execution 

### ISSUE THREAD

**Issue by saadlu** [damianszczepanik/cucumber-reporting#281]
After installing the plugin, I do not get to see the chart and the reports are not properly styled (table columns are not aligned or padded):

![screen](https://cloud.githubusercontent.com/assets/1028104/12075948/8182075c-b18c-11e5-8a2b-f2ee3c3273e5.png)

I also see errors on the console about loading the script. I am not an experienced webdev to understand these errors, any clues? Anything I should be doing?

**Comment by damianszczepanik** [comment]
Duplicate of jenkinsci/cucumber-reports-plugin/issues/7

**Comment by saadlu** [comment]
yes it is. thanks
