### ISSUE TITLE
java.lang.IllegalArgumentException: cucumber.json does not exist

### ISSUE THREAD

**Issue by sahajamit** [damianszczepanik/cucumber-reporting#284]
When I am running the code given on the readme page then it is not generating the report and giving the following error. I am attaching the screenshot along with json file.

This is the cucumber.json file
https://gist.github.com/sahajamit/e85986e2f365aed3a4a8

Here is the report generated.
<img width="1066" alt="screen shot 2016-01-06 at 7 24 43 pm" src="https://cloud.githubusercontent.com/assets/358319/12144058/40a9a06a-b4ab-11e5-9807-ab874bbe7711.png">

**Comment by damianszczepanik** [comment]
You've passed wrong path to the json report and the report could not be found.

**Comment by sahajamit** [comment]
Thanks I figured out the issue. I was in a assumption that it will search for cucumber.json in the reportOutputDirectory so I have not given the absolute path for the json file.

Thanks for your prompt reply :-)
