### ISSUE TITLE
Report not formatted correctly in Chrome and Firefox

### ISSUE THREAD

**Issue by rachidbouacheria** [damianszczepanik/cucumber-reporting#285]
The below error shows in the chrome browser in the developer tool's console. I also attached a picture.
![cucumber_report_bug](https://cloud.githubusercontent.com/assets/16614703/12207151/e2df5c68-b5f9-11e5-94b0-696dd978a62b.png)

:1 Blocked script execution in 'http://myurl/cucumber-html-reports/' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

**Comment by damianszczepanik** [comment]
Duplicate of jenkinsci/cucumber-reports-plugin#7
