### ISSUE TITLE
New feature: is it possible that add drillable link for failed scenarios?

### ISSUE THREAD

**Issue by idealivan** [damianszczepanik/cucumber-reporting#291]
Usually it is needed to pay special attentions to failed scenarios.

is it possible to add drillable link for failed scenarios: `a page for specific feature that had been chosen, and just display all failed scenarios`.

Thanks
Cent Lui

**Comment by damianszczepanik** [comment]
It is based on cucumber-jvm report so if you have such data in cucumber.json we can talk it over.

**Comment by damianszczepanik** [comment]
Duplicate of #344
