### ISSUE TITLE
Tags not processed on Feature level

### ISSUE THREAD

**Issue by mbfaay** [damianszczepanik/cucumber-reporting#297]
Tags are only processed on Scenario level, whereas Scenario's inherit the tags set at Feature level.
Can you please add the tag inheritance in the processing?

**Comment by damianszczepanik** [comment]
Attach json file and describe the problem

**Comment by mbfaay** [comment]
See the attached json file.
On Feature level there are 2 tags (@available-offers-country-language & @smoketest).
On a few Scenario's there is also a tag (@FSE-605).
There is only reporting about the tag on the Scenario level (@FSE-605), while the Feature level tags should be inherited by the Scenario's.
[results.json.txt](https://github.com/damianszczepanik/cucumber-reporting/files/87572/results.json.txt)

**Comment by damianszczepanik** [comment]
Good bug! This is regression causes by big refactoring which I did weeks ago.

Thank you for this report. Fix will be available in next release.

**Comment by mbfaay** [comment]
Do you have a planned release date?

**Comment by damianszczepanik** [comment]
Very soon. Probably days
