### ISSUE TITLE
I could not find gradle plugin for this report 

### ISSUE THREAD

**Issue by cdewangan** [damianszczepanik/cucumber-reporting#301]

**Comment by damianszczepanik** [comment]
What do you need it for?

**Comment by tommywo** [comment]
@cdewangan Currently there isn't one, but you can generate report in gradle like that:
https://github.com/camiloribeiro/cucumber-gradle-parallel/blob/master/build.gradle

**Comment by damianszczepanik** [comment]
Looks promising
