### ISSUE TITLE
Cucumber-JVM-TestNG support for this reporting

### ISSUE THREAD

**Issue by cdewangan** [damianszczepanik/cucumber-reporting#302]

**Comment by damianszczepanik** [comment]
What do you expect?

**Comment by cdewangan** [comment]
The report is not getting generated when I am using Gradle (with Cucumber-JVM-TestNG). I could not try using maven.

**Comment by damianszczepanik** [comment]
Generate grade build file from pom and then it should work.
Otherwise feel free to pull request with such change.  Mind that I don't want to maintain two files and update both once the pom.xml is changed.  This should be done smartly :)
