### ISSUE TITLE
Only English keywords are supported

### ISSUE THREAD

**Issue by hloland** [damianszczepanik/cucumber-reporting#306]
Scenario statistics is missing for the report. I don't know if this is a bug or it is intended (feature), It works in older versions, I don't have the version number.

According to the source code the report only support English language of the gherkin language.

The method in the Element class:

public boolean isScenario() {
for (String reference : SCENARIO_KEYWORDS) {
if (reference.equals(keyword)) {
return true;
}
}
return false;
}

This line is the problem: 
private static final String[] SCENARIO_KEYWORDS = { "Scenario", "Scenario Outline" };
It only contains English language. When I added the Norwegian version (Scenariomal) it worked fine.

One option is to rewrite the mothed to not use the scenario words or use the language file for the gherkin project. https://github.com/cucumber/cucumber/wiki/Spoken-languages

The report in question contains Norwegian language in the scenarios.

![screenshot](https://cloud.githubusercontent.com/assets/10044795/12394873/c5ae20a4-bdfe-11e5-9534-d17f90901ec4.png)

**Comment by damianszczepanik** [comment]
I thought that even you have defined scenarios in local languages, json file is still rewritten in English. If  this is not true than plugin might show crazy results.

I don't have plan to support all languages, especially if this information is not stored directly in json file

**Comment by damianszczepanik** [comment]
Attach json. Maybe there is easy way to make it work

**Comment by hloland** [comment]
I'm not allowed for legal reason to post the complete json file, but here is some part of it, this might help you.

when I added Scenariomal to the SCENARIO_KEYWORDS it worked fine.

[
  {
    "comments": [
      {
        "line": 1,
        "value": "#language: no"
      }
    ],
    "line": 2,
    "elements": [
      {
        "line": 10,
        "name": "#######################",
        "description": "",
        "id": "#######################;;2",
        "after": [
          {
            "result": {
              "duration": 554644,
              "status": "passed"
            },
            "match": {
              "location": "#######################.after(Scenario)"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenariomal"
        "steps": [
          {
            "result": {
              "duration": 3657784210,
              "status": "passed"
            },
            "line": 5,

**Comment by hloland** [comment]
This fix also worked: (file: Element.java)

public boolean isScenario() {
        /*for (String reference : SCENARIO_KEYWORDS) {
            if (reference.equals(keyword)) {
                return true;
            }
        }*/

        if(type.equals("scenario")){
            return true;
        }

        return false;
    }

**Comment by damianszczepanik** [comment]
I will take a look. Next time you can use library that eliminates from JSON 'legal' information https://github.com/damianszczepanik/silencio
