### ISSUE TITLE
String is no longer supported as a parameter for  private String buildNumber

### ISSUE THREAD

**Issue by Ploskodonka** [damianszczepanik/cucumber-reporting#309]
String is no longer supported as a parameter for 
private String buildNumber; (Configuration.class)
in one of the latest versions.

We get a java.lang.NumberFormatException due to these lines

result.put("build_number", configuration.getBuildNumber());
        int previousBuildNumber = -1;
        try {
            previousBuildNumber = Integer.parseInt(configuration.getBuildNumber());
            previousBuildNumber--;
        } catch (NumberFormatException e) {
            LOG.error("Could not parse build number: {}.", configuration.getBuildNumber(), e);
        }
in  protected Map<String, Object> getGeneralParameters() 

So it is possible to pass only Integer values into buildNumber.
Could you please fix it?

**Comment by damianszczepanik** [comment]
Well, validation should be done during compilation time so the buildNumber is integer, not String. 

Why do you want to have string as the build number? Jenkins uses number so in that way I can prepare link to previous build

**Comment by Ploskodonka** [comment]
We are actually using this parameter for different purposes, so it may contain string as branch name  or version like "1.0.0" as well.
Would it be possible to make parameter optional? Or if the solution will be complex enough, could you remove logging messages, because reports look weird with them

**Comment by tommywo** [comment]
Cucumber report can also be generated without use of jenkins - for example with maven mojo,
so how about parsing buildNumber to int only when runWithJenkins is true?

**Comment by Ploskodonka** [comment]
"parsing buildNumber to int only when runWithJenkins is true"
This will suit us as well
