### ISSUE TITLE
Tag View Graph:  Use Vertical rather than Horizontal

### ISSUE THREAD

**Issue by msymons** [damianszczepanik/cucumber-reporting#31]
Issue #26 covers problems with tag counts.  Whilst waiting for a fix, I essentially stopped using tags...  but have every intention of going back and adding a LOT of additional tags to my feature files as soon as the fix is in.

However, I  fear that doing this will make the Tag View graph look a bit squashed.  This is what my graph looks like as things stand:

![tag-chart](https://f.cloud.github.com/assets/4938718/873193/adfd6234-f872-11e2-85ae-a324dcfb38f2.JPG)

(Everything was green last week...  honest!)

The tags on the horizontal access are almost unreadable... it'll be worse when there are 80 or 120 instead of just 40.

So, would it be possible to switch the graph from a horizontal to a vertical orientation?

1) The bars would be longer (and easier to work with) as they would now be horizontal, using the width of the graph.

2) The tag names would now be on the Y axis and easier to read.  Furthermore, it would not matter if there were 3 or 30 or 300...  the graph should still be readable (although maybe harder to print for too many tags?). 

Note:  I have read the comment on issue #13...

> I have been working on removing all html from the code to allow
> for proper templating... 

> ...let people easily customise the reports with the information that is important to > them and add graphs and charts as they like

I just wanted to add an idea into the pot!

**Comment by damianszczepanik** [comment]
Whole front-end should (nice to have at least) be refactored but I don't have plan for this in near future. Also chart we are using does not support vertical mode.
