### ISSUE TITLE
Cannot find resource issues

### ISSUE THREAD

**Issue by trongbui** [damianszczepanik/cucumber-reporting#317]
Hi damianszczepanik,

I have used the version 1.2.0 in my proj and got an issue that resource file could not be found. ie: #parse("/templates/footer.vm"). I have downloaded the code (1.3.0-snapshot) and when I removed "**/**" before "template", it worked. 

and at stepOverview.vm, I have issue at #if($step.getPercentageResult() == 100**.0**) and I have to remove **".0"** to get the report generated.

Do you have experience on that? Seem that only me having the issue but I did not know how to fix it.

Kind regards,
-- Trong

**Comment by damianszczepanik** [comment]
Attach json, so I can take a look

**Comment by trongbui** [comment]
`[
  {
    "line": 1,
    "elements": [
      {
        "before": [
          {
            "result": {
              "duration": 4702347,
              "status": "passed"
            },
            "match": {
              "location": "Hooks.before()"
            }
          }
        ],
        "line": 11,
        "name": "Verify client list",
        "description": "",
        "id": "rest;verify-client-list;;2",
        "after": [
          {
            "result": {
              "duration": 90400,
              "status": "passed"
            },
            "match": {
              "location": "Hooks.after()"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "duration": 1430902300,
              "status": "passed"
            },
            "line": 5,
            "name": "The Rest is working",
            "match": {
              "location": "RestSteps.restIsWorking()"
            },
            "keyword": "Given "
          },
          {
            "result": {
              "duration": 604983888,
              "error_message": "org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error",
              "status": "failed"
            },
            "line": 6,
            "name": "I get the list of Clients in the System",
            "match": {
              "location": "RestSteps.getClientList()"
            },
            "keyword": "When "
          },
          {
            "result": {
              "status": "skipped"
            },
            "line": 7,
            "name": "The Clients list should contains: \u0027ABC-001\u0027",
            "match": {
              "arguments": [
                {
                  "val": "ABC-001",
                  "offset": 35
                }
              ],
              "location": "RestSteps.clientListShouldBe(String)"
            },
            "matchedColumns": [
              0
            ],
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "line": 1,
            "name": "@Clients"
          }
        ]
      }
    ],
    "name": "REST",
    "description": "",
    "id": "rest",
    "keyword": "Feature",
    "uri": "Clients.feature",
    "tags": [
      {
        "line": 1,
        "name": "@Clients"
      }
    ]
  }
]`

**Comment by trongbui** [comment]
Above is the cucumber.json

**Comment by damianszczepanik** [comment]
Are you running on Jenkins or directly as standalone application? Unix or Windows?

**Comment by trongbui** [comment]
I add it as a dependency and run it dirrectly in a project in Windows environment.

**Comment by damianszczepanik** [comment]
So the problem is probably that you run it in wrong directory context because I can run it directly from IDE as maven project and when running directly in Windows you need to make sure that all dependency are added properly

**Comment by trongbui** [comment]
But I just added cucumber-reporting as a dependency, and here is the code for generating it. Then I run it within the IDE, How can I run it wrong?

`    public static void generateHTMLReport() {
        File reportOutputDirectory = new File("target");
        List<String> jsonFiles = new ArrayList<>();
        jsonFiles.add("target/cucumber.json");

        String jenkinsBasePath = "";
        String buildNumber = "1";
        String projectName = "cucumber-jvm";
        boolean skippedFails = true;
        boolean pendingFails = false;
        boolean undefinedFails = true;
        boolean missingFails = true;
        boolean runWithJenkins = false;
        boolean parallelTesting = false;

        Configuration configuration = new Configuration(reportOutputDirectory, projectName);
// optionally only if you need
        configuration.setStatusFlags(skippedFails, pendingFails, undefinedFails, missingFails);
        configuration.setParallelTesting(parallelTesting);
        configuration.setJenkinsBasePath(jenkinsBasePath);
        configuration.setRunWithJenkins(runWithJenkins);
        configuration.setBuildNumber(buildNumber);

        ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
        reportBuilder.generateReports();
    }`

**Comment by tommywo** [comment]
What IDE do you use?

**Comment by trongbui** [comment]
hi,
I am using IntelliJ IDEA Community version
