### ISSUE TITLE
Diff Report to compare results from current and previous build

### ISSUE THREAD

**Issue by msymons** [damianszczepanik/cucumber-reporting#33]
A feature that I would love to see in cucumber-reporting is a diff report...  something that tells me what has changed between the current report and the last report (or variations thereof).

For instance, I have seen the total number of features reported upon *drop* from one day to the next because a change to one feature caused it not to run at all.  But the status report was all green before this happened and all green afterwards...  and so it was hard to spot that something had changed.  It would have helped to have been told that the total number of features had dropped.

Another use case:  the feature status lists lots of (say) skipped steps... but the number has declined because someone has been fixing stuff.  It would be useful to know that things are improving (or vice versa).

**Comment by PivotITAcademy** [comment]
Hi....
just curious to know if the logic of showing diff between current cucumber report and previous reports was implemented?
I am using cucumber report plugin in Jenkins and want to implement this
