### ISSUE TITLE
Report Table Sorting

### ISSUE THREAD

**Issue by msymons** [damianszczepanik/cucumber-reporting#34]
The Feature Statistics table is sorted by the feature file name but lists features by the feature text from inside the file.  The Tag Statistics table is sorted I know not how.

It would be helpful if the columns in the tables were sortable on the fly.  ie, sort by tag, sort by duration, sort by status, etc.

**Comment by damianszczepanik** [comment]
W don't sort or re-order features and the order is the same as in passed json file. That make sense because you can observe dependencies between tests (if there are any). If you need to execute tests in order you can arrange *.feature files.
