### ISSUE TITLE
Failed scenarios count is not showing properly, all scenarios showing in Passed column

### ISSUE THREAD

**Issue by pradeepreddy305** [damianszczepanik/cucumber-reporting#340]
Couple of scenarios got failed in one feature file,
![capture](https://cloud.githubusercontent.com/assets/17430362/13252407/7c069754-da5c-11e5-878b-0b3855407197.PNG)

but it is not showing in Failed column and it is showing as passed.

**Comment by damianszczepanik** [comment]
Attach json file

**Comment by pradeepreddy305** [comment]
Please find below Json:

[RegressionSuiteTest.txt](https://github.com/damianszczepanik/cucumber-reporting/files/144340/RegressionSuiteTest.txt)

![capture1](https://cloud.githubusercontent.com/assets/17430362/13282193/cc862bac-db0d-11e5-8973-d6a70011ec2d.PNG)

**Comment by damianszczepanik** [comment]
True, looks like the bug

**Comment by damianszczepanik** [comment]
Will be published with next release. 

Thank you!

**Comment by damianszczepanik** [comment]
On the other hand I need to think it over because the chart was fine: chart displayed scenarios while table features. In your case feature failed while scenario doesn't. Maybe I will add one more chart for scenario
