### ISSUE TITLE
Suggestion for report beautifying

### ISSUE THREAD

**Issue by rommy1204** [damianszczepanik/cucumber-reporting#341]
Hi Damian,

Could you please implement these improvements?
1. Apply (+) functionality not to the first logs row, but to the step - it would be better
2. Step output should be expanded by default only for failed scenarios to see the steps logs and reproduce them (it is not convenient to expand them all manually)

you agreed with these points in https://github.com/jenkinsci/cucumber-reports-plugin/issues/25

**Comment by damianszczepanik** [comment]
Sounds good, hopefully it will be added but probably not very soon

**Comment by damianszczepanik** [comment]
Fixed in #415
