### ISSUE TITLE
Links for failed scenarios

### ISSUE THREAD

**Issue by damianszczepanik** [damianszczepanik/cucumber-reporting#344]
_From @girbh on May 18, 2015 13:45_

I feel there is a need for listing all the failed scenarios within a feature, when we click on failed tests within features.

_Copied from original issue: damianszczepanik/cucumber-sandwich#5_

**Comment by damianszczepanik** [comment]
Passing scenarios are collapsed now, failing expanded - this should be helpful improvement for now

**Comment by msillence** [comment]
The collapsed view definitely helps however we have around 7000 tests in our output and a page just showing failures would be really handy and save a lot of searching.

**Comment by damianszczepanik** [comment]
Already implemented, will be delivered after some tests
