### ISSUE TITLE
NPE generating report

### ISSUE THREAD

**Issue by charles-haynes** [damianszczepanik/cucumber-reporting#35]
I'm trying to generate an HTML report from a JSON generated by cucumber-jvm. I'm using cucumber-core 1.1.2 because of this issue https://github.com/cucumber/cucumber-jvm/issues/565 I will try using 1.1.4-SNAPSHOT next

I get a page that has only a pink bar saying "null pointer exception." When I paste my JSON (2.8mb worth) into the error checker from the troubleshooting page I get the following:

Cucumber-Reporting Report diagnostic
Error Detected
["java.io.FileOutputStream.open(Native Method)", "java.io.FileOutputStream.(FileOutputStream.java:209)", "java.io.FileOutputStream.(FileOutputStream.java:160)", "java.io.FileWriter.(FileWriter.java:90)", "net.masterthought.cucumber.ReportBuilder.generateReport(ReportBuilder.java:250)", "net.masterthought.cucumber.ReportBuilder.generateErrorPage(ReportBuilder.java:224)", "net.masterthought.cucumber.ReportBuilder.(ReportBuilder.java:58)", "sun.reflect.GeneratedConstructorAccessor38.newInstance(Unknown Source)", "sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)", "java.lang.reflect.Constructor.newInstance(Constructor.java:532)", "org.jruby.javasupport.JavaConstructor.newInstanceDirect(JavaConstructor.java:243)", "org.jruby.java.invokers.ConstructorInvoker.call(ConstructorInvoker.java:68)", "org.jruby.java.invokers.ConstructorInvoker.call(ConstructorInvoker.java:143)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:286)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:81)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:85)", "org.jruby.java.proxies.ConcreteJavaProxy$2.call(ConcreteJavaProxy.java:44)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:85)", "org.jruby.RubyClass.newInstance(RubyClass.java:876)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:179)", "org.jruby.java.proxies.ConcreteJavaProxy$3.call(ConcreteJavaProxy.java:134)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)", "rubyjit.CucumberReporting$$initialize_203AA27F2E5F44FFAF037006A8B557BF973DEC87.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/src/cucumber_reporting.rb:13)", "rubyjit.CucumberReporting$$initialize_203AA27F2E5F44FFAF037006A8B557BF973DEC87.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/src/cucumber_reporting.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:101)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:85)", "org.jruby.RubyClass.newInstance(RubyClass.java:876)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:179)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)", "org.jruby.ast.CallManyArgsNode.interpret(CallManyArgsNode.java:59)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.ast.RescueNode.executeBody(RescueNode.java:224)", "org.jruby.ast.RescueNode.interpret(RescueNode.java:119)", "org.jruby.ast.BeginNode.interpret(BeginNode.java:83)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)", "org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:209)", "org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:197)", "org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:128)", "org.jruby.runtime.Block.call(Block.java:89)", "org.jruby.RubyProc.call(RubyProc.java:261)", "org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:64)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:201)", "org.jruby.RubyMethod.call(RubyMethod.java:118)", "org.jruby.RubyMethod$INVOKER$i$call.call(RubyMethod$INVOKER$i$call.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrNBlock.call(JavaMethod.java:261)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)", "org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:64)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)", "org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:209)", "org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:197)", "org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:128)", "org.jruby.runtime.Block.call(Block.java:89)", "org.jruby.RubyProc.call(RubyProc.java:261)", "org.jruby.RubyProc.call19(RubyProc.java:249)", "org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:217)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:213)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)", "org.jruby.runtime.callsite.CachingCallSite.callVarargs(CachingCallSite.java:104)", "rubyjit.Sinatra::Base$$route!_AD49F929CD09ECE08A2F7D8ECF4E4E740528F968.block_2$RUBY$__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:785)", "rubyjit$Sinatra::Base$$route!_AD49F929CD09ECE08A2F7D8ECF4E4E740528F968$block_2$RUBY$__file__.call(rubyjit$Sinatra::Base$$route!_AD49F929CD09ECE08A2F7D8ECF4E4E740528F968$block_2$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yieldSpecificInternal(CompiledBlock19.java:121)", "org.jruby.runtime.CompiledBlock19.yieldSpecific(CompiledBlock19.java:96)", "org.jruby.runtime.Block.yieldSpecific(Block.java:99)", "rubyjit.Sinatra::Base$$route_eval_8C613D4A743043A48623BF352882D27A2220E27B.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:801)", "rubyjit.Sinatra::Base$$route_eval_8C613D4A743043A48623BF352882D27A2220E27B.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:161)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)", "rubyjit.Sinatra::Base$$route!_AD49F929CD09ECE08A2F7D8ECF4E4E740528F968.block_1$RUBY$__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:785)", "rubyjit$Sinatra::Base$$route!_AD49F929CD09ECE08A2F7D8ECF4E4E740528F968$block_1$RUBY$__file__.call(rubyjit$Sinatra::Base$$route!_AD49F929CD09ECE08A2F7D8ECF4E4E740528F968$block_1$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yieldSpecificInternal(CompiledBlock19.java:121)", "org.jruby.runtime.CompiledBlock19.yieldSpecific(CompiledBlock19.java:106)", "org.jruby.runtime.Block.yieldSpecific(Block.java:117)", "rubyjit.Sinatra::Base$$process_route_A431099D4515854914AD2CBB3A8EBCA9EF435073.block_2$RUBY$__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:822)", "rubyjit$Sinatra::Base$$process_route_A431099D4515854914AD2CBB3A8EBCA9EF435073$block_2$RUBY$__file__.call(rubyjit$Sinatra::Base$$process_route_A431099D4515854914AD2CBB3A8EBCA9EF435073$block_2$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:139)", "org.jruby.runtime.Block.yield(Block.java:130)", "org.jruby.RubyContinuation.enter(RubyContinuation.java:107)", "org.jruby.RubyKernel.rbCatch19Common(RubyKernel.java:1181)", "org.jruby.RubyKernel.rbCatch19(RubyKernel.java:1174)", "org.jruby.RubyKernel$INVOKER$s$rbCatch19.call(RubyKernel$INVOKER$s$rbCatch19.gen)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:177)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:188)", "rubyjit.Sinatra::Base$$process_route_A431099D4515854914AD2CBB3A8EBCA9EF435073.chained_0_ensure_1$RUBY$__ensure__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:820)", "rubyjit.Sinatra::Base$$process_route_A431099D4515854914AD2CBB3A8EBCA9EF435073.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb)", "rubyjit.Sinatra::Base$$process_route_A431099D4515854914AD2CBB3A8EBCA9EF435073.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb)", "org.jruby.ast.executable.AbstractScript.__file__(AbstractScript.java:50)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:281)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:245)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:256)", "rubyjit.Sinatra::Base$$route!_AD49F929CD09ECE08A2F7D8ECF4E4E740528F968.block_0$RUBY$__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:784)", "rubyjit$Sinatra::Base$$route!_AD49F929CD09ECE08A2F7D8ECF4E4E740528F968$block_0$RUBY$__file__.call(rubyjit$Sinatra::Base$$route!_AD49F929CD09ECE08A2F7D8ECF4E4E740528F968$block_0$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:139)", "org.jruby.runtime.Block.yield(Block.java:130)", "org.jruby.RubyArray.eachCommon(RubyArray.java:1606)", "org.jruby.RubyArray.each(RubyArray.java:1613)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)", "rubyjit.Sinatra::Base$$route!_AD49F929CD09ECE08A2F7D8ECF4E4E740528F968.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:783)", "rubyjit.Sinatra::Base$$route!_AD49F929CD09ECE08A2F7D8ECF4E4E740528F968.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb)", "org.jruby.ast.executable.AbstractScript.__file__(AbstractScript.java:38)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:141)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)", "rubyjit.Sinatra::Base$$dispatch!_32CEF8F441C55720F2AC7409196CBFC4F97B89CF.chained_1_rescue_1$RUBY$SYNTHETIC__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:886)", "rubyjit.Sinatra::Base$$dispatch!_32CEF8F441C55720F2AC7409196CBFC4F97B89CF.chained_0_ensure_1$RUBY$__ensure__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb)", "rubyjit.Sinatra::Base$$dispatch!_32CEF8F441C55720F2AC7409196CBFC4F97B89CF.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb)", "rubyjit.Sinatra::Base$$dispatch!_32CEF8F441C55720F2AC7409196CBFC4F97B89CF.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:141)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)", "rubyjit.Sinatra::Base$$call!_F1A0960F02EBF281DFB1AE3733E87720D5C76009.block_0$RUBY$__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:719)", "rubyjit$Sinatra::Base$$call!_F1A0960F02EBF281DFB1AE3733E87720D5C76009$block_0$RUBY$__file__.call(rubyjit$Sinatra::Base$$call!_F1A0960F02EBF281DFB1AE3733E87720D5C76009$block_0$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yieldSpecificInternal(CompiledBlock19.java:121)", "org.jruby.runtime.CompiledBlock19.yieldSpecific(CompiledBlock19.java:96)", "org.jruby.runtime.Block.yieldSpecific(Block.java:99)", "rubyjit.Sinatra::Base$$invoke_1EEEE497B12EDF486DEE8D12842B4E8AED2BB2FB.block_0$RUBY$__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:871)", "rubyjit$Sinatra::Base$$invoke_1EEEE497B12EDF486DEE8D12842B4E8AED2BB2FB$block_0$RUBY$__file__.call(rubyjit$Sinatra::Base$$invoke_1EEEE497B12EDF486DEE8D12842B4E8AED2BB2FB$block_0$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:139)", "org.jruby.runtime.Block.yield(Block.java:130)", "org.jruby.RubyContinuation.enter(RubyContinuation.java:107)", "org.jruby.RubyKernel.rbCatch19Common(RubyKernel.java:1181)", "org.jruby.RubyKernel.rbCatch19(RubyKernel.java:1174)", "org.jruby.RubyKernel$INVOKER$s$rbCatch19.call(RubyKernel$INVOKER$s$rbCatch19.gen)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:177)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:188)", "rubyjit.Sinatra::Base$$invoke_1EEEE497B12EDF486DEE8D12842B4E8AED2BB2FB.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:871)", "rubyjit.Sinatra::Base$$invoke_1EEEE497B12EDF486DEE8D12842B4E8AED2BB2FB.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:161)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)", "rubyjit.Sinatra::Base$$call!_F1A0960F02EBF281DFB1AE3733E87720D5C76009.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:719)", "rubyjit.Sinatra::Base$$call!_F1A0960F02EBF281DFB1AE3733E87720D5C76009.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "rubyjit.Sinatra::Base$$call_E7297D83DF1A6A3B6C6430CFC06E1C6955B2C3A9.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:705)", "rubyjit.Sinatra::Base$$call_E7297D83DF1A6A3B6C6430CFC06E1C6955B2C3A9.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)", "rubyjit.Rack::Protection::XSSHeader$$call_583981A7C5553C000641D80C19F025CB1E10CA57.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22)", "rubyjit.Rack::Protection::XSSHeader$$call_583981A7C5553C000641D80C19F025CB1E10CA57.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "rubyjit.Rack::Protection::PathTraversal$$call_1FA61E7C557B7316A900834B49199A8901CF507F.chained_0_ensure_1$RUBY$__ensure__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16)", "rubyjit.Rack::Protection::PathTraversal$$call_1FA61E7C557B7316A900834B49199A8901CF507F.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb)", "rubyjit.Rack::Protection::PathTraversal$$call_1FA61E7C557B7316A900834B49199A8901CF507F.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "rubyjit.Rack::Protection::JsonCsrf$$call_BB197BD41FEE12D244A68A6C28D2451E579BEDA2.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17)", "rubyjit.Rack::Protection::JsonCsrf$$call_BB197BD41FEE12D244A68A6C28D2451E579BEDA2.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "rubyjit.Rack::Protection::Base$$call_EF23885744C5A97C466705F2C222FE925519934C.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47)", "rubyjit.Rack::Protection::Base$$call_EF23885744C5A97C466705F2C222FE925519934C.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/rack-protection-1.2.0/lib/rack/protection/base.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)", "rubyjit.Rack::Protection::XSSHeader$$call_583981A7C5553C000641D80C19F025CB1E10CA57.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22)", "rubyjit.Rack::Protection::XSSHeader$$call_583981A7C5553C000641D80C19F025CB1E10CA57.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "rubyjit.Rack::Logger$$call_9B7411951859B64FADEEBE6D5C62AAF6DF4FA6CF.__file__(/home/rails/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/logger.rb:15)", "rubyjit.Rack::Logger$$call_9B7411951859B64FADEEBE6D5C62AAF6DF4FA6CF.__file__(/home/rails/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/logger.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "rubyjit.Rack::CommonLogger$$call_E0AEE62396EBD015D745DB8B89024865754E45E5.__file__(/home/rails/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/commonlogger.rb:20)", "rubyjit.Rack::CommonLogger$$call_E0AEE62396EBD015D745DB8B89024865754E45E5.__file__(/home/rails/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/commonlogger.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "rubyjit.Rack::Head$$call_B3E31D34D8A282DD56671BF2AB8DCC94A0581272.__file__(/home/rails/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/head.rb:9)", "rubyjit.Rack::Head$$call_B3E31D34D8A282DD56671BF2AB8DCC94A0581272.__file__(/home/rails/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/head.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "rubyjit.Rack::MethodOverride$$call_5C4513A64D983C8019F0C2940E049E8355465D21.__file__(/home/rails/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/methodoverride.rb:21)", "rubyjit.Rack::MethodOverride$$call_5C4513A64D983C8019F0C2940E049E8355465D21.__file__(/home/rails/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/methodoverride.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "rubyjit.Sinatra::Base$$call_94E8BA21132402701DA13E650D75E342B14A9AE7.block_0$RUBY$__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334)", "rubyjit$Sinatra::Base$$call_94E8BA21132402701DA13E650D75E342B14A9AE7$block_0$RUBY$__file__.call(rubyjit$Sinatra::Base$$call_94E8BA21132402701DA13E650D75E342B14A9AE7$block_0$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yieldSpecificInternal(CompiledBlock19.java:121)", "org.jruby.runtime.CompiledBlock19.yieldSpecific(CompiledBlock19.java:96)", "org.jruby.runtime.Block.yieldSpecific(Block.java:99)", "rubyjit.Sinatra::Base$$synchronize_628CFC31708E3E9E2E780EF29F851B0BBD3689DF.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:1416)", "rubyjit.Sinatra::Base$$synchronize_628CFC31708E3E9E2E780EF29F851B0BBD3689DF.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:161)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)", "rubyjit.Sinatra::Base$$call_94E8BA21132402701DA13E650D75E342B14A9AE7.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334)", "rubyjit.Sinatra::Base$$call_94E8BA21132402701DA13E650D75E342B14A9AE7.__file__(/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/gems/gems/sinatra-1.3.2/lib/sinatra/base.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "rubyjit.Rack::Handler::Servlet$$call_70B35DDDBC7240FEE6A00DF14B77D46976C112A8.__file__(file:/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.1-lib-jruby-rack-1.1.13.1.jar!/rack/handler/servlet.rb:22)", "rubyjit.Rack::Handler::Servlet$$call_70B35DDDBC7240FEE6A00DF14B77D46976C112A8.__file__(file:/home/rails/apache-tomcat-7.0.30/webapps/cucumber-reporting-web/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.1-lib-jruby-rack-1.1.13.1.jar!/rack/handler/servlet.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)", "org.jruby.RubyClass.finvoke(RubyClass.java:741)", "org.jruby.javasupport.util.RuntimeHelpers.invoke(RuntimeHelpers.java:496)", "org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:358)", "org.jruby.javasupport.JavaEmbedUtils$1.callMethod(JavaEmbedUtils.java:143)", "org.jruby.rack.DefaultRackApplication.call(DefaultRackApplication.java:64)", "org.jruby.rack.AbstractRackDispatcher.process(AbstractRackDispatcher.java:33)", "org.jruby.rack.AbstractFilter.doFilter(AbstractFilter.java:66)", "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)", "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)", "org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)", "org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)", "org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)", "org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)", "org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)", "org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929)", "org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)", "org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)", "org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)", "org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)", "org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)", "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)", "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)", "java.lang.Thread.run(Thread.java:679)"]

**Comment by damianszczepanik** [comment]
This issue has been found long time ago and new version has been refactored a lot.
