### ISSUE TITLE
Feature request: Show scenario descriptions

### ISSUE THREAD

**Issue by rarbuthnot** [damianszczepanik/cucumber-reporting#364]
Just like the report currently shows feature descriptions, it would be nice if the reports would show any descriptions that exist for scenarios.

In the JSON file, it appears that these descriptions exist under "elements: description".

Even if this were a flag that could be configured, that would be better than not being able to show them at all, imo.

Thanks!

**Comment by damianszczepanik** [comment]
Attach json and screenshots describing what is your expectations

**Comment by rarbuthnot** [comment]
![scenariodescription](https://cloud.githubusercontent.com/assets/1295575/13715739/bf979b44-e7a4-11e5-8d9c-de7eea793637.png)

JSON starts like this:

`
[
  {
    "line": 1,
    "elements": [
      {
        "line": 4,
        "name": "If a bid is entered by a user on the supplier\u0027s behalf, then the supplier should be notified",
        "description": "  CREATED: 3/10/15; SOURCE: Procure Pilot\n  BIZ REVIEW: APPROVED 7/15/15 by Sara and Mike.\n  NOTE: A notification does not have to be an email or an active notification, it could be a passive like a status update in the Supplier Portal.",
        "id": "bid-line,-request-for-bid,-and-bid-response;if-a-bid-is-entered-by-a-user-on-the-supplier\u0027s-behalf,-then-the-supplier-should-be-notified",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "status": "undefined"
            }, ...
`

You can see the Scenario description for the scenario shown in the screenshot. 

Thanks for your consideration, and please let me know if there is any more info I can provide.
