### ISSUE TITLE
[question] How to add the device value

### ISSUE THREAD

**Issue by saikrishna321** [damianszczepanik/cucumber-reporting#371]
@kingsleyh  in the cucumber html report i see a field Device 

How do i set values into this field ?

<img width="1438" alt="screen shot 2016-03-14 at 9 49 55 pm" src="https://cloud.githubusercontent.com/assets/4045041/13751199/080a826a-ea2f-11e5-9450-c61f18b2bc60.png">

**Comment by damianszczepanik** [comment]
This is useful when you run the same tests on different devices, machines

**Comment by saikrishna321** [comment]
@damianszczepanik yup .. thats exactly what i'm doing . i'm running ma tests on different device. How do i set the value into that field ?

**Comment by tommywo** [comment]
@saikrishna321 the value is taken from json filename, but sanitation in not correct, 
please try to use only letters and numbers in your filename

**Comment by saikrishna321** [comment]
@tommywo kool  thanks.. will give it a try ..
