### ISSUE TITLE
Is it possible to reference screenshots rather than embed them?

### ISSUE THREAD

**Issue by TeresaP** [damianszczepanik/cucumber-reporting#380]
Our Jenkins reports are often times hundreds of MB, and the cuprit seems to be embedded screenshots. Is it possible to simply reference them instead?

**Comment by damianszczepanik** [comment]
It is but so far I don't have a plan for such change. I can give you advise if you want to send PR obout it

**Comment by TeresaP** [comment]
That would be great

**Comment by Seploid** [comment]
We faced with same problems, in our case some jenkins plugins doesn't work with a big json-files. So we managed to not hold pictures in JSON. 
For that we save pictures as files and add links to pictures as text in scenario outline.

```
String newFileNamePath = "<a href onclick=\"var im=document.getElementById('" + id + "'); " +
					"im.style.display = (im.style.display == 'none' ? 'block' : 'none');return false\">" +
					screenshotName + "</a>" +

					"  <img id=" + id + " style=\"display: none;\" src=\".." + fileSeparator + ".." + fileSeparator + level + "target" +
					fileSeparator + "cucumber-html-reports" + fileSeparator + SCREENSHOTS + fileSeparator +
					screenshotName + "\"/>";
scenario.write(newFileNamePath);
```

That looks fine, visually it doesn't different from default method.

**Comment by midopa** [comment]
+1

**Comment by midopa** [comment]
What if the plugin recognized "text/url" MIME types as image URLs?
* Data is just the URL characters
* Supports both links to external images (eg. tests upload images to S3, embed a URL) or internal/local (eg. tests save images locally and provide relative file path).
* Plugin extracts the string and places into an image tag.
* If saving images locally, tests must ensure the URL is accessible from wherever the report is written. Which leads to...

Open question:
* Images saved locally need to be copied properly to the build artifacts/report directory in Jenkins. Probably something the Jenkins plugin needs to ensure.

**Comment by damianszczepanik** [comment]
This mime type would be quite easy to add so you can update https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/resources/templates/macros/report/embeddings.vm - that won't be a difficult so we're welcome to send PR.

**Comment by damianszczepanik** [comment]
Merged support for images. I believe some improvements will be prepared and maybe support for other file types but lets start from images.
