### ISSUE TITLE
Update colours for report

### ISSUE THREAD

**Issue by rommy1204** [damianszczepanik/cucumber-reporting#383]
Hi Damian,

Is it possible to make colours in the report not so bright?
Our eyes are getting tired so much while working with current colours
Now it is:
![now](https://cloud.githubusercontent.com/assets/10895964/14100121/19e8c190-f59c-11e5-84ff-3acc8e5186fc.png)
With previous colours (as it was in earlier version):
![was](https://cloud.githubusercontent.com/assets/10895964/14100137/305140b0-f59c-11e5-8bc0-2b4444d42a61.png)
It could be another colours, just not so saturated :)
for the second screenshot I used:

.passed {
    background-color: #C5D88A;
}

.failed {
    background-color: #D88A8A;
}

**Comment by tommywo** [comment]
+1

**Comment by Seploid** [comment]
+1

**Comment by damianszczepanik** [comment]
I wanted to have the same colors for reports and charts. I can update them if you provide examples which are not so poor and unhappy as previous :)

**Comment by rommy1204** [comment]
Damian, how about these colous? Something between previous and current
![prososal1](https://cloud.githubusercontent.com/assets/10895964/14106929/b60b2422-f5c5-11e5-8ed6-bdae9d9b5193.png)

**Comment by Ploskodonka** [comment]
Thats how it looks now with chart
![2016-03-29_1601](https://cloud.githubusercontent.com/assets/10787015/14107227/dcae3234-f5c7-11e5-9127-7ce441b71209.png)
I used the following colors:

```
.passed {
    background-color: #92DD96;
}

.failed {
    background-color: #F2928C;
}

.skipped {
    background-color: #8AF;
}

.pending {
    background-color: #F5F28F;
}

.undefined {
    background-color: #F5B975;
}

.missing {
    background-color: #FAB3E9;
}
```

**Comment by rommy1204** [comment]
Damian, as I noticed, we can also change colours for highcharts here
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/resources/templates/pages/featuresOverview.vm
And we can make them the same as for the report
@Ploskodonka , I like your colours :)

**Comment by damianszczepanik** [comment]
Prepare PR with updated colors for report but keep chars unchanged. Does it make sense?

**Comment by nbarrett** [comment]
Hi @damianszczepanik - I'm a little unsure about what's happening now with this colour change? I agree with @rommy1204 about making them more gentle on the eyes and I also agree with allowing errors to be displayable without needing to scroll them as version 2.1.0 seems to be causing unrest in the community!

**Comment by damianszczepanik** [comment]
This plugin works as Agile - if you think something is wrong/ugly/etc you can send PR and improve it. Thus the UX may change from time to time if someone decides that the current approach is not perfect and can prove, that better solution can be implemented :)

**Comment by nbarrett** [comment]
Cool - I understand agile - was just trying to understand whether any work was underway (from anyone) to implement requests in the various threads.. Looks like you are waiting for PR following comment on 29th Mar yes?

**Comment by damianszczepanik** [comment]
I don't wait since this issue is closed but any other contributions are welcome :)
