### ISSUE TITLE
Getting Error On Report Generation.

### ISSUE THREAD

**Issue by arjunray12** [damianszczepanik/cucumber-reporting#390]
I am using a Cucumber reporting api for better reporting. My project is not a maven project and cannot change the project structure now. So I add all the dependency on my project but still now it is getting error like "java.lang.IllegalArgumentException: File 'target/cucumber.json' does not contan features!"

All added jars and version showing below.

![img1](https://cloud.githubusercontent.com/assets/5012549/14258286/752b1c92-fabf-11e5-8d2e-f14b1dc2d529.JPG)

I also added my runner class here which may help for debugging.

          import java.io.File;
          import java.util.ArrayList;
          import java.util.List;
          import org.junit.AfterClass;
          import org.junit.runner.RunWith;
          import cucumber.api.CucumberOptions;
          import cucumber.api.SnippetType;
          import cucumber.api.junit.Cucumber;
          import net.masterthought.cucumber.Configuration;
          import net.masterthought.cucumber.ReportBuilder;
         @RunWith(Cucumber.class)

         @CucumberOptions(
          plugin = { 
                "html:target/cucumber-html-report",
                "json:target/cucumber.json"
          },features ={"./sample.feature"},
            glue ={"com/automation/steps"},strict = true,
            dryRun= false,monochrome = true, snippets= SnippetType.CAMELCASE)

       public class Runner {
           @AfterClass
             public static void generateReport(){
             File reportOutputDirectory = new File("target");
             List<String> jsonFiles = new ArrayList<>();
             jsonFiles.add("target/cucumber.json");

        String jenkinsBasePath = "";
        String buildNumber = "1";
        String projectName = "cucumber-jvm";
        boolean skippedFails = true;
        boolean pendingFails = false;
        boolean undefinedFails = true;
        boolean missingFails = true;
        boolean runWithJenkins = false;
        boolean parallelTesting = false;

        Configuration configuration = new Configuration(reportOutputDirectory, projectName);
        // optionally only if you need
        configuration.setStatusFlags(skippedFails, pendingFails, undefinedFails, missingFails);
        configuration.setParallelTesting(parallelTesting);
        configuration.setJenkinsBasePath(jenkinsBasePath);
        configuration.setRunWithJenkins(runWithJenkins);
        configuration.setBuildNumber(buildNumber);

        ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
        reportBuilder.generateReports();
    }
}

I also attached the project structure.

![proj_structure](https://cloud.githubusercontent.com/assets/5012549/14256441/bf9c37ce-fab6-11e5-88a2-e4c9624852e9.JPG)

I observed that feature-overview.html was generated under the folder structure but it was corrupted.
![error_html](https://cloud.githubusercontent.com/assets/5012549/14258347/c5197104-fabf-11e5-996d-ee8b35786bef.JPG)

when I open this file I observed this error message on this file.

**Comment by damianszczepanik** [comment]
The configuration is fine, json file is found but it is not valid, does not contain features

**Comment by arjunray12** [comment]
I added my feature file looks like below:

Feature: This is a sample feature file

	Scenario: This is a scenario to test DataTable on Cucumber JVM.
		Given scenario data
		When executed from Runner Class
		Then UserName and Password Like below.
		| userName | password |
		| TestUser1 | TestPassword1 |
		| TestUser2 | TestPassword2 |

And another thing I want to mention that cucumber default result generate properly there is no problem.I also share the JSON file with you can you please tell me why this beautiful report not generating why this error occur. 
[
  {
    "id": "background-testing",
    "description": "",
    "name": "BackGround Testing",
    "keyword": "Feature",
    "line": 1,
    "elements": [
      {
        "description": "",
        "name": "",
        "keyword": "Background",
        "line": 3,
        "steps": [
          {
            "result": {
              "status": "undefined"
            },
            "name": "Open Browser with Google Link on any browser",
            "keyword": "Given ",
            "line": 4,
            "match": {}
          }
        ],
        "type": "background"
      },
      {
        "id": "background-testing;",
        "description": "",
        "name": "",
        "keyword": "Scenario",
        "line": 6,
        "steps": [
          {
            "result": {
              "status": "undefined"
            },
            "name": "Page with input field and User type on input field",
            "keyword": "Given ",
            "line": 7,
            "match": {}
          },
          {
            "result": {
              "status": "undefined"
            },
            "name": "Browser loaded properly.",
            "keyword": "When ",
            "line": 8,
            "match": {}
          },
          {
            "result": {
              "status": "undefined"
            },
            "name": "Search result should be populated automatically",
            "keyword": "Then ",
            "line": 9,
            "match": {}
          }
        ],
        "type": "scenario"
      },
      {
        "description": "",
        "name": "",
        "keyword": "Background",
        "line": 3,
        "steps": [
          {
            "result": {
              "status": "undefined"
            },
            "name": "Open Browser with Google Link on any browser",
            "keyword": "Given ",
            "line": 4,
            "match": {}
          }
        ],
        "type": "background"
      },
      {
        "id": "background-testing;",
        "description": "",
        "name": "",
        "keyword": "Scenario",
        "line": 11,
        "steps": [
          {
            "result": {
              "status": "undefined"
            },
            "name": "Page with search field and User click on search button",
            "keyword": "Given ",
            "line": 12,
            "match": {}
          },
          {
            "result": {
              "status": "undefined"
            },
            "name": "Browser loaded properly with search button.",
            "keyword": "When ",
            "line": 13,
            "match": {}
          },
          {
            "result": {
              "status": "undefined"
            },
            "name": "Search result should be populated after click on search button",
            "keyword": "Then ",
            "line": 14,
            "match": {}
          }
        ],
        "type": "scenario"
      }
    ],
    "uri": "./back_Test.feature"
  }
]

**Comment by GutoMartins019** [comment]
@arjunray12 how do you solve this problem? my json dont have the feature too.

**Comment by arjunray12** [comment]
@GutoMartins019 I already solved my problem and I wrote about this on [http://startingwithseleniumwebdriver.blogspot.in/2016/04/better-reporting-for-cucumber-jvm.html](my blog) go through it if you have any problem post comment on this I will try to give my best to help you.

**Comment by GutoMartins019** [comment]
Nice, thank you, i will read your post. 

I solved changing the report code to my suite test, my problem was that json was not filled with text when report was generated.

**Comment by arjunray12** [comment]
could you please share how you resolve your problem. It will be very helpful for others if you share your solution.

**Comment by Purus** [comment]
@damianszczepanik I am facing the same issue. 

Do we need to create any custom runner as mentioned by @arjunray12 ? I could not find any reference to such custom runners here in the repo.

**Comment by arjunray12** [comment]
Custom runner creation needed when you use this report without maven.Complete code given below link 
http://startingwithseleniumwebdriver.blogspot.in/2016/04/better-reporting-for-cucumber-jvm.html

and if we use this report using maven then we don't need anything complete code given here 
http://startingwithseleniumwebdriver.blogspot.in/2016/05/custom-cucumber-reporting-using-maven.html

**Comment by damianszczepanik** [comment]
Check with last release, should work fine

**Comment by Purus** [comment]
@damianszczepanik : I am using v2.30 and it does not work out-of-box

@arjunray12 : Based on ur blog, I am able to generate the report via maven. But I am looking to generate the report without maven. The repo does not specify about using custom runners. So let's wait for Damian response.

BTW, thanks for your blog links. It was useful.

**Comment by damianszczepanik** [comment]
Attach json file

**Comment by Purus** [comment]
@damianszczepanik A gist having the edited json is provided for your reference.

https://gist.github.com/Purus/e9d10c0f5834e5d5f884094ce42f7115

PS: File is edited to remove business related information.

**Comment by damianszczepanik** [comment]
I could generate report from given JSON. I suggest to anonimize json using https://github.com/damianszczepanik/silencio generate report using new json and if it fails share it again.

As long as I'm not able to reproduce the problem I won't be able to help.

**Comment by rupamraj20** [comment]
I want to add a custom error message to the report. Is there any way to do this. ReportBuilder class doesnot have such an option. Please let me know if anyone knows how to do this. Thanks in advance.
