### ISSUE TITLE
[question] How to log device name

### ISSUE THREAD

**Issue by saikrishna321** [damianszczepanik/cucumber-reporting#393]
@damianszczepanik i'm running ma tests on android/ios devices using appium, with cucumber-jvm

i'm using cucumber-reporting dependencies for reporting. How do i log the deviceName in the report ?

**Comment by damianszczepanik** [comment]
damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/json/Feature.java#L166 should help

**Comment by saikrishna321** [comment]
@damianszczepanik looking at this code i see we need to have the featureFile name as Nexus5_HomePage.feature and the report would fetch the device.

But in ma case i have the feature files running in parallel. So  a feature file named Nexus5 would necessary not run on the same device when running in parallel 

Is there anyway you would think off ?

**Comment by damianszczepanik** [comment]
Honestly I don't use this feature so you can send PR with updated proposal so we can discuss it

**Comment by saikrishna321** [comment]
👍   i will look into this ..

**Comment by damianszczepanik** [comment]
Try to pass true in https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/Configuration.java#L55 so new column will appear in the report

**Comment by saikrishna321** [comment]
@damianszczepanik btw how will tis pick the deviceName?

**Comment by damianszczepanik** [comment]
It refers to json file name
