### ISSUE TITLE
[question] unable to view tag summary in report

### ISSUE THREAD

**Issue by daniellesong** [damianszczepanik/cucumber-reporting#399]
Hi! I'm using cucumber-reporting with jenkins, and when viewing the HTML report, I'm able to see the graphs for scenarios and steps passing, as well as the drillable feature statistics, but I do not see the tag breakdown anywhere. Is there anything in particular I should be doing to enable them? This is a sample of one of my test json files, so I can see there are tags that could be read from there: 
```
{
    "keyword": "Feature",  
    "name": "Example Feature",  
    "line": 2,
    "description": "",
    "tags": [
      {
        "name": "@tag1",
        "line": 1
      },
      {
        "name": "@tag2",
        "line": 1
      }
    ],
    "id": "test",
    "uri": "features/test.feature",
```
Please let me know if any other information would be helpful. Thanks!

**Comment by damianszczepanik** [comment]
Attach json file you have been using for the report

**Comment by daniellesong** [comment]
Here you go!
[language.txt](https://github.com/damianszczepanik/cucumber-reporting/files/224909/language.txt)

**Comment by damianszczepanik** [comment]
As examined at http://jsonformatter.curiousconcept.com/ - this is not valid json file
