### ISSUE TITLE
Multiple Json files are not getting merged into single file

### ISSUE THREAD

**Issue by Washington3** [damianszczepanik/cucumber-reporting#411]
Hi, 
We have a group of test cases,we execute them once.. And then failed test cases also execute another time and then again execute second time failed test cases. For these 3 runs, we have 3 json files..if we put them in one folder, we are NOT getting consolidated report,instead we get only 3 separate reports..

Is it possible to merge the 3 json files  and create the consolidated report ?

Note: Tools being used:Cucumber /Calabash

**Comment by saikrishna321** [comment]
I do merging of multiple json and I get a single html report .. Can you pls post your code of generating cucumber 
HTML report ?

**Comment by damianszczepanik** [comment]
Yes it looks like your json file is not valid
