### ISSUE TITLE
Add support for mimetype 'application/json'

### ISSUE THREAD

**Issue by gd46** [damianszczepanik/cucumber-reporting#412]
I tried adding a scenario.attach(jsonObj, 'application/json') and got the following error. It would be great if this support was added. I have tests that I have user specific info attach to a json object that I keep track of during the test that I would like to add to the scenario attach so I have more info when debugging. 

Attachment number 0, has unsupported mimetype 'application/json'.

**Comment by damianszczepanik** [comment]
How this format should be displayed? Plain text would be easy to add but what if JS ON is stored as single line?

**Comment by gd46** [comment]
Sorry I figured out I could do what I was looking for by using plain text and then formatting the JSON response how I wanted.
