### ISSUE TITLE
Escape xml tags in output

### ISSUE THREAD

**Issue by msillence** [damianszczepanik/cucumber-reporting#435]
Out tests use xml for input and output, this is displayed in the web pages when they fail but as the tags are not escaped the browser just ignores all the tags and the output is blank.

**Comment by damianszczepanik** [comment]
Please attach json file

**Comment by msillence** [comment]
json attachments not allowed, so zipped it:

[cucumber162.zip](https://github.com/damianszczepanik/cucumber-reporting/files/246715/cucumber162.zip)

**Comment by damianszczepanik** [comment]
Tags are processed correctly and are the same as in JSON file so I don't understand the prbolem

**Comment by msillence** [comment]
I would like to see the xml in the output but browsers ignore tags they don't know about so the <ns3:error> xml does not appear
Really we should escape any html entities that we put in the pre tag so it should be
&lt;ns3:error&gt;
This example is a bit trivial but for more complicated xml we need to know what the xml not just the textual elements within. If I'd put the error in an attribute I guess this would be more obvious as the error text would also be missing.

![screenshot](https://cloud.githubusercontent.com/assets/1208867/14985433/5cf7c2a6-113f-11e6-906d-0d7ef6a613ca.png)

**Comment by damianszczepanik** [comment]
We agreed time ago that cucumber does not escape html/xml tag because some users want to display HTML code as it is so report should not change it.

If you want escape tags you need to pass through the library that does it and then store in report/json.
