### ISSUE TITLE
java.lang.UnsupportedClassVersionError: net/masterthought/cucumber/Configuration

### ISSUE THREAD

**Issue by Mozzartbet** [damianszczepanik/cucumber-reporting#438]
I wrote some simple login/logout test, then install cucumber-reporting plugin on jenkins. So than I  have problem with generate report with 2.2.0 version, i have same problem with less version of plugin too. This is log report :

[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] Copying all json files from slave: c:/git/Selenium/TestOfLogin-GUIsupport/target/cucumber to master reports directory: /var/lib/jenkins/jobs/TestOfLogin_GUIsupport/builds/2016-05-04_11-47-44/cucumber-html-reports
[CucumberReportPublisher] Found 1 json files.
[CucumberReportPublisher] 1. Found a json file: cucumber.json
[CucumberReportPublisher] Generating HTML reports
ERROR: Publisher net.masterthought.jenkins.CucumberReportPublisher aborted due to exception
java.lang.UnsupportedClassVersionError: net/masterthought/cucumber/Configuration
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:125)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:74)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
	at hudson.model.Run.execute(Run.java:1784)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)

and there is setup of my pom.xml :

	<groupId>com.mozzartbet.qa</groupId>
	<artifactId>TestOfLogin</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>TestOfLogin</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.12.1</version>
				<executions>
					<execution>
						<id>default-test</id>
						<phase>test</phase>
						<goals>
							<goal>test</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		
				<plugin>
					<groupId>com.versioneye</groupId>
					<artifactId>versioneye-maven-plugin</artifactId>
					<version>3.9.2</version>
				</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.43.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.4</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.4</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-picocontainer</artifactId>
			<version>1.2.4</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.5</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>2.2.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>18.0</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>

Sorry  about  bunch of text, im beginner. :) I hope so that you have some advice for me. TY.

**Comment by damianszczepanik** [comment]
Try with this https://github.com/damianszczepanik/maven-cucumber-reporting
