### ISSUE TITLE
Embedded images are displayed for hooks #Before and @After

### ISSUE THREAD

**Issue by ryderstorm** [damianszczepanik/cucumber-reporting#439]
Before version 2.2.0:
![image](https://cloud.githubusercontent.com/assets/3799823/15016129/a90a26b8-11dd-11e6-8227-4cd463912964.png)
---
After verison 2.2.0:
![image](https://cloud.githubusercontent.com/assets/3799823/15016163/cd1bd68c-11dd-11e6-8c7e-60b8e6761b1b.png)
---
The new styling looks great, and I really appreciate the use of monospaced fonts for error messages and test output. But the lack of images is crippling my troubleshooting capabilities. I didn't make any changes to the logic that embeds the images and they're still showing up in the html reports that my codebase generates whenever tests are run locally, so I think it must be something that changed in the 2.2.0 release.

**Comment by damianszczepanik** [comment]
Error message is wrapped to <pre> and previously you probably used HTML code which was displayed as-it-is
Well I think that you should use embedded for html code and plain text for error message. I don't think it is good idea to put html code as the output/log and assume it will be displayed as html code.

**Comment by ryderstorm** [comment]
I apologize if I'm misunderstanding you or if I am being unclear. I have no issue with the new styling for the error messages, they're even better in 2.2.0 and I'm grateful for the changes.

The issue I'm having is that the images embedded in the JSON reports are no longer displayed in the Jenkins reports. Embedded images in the JSON reports used to appear like this:
![image](https://cloud.githubusercontent.com/assets/3799823/15028890/1b0f0eb4-1219-11e6-915c-803e8bf8beb2.png)

But are now completely missing from the Jenkins reports. The embedded images are still present in the JSON reports:
[example_report.txt](https://github.com/damianszczepanik/cucumber-reporting/files/249562/example_report.txt)

They're just no longer being included in the Jenkins reports generated by your plugin.

**Comment by damianszczepanik** [comment]
https://jsonformatter.curiousconcept.com/ says this is not valid JSON, sorry about this

**Comment by ryderstorm** [comment]
Weird. According to these 3 validators, the contents of that `example_report.txt` file are valid:
http://jsonlint.com/
http://www.freeformatter.com/json-validator.html
http://codebeautify.org/jsonvalidate/cb06d80c

**Comment by damianszczepanik** [comment]
Based on json file:

``
				"location": {
					"file": "features/support/env.rb",
					"lines": {
						"data": [53]
					}
				}
``
it was not generated by cucumber-jvm so there is no official support for this

**Comment by ryderstorm** [comment]
That's from a report I generated locally just to show the images were still present in the json. Here is an actual full report from my Jenkins server. It has 23 different embedded png images in it that aren't showing up anywhere in the html reports generated by cucumber-reporting.
https://gist.github.com/ryderstorm/d7c87f0a3d5ee1d3337c33706ecccc49

**Comment by ryderstorm** [comment]
The reports are being generated by cucumber run from ruby tests. The images were being embedded just fine before the 2.2.0 update.

**Comment by smacgaha** [comment]
@ryderstorm What version of Cucumber are you using?

**Comment by ryderstorm** [comment]
`ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]`

**Comment by smacgaha** [comment]
I'm on 2.3.3 which I guess changed the json formatter schema slightly, as my hooks display that information as `"location": "features/support/env.rb:53"` instead. I'm still having the same problem with displaying screenshots that are taken in the after hooks, however.

Here's an example that I'm able to reproduce with 2.2.0: 
[cucumber.txt](https://github.com/damianszczepanik/cucumber-reporting/files/251170/cucumber.txt)

**Comment by ryderstorm** [comment]
I upgraded to the latest version of cucumber but there was no change. However, I think I've narrowed down the problem. 

I added embedded screenshots to the beginning and end of a scenario via Before and After hooks. The screenshot from the Before hook does appear in the Jenkins generated html report, but the screenshot from the After hook does not:
![image](https://cloud.githubusercontent.com/assets/3799823/15116624/09785bd0-15d2-11e6-92cc-f7e9f91f92dd.png)

So it looks like any images embedded during the After hooks aren't getting processed.

Here's the JSON report that was used by Jenkins to generate the HTML report. Both the Before and After screenshots are present in the JSON: https://gist.github.com/ryderstorm/13b4b258f249fdc369a38c8902bd6f98

**Comment by damianszczepanik** [comment]
Will take a look but since this is not jvm-cucumber report but ruby some differences may not be supported

**Comment by ryderstorm** [comment]
@damianszczepanik - I really appreciate you taking the time to investigate. This plugin is by far the best and most feature-rich of all the Jenkins/cucumber reporting plugins I've tried. :+1:

**Comment by reach2jeyan** [comment]
Is this issue resolved?

**Comment by damianszczepanik** [comment]
File new issue with details so I can take a look
