### ISSUE TITLE
Sending email with reports

### ISSUE THREAD

**Issue by maksimsarychau** [damianszczepanik/cucumber-reporting#441]
Hi. Is it possible to add report generation for sending it as email? Something lightweight and in one html file. With configurable url to the big beautiful report? 

Btw, may be such feature already possible, but I didn't found.

**Comment by damianszczepanik** [comment]
Sounds like nice feature that should be implemented

**Comment by Purus** [comment]
Or the entire report can be automatically converted to PDF format to be sent via email.

**Comment by maksimsarychau** [comment]
I think 2 such features will be really useful.

**Comment by damianszczepanik** [comment]
For now I can suggest to add email as the post-build action so email is sent once the build becomes unstable or failed

**Comment by maksimsarychau** [comment]
Cool. Thanks. But what about simple function with String output? Like standard, but for example: generateReportsAsEmail. In this case we can use already existing logic during integration cucumber in existing frameworks.

**Comment by a-yumashin** [comment]
> For now I can suggest to add email as the post-build action so email is sent once the build becomes unstable or failed
But the report consists of _several_ files: html-pages, javascripts, external stylesheets, fonts. So we can't use such report as the message **body**. And zipping all these files and sending them as an **attachment** makes no sense, IMHO.
I think some _lightweight_ version of the report is needed to be used as message body. What about creating a special option like GenerateSingleFileReport accessible from code and Maven as well?

**Comment by damianszczepanik** [comment]
Anyone is happy to prepare PR about it?

**Comment by mpkorstanje** [comment]
A few things would have to be changed.

1. Bootstrap, jQuery and other javascript libraries would have to be included by referencing a cdn.
2. Images and other attachment would have to be all url encoded. E.g.
```
<a  href="data:some/mimetypebase64, LOADS OF B64 Data">
```
3. Add some js to make it all single page.

At this point I'm questioning the use of a template engine. I would think it better to create single page javascript app that either reads the json file or is concatenated to it.

**Comment by deepikaguha** [comment]
Hi All,

Can any please let me know whether or not can i send these cucumber html report as an attcahememt post automation is run also why am i not able to work with TestNg (it is either test runner or testng i can use)

**Comment by damianszczepanik** [comment]
Suggest to use another plugin for this. There are a few that can be utilized.

**Comment by Mitalig** [comment]
Any progress on this?

**Comment by sanjayvarma498** [comment]
i need to cucumber reports in email. Can anybody please tell me how to do it

**Comment by damianszczepanik** [comment]
You can use email plugins that can do that

**Comment by tmnuwan12** [comment]
> You can use email plugins that can do that

Can you please provide some reference to this so called email plugin.. is this some cucumber email plugin..?
