### ISSUE TITLE
Unable to disable logging

### ISSUE THREAD

**Issue by Purus** [damianszczepanik/cucumber-reporting#446]
I am unable to disbale logging once I include the cucumber-reporting in the project.

Wihtout these the log configurations work fine but once I include this library, I see Hibernative related logs as Info/Debug message.

Below is my log4j2.xml file.

```
        <Logger name="org.hibernate" level="error"/>
        <Logger name="org.hibernate.SQL" level="error"/>
        <Logger name="org.hibernate.cache" level="error"/>
        <Logger name="org.hibernate.jdbc" level="error"/>
        <Logger name="org.hibernate.transaction" level="error"/>
        <Logger name="org.hibernate.hql" level="error"/>
        <Logger name="org.hibernate.tool.hbm2ddl" level="errors"/>
        <Logger name="org.hibernate.hql.ast.AST" level="errors"/>
        <Logger name="log4j.logger.org.hibernate.type" level="error"/>
        <Logger name="org.hibernate.type.descriptor.sql.BasicBinder" level="error"/>
```

**Comment by damianszczepanik** [comment]
I believe you need to remove https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/resources/log4j2.properties file from released jar - check and if it works prepare new PR that removes this file.
