### ISSUE TITLE
Broken links when using matrix projects in Jenkins

### ISSUE THREAD

**Issue by midopa** [damianszczepanik/cucumber-reporting#464]
Valid link:
`//localhost:8080/job/Sandwich/58/jam=raspberry,bread=rye,cheese=cheddar/cucumber-html-reports/`

* Sandwich is the Project Name
* 58 is the build number
* The other stuff are the parameters/permutation for the matrix build

But the links in the generated page look like:
`//localhost:8080/job/jam=raspberry,bread=rye,cheese=cheddar/58/cucumber-html-reports/`

* The project name is gone
* and the build number is in the wrong place

This is consistent for all three links:
* Jenkins
* Previous results
* Last results

**Comment by damianszczepanik** [comment]
Have you tried to solve such problem by setting https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/Configuration.java#L65 ?

**Comment by midopa** [comment]
I tried setting it through the Jenkins plugin and the URLs are still wrong:
`//localhost:8080/job/Sandwich/job/jam=raspberry,bread=rye,cheese=cheddar/58/cucumber-html-reports/`

`setJenkinsBasePath` is meant to point to the Jenkins instance, not to the Jenkins project, because the report tool crafts the rest of the URL path and appends it to the base path.

So it seems the reporter should be made aware of a few things:
* Whether or not the Jenkins project is a matrix project. If so, then the URLs are structured differently
* Retrieve the correct Project name. Right now it's getting the permutations/matrix configuration for a particular run
* Retain the matrix configuration for the run and include it in the report somehow. This will be needed for the URL anyway.

**Comment by damianszczepanik** [comment]
Can you prepare PR with correct solution? Seems like not many installations have this option enabled so its hard to test it

**Comment by midopa** [comment]
Turns out this is a simple fix that can be done in the Jenkins plugin. PR coming for that repo

**Comment by midopa** [comment]
https://github.com/jenkinsci/cucumber-reports-plugin/pull/58

**Comment by midopa** [comment]
https://github.com/jenkinsci/cucumber-reports-plugin/pull/58

**Comment by midopa** [comment]
Fix is merged. Will be avail next plugin release. So I'll close this.
