### ISSUE TITLE
Support for AMBIGUOUS status for Cucumber-JS

### ISSUE THREAD

**Issue by edzius** [damianszczepanik/cucumber-reporting#467]
Hi, i got myself into situation when test results has "ambigous" step. And as far as i can understand this causes reporter to crash. According to https://github.com/cucumber/cucumber/wiki/Step-Definitions#ambiguous-steps this step status could occur when more than one matching step definitions is found.

I get this exception in jenkins build cucumber-html-reports/ page:

> java.lang.IllegalArgumentException: No enum constant net.masterthought.cucumber.json.support.Status.AMBIGUOUS
> 	at java.lang.Enum.valueOf(Enum.java:236)
> 	at net.masterthought.cucumber.json.support.Status.valueOf(Status.java:8)
> 	at net.masterthought.cucumber.json.support.Status.toStatus(Status.java:28)
> 	at net.masterthought.cucumber.json.Step.calculateStatus(Step.java:86)
> 	at net.masterthought.cucumber.json.Step.setMedaData(Step.java:79)
> 	at net.masterthought.cucumber.json.Element.setMedaData(Element.java:130)
> 	at net.masterthought.cucumber.json.Feature.setMetaData(Feature.java:149)
> 	at net.masterthought.cucumber.ReportParser.setMetadata(ReportParser.java:90)
> 	at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:60)
> 	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:47)
> 	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:134)
> 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:74)
> 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:776)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
> 	at hudson.model.Build$BuildExecution.post2(Build.java:183)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
> 	at hudson.model.Run.execute(Run.java:1763)
> 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
> 	at hudson.model.ResourceController.execute(ResourceController.java:98)
> 	at hudson.model.Executor.run(Executor.java:381)

I am using protractor + cucumberjs. Here is sample JSON results that causes the crash:

> ...
>           {
>             "name": "I click on \"Cancel\" button",
>             "line": 240,
>             "keyword": "And ",
>             "result": {
>               "status": "ambiguous"
>             }
>           },
>           {
>             "name": "configuration is not changed",
>             "line": 241,
>             "keyword": "Then ",
>             "result": {
>               "status": "skipped"
>             },
>             "match": {
>               "location": "/var/lib/jenkins/jobs/Cuke-2RA/workspace/test/e2e/2ra/features/config.steps.js:120"
>             }
>           },
> ...

**Comment by damianszczepanik** [comment]
status": "ambiguous

It seems to be not valid status, is that?

**Comment by edzius** [comment]
As i said i am using cucumberJS, so i am not sure wheter this is standard status.

I did some checks in cucumberJS code and i found this: https://github.com/cucumber/cucumber-js/blame/0e284313c2c75aebd53f74ea966e8c14d8946800/lib/cucumber/status.js .
From file commit log seems they have added this non standard (ambiguous) status to explicitly handle duplicated step definitions.

Anyway reporter crash does not look right, it would be nice if this extra result status be handled. For sake of simplicity i think it could even be interpreted as existing status "missing".

**Comment by damianszczepanik** [comment]
Sounds good, will take a look at this but I don't know when. From one of the recent commit I'm able to handle unusual cases like this one.

**Comment by edzius** [comment]
Great! Thanks :)

**Comment by damianszczepanik** [comment]
@midopa what do you think about adding new status into the Status class? Should be easy and enough to make it working. ..

**Comment by midopa** [comment]
Cucumber also defines Redundant step errors:
https://github.com/cucumber/cucumber/wiki/Step-Definitions#redundant-step-definitions

These can certainly be added, but I worry about cluttering the test report. Basically we'd be adding two more columns for step statuses. I think I'd prefer to combine them somehow. Something like a `Step Mismatch`.

Thnoughts?

**Comment by damianszczepanik** [comment]
I would start from renaming those two into Undefined using deserializer https://github.com/damianszczepanik/cucumber-reporting/tree/master/src/main/java/net/masterthought/cucumber/json/deserializers because it does not create new columns that are not used in JVM implementation

**Comment by midopa** [comment]
FYI the Cucumber JVM reports ambiguous steps as failures with the ambiguity exception placed into the error message field.

And if there are redundant steps, it crashes at the beginning with a message talking about the redundancy problem.

So I think both ambiguous and redundant steps/statuses should map to failure.

**Comment by damianszczepanik** [comment]
@midopa @edzius
Take a look at attached PR and let me know if this is fine and if you need more than requested state?
