### ISSUE TITLE
Error Messages that have the same text are only expandable for the first occurrence in the report

### ISSUE THREAD

**Issue by andrewcurtis-mris** [damianszczepanik/cucumber-reporting#471]
I am using version 2.3.0 to create reports. When viewing the reports for a feature where two or more steps fail with the exact same error message the error message is only available to drill down into on the first occurance.

if scenario 1 step1 fails with the error:
"junit.framework.ComparisonFailure: expected:<[0] Days> but was:<[25.7] Days>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)"

and scenario 2 step 1 also fails with the error:
"junit.framework.ComparisonFailure: expected:<[0] Days> but was:<[25.7] Days>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)"

The link to expand the error message on scenario 2 step 1 only expands/collapses the error message under the failed step in scenario 1 and there is no message to actually display for the second and subsequent occurrences.

I assume this is because of the way hash is used on the message and the hash would be identical for identical messages. It can be hard to see the error if there are a large number of scenarios and they may not show up close to the other occurrences.

**Comment by damianszczepanik** [comment]
That's because expandable ID is generated by hashCode. This waits for improvements.

**Comment by midopa** [comment]
FYI, this only happens for same error messages in Scenario Outlines. Otherwise, the error messages will be different because the feature file and line number are included in the stack trace string.

Doesn't invalidate the bug. Just wanted to clarify when it happens/how to repro.

**Comment by midopa** [comment]
In the end, it boils down to getting a unique ID for each "object" somehow. I don't think there's a clear-cut way to do this without knowing things like the memory location and such. Some implementations can provide this, but that locks usage to a particular JVM.

A simple solution would be to add a random number after the hash. It will reduce the chances of a collision. But a collision is still possible. Another way is to just use some incrementing counter. I'm testing the later.
