### ISSUE TITLE
Graphs and icons that collapse/uncollapse doesn't render in Chrome

### ISSUE THREAD

**Issue by gustavoriveray** [damianszczepanik/cucumber-reporting#472]
When I go to a report the graphs doesn't render

When I click on one of the Features, the steps are collapsed, the icon to uncollapsed doesn't show and clicking the square it shows doesn't do anything.

This only happens on Chrome, but in Firefox it renders correctly.

I get a bunch of these logs in Chrome's console

Blocked script execution in 'http://myjenkinsinstallation/job/myjob/cucumber-html-reports/' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

**Comment by damianszczepanik** [comment]
Looks like you are using the old version, upgrade

**Comment by gustavoriveray** [comment]
I did upgraded to 2.4.0, from 2.1.0

**Comment by damianszczepanik** [comment]
Can you check 2.3.0? There were some changes between those versions that may have impact

**Comment by gustavoriveray** [comment]
Sure, will get back to you later

**Comment by VireshDoshiArm** [comment]
I upgraded from 2.2.0 to 2.4.0 and noticed that the charts did not display correctly as per the issues observed by https://github.com/gustavoriveray

**Comment by lbeder** [comment]
:+1:

**Comment by midopa** [comment]
Seeing to today also for some reason. Didn't upgrade my browser, but Chrome is saying it's ready to upgrade. Maybe it does a partial upgrade and this was introduced?

Anyway, seems related:
* https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy

HTML Publisher ran into this back in Jenkins 1.6.x:
* https://github.com/jenkinsci/htmlpublisher-plugin/pull/22

**Comment by midopa** [comment]
Perhaps this line should be changed:
https://github.com/jenkinsci/cucumber-reports-plugin/blob/9c291fe6eda4f102d5305f7f9e4895c349bac531/src/main/java/net/masterthought/jenkins/CucumberReportBaseAction.java#L38

From
```"sandbox; script-src 'self' 'unsafe-inline'; default-src 'self'; img-src 'self'; style-src 'self';"```
To
```"sandbox allow-scripts; script-src 'self' 'unsafe-inline'; default-src 'self'; img-src 'self'; style-src 'self';"```

**Comment by damianszczepanik** [comment]
Fix will be provided soon, there are some problems with this and I have contacted Jenkins team. Please hold on...

**Comment by damianszczepanik** [comment]
New version has been published, please upgrade
