### ISSUE TITLE
What's the difference between undefined and missing steps?

### ISSUE THREAD

**Issue by midopa** [damianszczepanik/cucumber-reporting#479]
Based on this doc, they seem to be the same thing:
https://www.relishapp.com/cucumber/cucumber-tck/docs/core-scenarios-steps-mappings#missing-step-mapping-means-the-scenario-is-undefined

Inside the `gherkin.formatter.Result` source, there's no `missing` status, only `undefined`:
https://github.com/ramonza/gherkin/blob/master/java/src/main/java/gherkin/formatter/model/Result.java#L16

Can this column/status be removed?

**Comment by damianszczepanik** [comment]
Just to be clear: you'd like to remove column from summary table but do not remove this status at all?

If so I will take a look and try to answer fro two questions:
- how was the support for older cucumber versions
- is the article valid for all cucumber implementation or only for particular

I'm trying to make Cucumber-JVM more open for other implementations. Currently Ruby is partially supported but I see also some JavaScript users want use it. That means that such modification must be done carefully.

**Comment by midopa** [comment]
Ah, I didn't know about the cross-implementation support goal.

My original request was to remove the column and combine 'missing' counters with the 'undefined' counters. The plugin can still support multiple implementations, but for the report, can just have one 'undefined' status that combines 'undefined' and 'missing' statuses.

**Comment by damianszczepanik** [comment]
Sounds like the step to remove forever http://cucumber.github.io/api/gherkin/javadoc/gherkin/formatter/model/Result.html and probably the same with the PENDING (not sure)

@midopa  will you prepare PR for this?

**Comment by midopa** [comment]
Cucumber uses Pending for auto-generated stub code for steps. Some other people might use Pending for other reasons too.

But I've never seen the Missing status from Cucumber. Was there ever a time it was valid? If so, then instead of removing Missing, maybe we just map it to Undefined, since Undefined is an official Gherkin status. Thoughts?

**Comment by damianszczepanik** [comment]
I'm not sue about missing however I suggest to check if this state is not valid for ruby implementations. If not drop it else merge states.

**Comment by midopa** [comment]
Looks like Cucumber's Ruby implementation contains 'Pending':
https://github.com/cucumber/cucumber-ruby-core/blob/master/lib/cucumber/core/test/result.rb#L19

There's also 'Unknown' but if you look at line 27, it's used as the default state of every step they get a status assigned by the engine. So 'Unknown' should never appear in a report.

So the action item is to just remove 'Missing'

**Comment by damianszczepanik** [comment]
Agree

**Comment by midopa** [comment]
#505
