### ISSUE TITLE
HTML generation issue on div class

### ISSUE THREAD

**Issue by cleclef** [damianszczepanik/cucumber-reporting#480]
My report doesn't show graph anymore, and complains about script sandboxing (other reported bug #472 ).

I see in the report that the div class double-quotes are unpaired on container-fluid
`<div id="report-lead" class="container-fluid>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2>Features Statistics</h2>
              <p>The following graphs show passing and failing statistics for features</p>
          </div>
  </div>
</div>
`

**Comment by damianszczepanik** [comment]
Duplicate
