### ISSUE TITLE
Tags statistics - Filtering tags to be displayed in the graph

### ISSUE THREAD

**Issue by aleitamar** [damianszczepanik/cucumber-reporting#482]
Hi,

My team is considering tagging each cucumber scenario with the matching JIRA ID.
The problem we have with the report, is that the Tags Statistics graph is displaying all the tags (including the JIRA ID tags) and this makes the graph very big and unusable.

Is there a way to filter tags to be displayed in the graph?

Thanks,
Itamar

**Comment by damianszczepanik** [comment]
Don't have plan for this but I will merge pull request if you prepare such feature.

**Comment by aleitamar** [comment]
Hi @damianszczepanik,

I have created the following pull requrest:
https://github.com/damianszczepanik/cucumber-reporting/pull/486

Any feedback will be appreciated.
