### ISSUE TITLE
Generated HTML-Page does not show stats and title (includes not working) on 2.5.

### ISSUE THREAD

**Issue by gaffa** [damianszczepanik/cucumber-reporting#485]
![image](https://cloud.githubusercontent.com/assets/904804/16362767/7daa3360-3bb7-11e6-9b31-9c3c31b905b5.png)

If you need anything else, just let me know.

**Comment by damianszczepanik** [comment]
Upgrade to the newest version then include stack trace as above and JSON file

**Comment by gaffa** [comment]
Hi Damian! I am using the latest version available in maven central. 2.5.0.The posted screenshot is from that.
http://search.maven.org/#search%7Cga%7C1%7Ccucumber-reporting
Is there a newer one?
I added a zip-file of the json I tried to create the html-report from. Just ignore the appium-logs-folder in it.
[cucumber.zip](https://github.com/damianszczepanik/cucumber-reporting/files/333643/cucumber.zip)

**Comment by gaffa** [comment]
I have isolated the files in a test project and tried again-it worked. It must be something in our setup. Maybe dependency-clash or something. Sorry to waste your time!
