### ISSUE TITLE
Gherkin syntax is not properly HTML escaped

### ISSUE THREAD

**Issue by btaz** [damianszczepanik/cucumber-reporting#49]
When the Gherkin scenario contains e.g. XML, then it's not properly escaped when displayed on the cucumber-reporting HTML page.

![screen shot 2014-01-09 at 10 00 08 pm](https://f.cloud.github.com/assets/597495/1885066/3803ac7e-79bd-11e3-96b3-665933a882b6.png)

This unfortunately displays as:

![screen shot 2014-01-09 at 9 58 48 pm](https://f.cloud.github.com/assets/597495/1885068/55519b56-79bd-11e3-8b3c-94e137f67ccb.png)

The problem is that the browser tries to parse the XML tags as HTML. Any of these characters need to be escaped: & < > " /

One option is to use velocity-tools EscapeText for this.
http://velocity.apache.org/tools/devel/generic/EscapeTool.html

I created a pull request for this:
https://github.com/masterthought/cucumber-reporting/pull/48

**Comment by SlyAtBest** [comment]
I've experienced a similar issue when using an Assert.assertEquals() to test a boolean value.  The value is returned as either &lt;true> or &lt;false>, which is not shown in the generated report when rendered by a browser.  I'm guessing this is because it is being treated as a html tag and so this needs to be escaped in order for it to display properly.  The page source reveals that the underlying values do exist.

Example:
> boolean expectedType = true;
> boolean currentType = false; 

> Assert.assertEquals("Package is not listed as the correct type",
                expectedType, currentType);

Should produce:

> Package is not listed as the correct type expected:&lt;true> but was:&lt;false>

But instead produces:

> Package is not listed as the correct type expected:<true> but was:<false>

**Comment by damianszczepanik** [comment]
This issue has been already resolved and released.

**Comment by msymons** [comment]
In what version was this resolved and released?  The release notes only go up to v0.0.21:

https://github.com/masterthought/cucumber-reporting/wiki/Release-Notes

The same is also true for jenkins-cucumber-jvm-reports-plugin-java  (where I have developers refusing to upgrade the plugin until I can tell them what has changed).

**Comment by damianszczepanik** [comment]
New cucumber reporting has been released weeks ago. New version is available also via Jenkina

**Comment by msymons** [comment]
I know that the new version was released weeks ago..  and that now there is also v0.2.1.  What I am seeking is a "release notes" that summarizes what has changed in the release.  To repeat what I said, no one in my organization is willing (or allowed) to upgrade unless they know what has changed in the release.

I gave a link in my previous comment but that link now just redirects to the main page of the cucumber-reports.    The release notes for cucumber-reporting-jenkins do not yet redirect so you can see what I am talking about:

https://github.com/damianszczepanik/cucumber-reporting-jenkins/wiki/Release-Notes

![cucumber-reporting-jenkins-release-notes](https://cloud.githubusercontent.com/assets/4938718/9304252/e7fd0732-44dd-11e5-8300-2e594f2badf7.png)

Note that the notes are not verbose... but they do provide issue IDs.

**Comment by damianszczepanik** [comment]
That would be nice if only I had more time for this :( also there are many commits that have no impact for end-users but refer to code quality so sometimes is hard to say if particular change should be mentioned in release notes or not.
