### ISSUE TITLE
Plugin prevents next plugins execution when tests failed?

### ISSUE THREAD

**Issue by a-yumashin** [damianszczepanik/cucumber-reporting#503]
I have the following plugins bound to Maven lifecycle phases:

```
pre-integration-test:  maven-resources-plugin, 3.0.1   - prepares certain files
integration-test:      maven-failsafe-plugin, 2.19.1   - runs Cucumber-jvm tests
post-integration-test: maven-cucumber-reporting, 2.4.0 - generates rich HTML report
                       exec-maven-plugin, 1.5.0        - stops certain processes
```
The two plugins bound to the "post-integration-test" phase are listed here in the order they are defined in the POM. If all tests pass without errors (at the "integration-test" phase) - **both** these plugins are executed. But **if any of the tests fail** - then I get the following situation:

- "maven-cucumber-reporting" successfully generates rich HTML report. However, I see the following in the log file: _"Failed to execute goal maven-cucumber-reporting:2.4.0:generate (execution) on project ...: Error Found: BUILD FAILED"_. This is strange because the report was successfully generated (as I already said).
- "exec-maven-plugin" **is not executed at all**.

If I comment out "maven-cucumber-reporting" plugin in the POM - then "exec-maven-plugin" runs successfully. In this case I see the following in the log file: _"Failed to execute goal maven-failsafe-plugin:2.19.1:verify (default) on project ...: There are test failures"_. Well, this message is quite expected when some test(s) have failed.

Seems that "maven-cucumber-reporting" plugin (bound to the "post-integration-test" phase) prevents execution of all next plugins - in case when the "integration-test" phase has failed. Could You please check this?

**Comment by damianszczepanik** [comment]
I expect that the reason is that previous plugin marked the build as failed so rest psot-actions are skipped. However I have no experiences with maven-cucumber-reporting so you are welcome to prepare PR for this problem if needed.

**Comment by a-yumashin** [comment]
Hm... I thought "maven-cucumber-reporting" Your project also: https://github.com/damianszczepanik/maven-cucumber-reporting

**Comment by damianszczepanik** [comment]
It does but since I don't use it on the daily basis I don't focus much about it so any PR are more then welcome.

**Comment by damianszczepanik** [comment]
Check with the most recent release, this should work better now

**Comment by gogiar** [comment]
hi,
could you please specify which version of maven-cucumber-reporting plugin fixes this issue. What do I need to do in order to execute next plugin when the Build passes or Fails. I want to be able to " run exec-maven-plugin" after the maven-cucumber-reporting plugin
