### ISSUE TITLE
Group Identically Named Features

### ISSUE THREAD

**Issue by stevejensen22** [damianszczepanik/cucumber-reporting#504]
I am using this plugin https://github.com/temyers/cucumber-jvm-parallel-plugin to generate a runner class **per scenario** (for concurrency) which then generates it's own cucumber json report file during test execution. Currently, `cucumber-reporting` displays a feature per json report file, even though all of those json reports are for an identically named feature.

See example image below:
<img width="1915" alt="same_feature" src="https://cloud.githubusercontent.com/assets/10365264/17163053/aee4e014-5378-11e6-8be2-280f28e23650.png">

Would it be possible to add a configuration option to `Group all features that are identically named`?

PS. If background steps fail, it doesn't fail the scenario, and it probably should. See above ☝️

**Comment by damianszczepanik** [comment]
Sounds nice but I don't have plan for such feature. You can prepare change if you like.

**Comment by damianszczepanik** [comment]
Order of the presented features can be sorted so it won't be improved

**Comment by shtraker** [comment]
This issue is VERY important , I'm having the same problem.

**Comment by prayagvakharia** [comment]
I have same issue. Is there any way found for this problem?
