### ISSUE TITLE
cucumber-jvm reports are not showing the updated results

### ISSUE THREAD

**Issue by udayanem** [damianszczepanik/cucumber-reporting#508]
I am not getting the latest test results in Cucumber-jvm reports. Previous execution results was shown.

Cucumber-jvm reports version: 2.6.3

Below is my Cucumber runner file,
@RunWith(Cucumber.class)
@CucumberOptions(
[cucumber.txt](https://github.com/damianszczepanik/cucumber-reporting/files/407407/cucumber.txt)
![jenkins](https://cloud.githubusercontent.com/assets/10852370/17490818/652dc7de-5dc2-11e6-8f01-e9c73966d7ee.png)

features="classpath:",
glue=
{"stepdefinitions","helpers"}
,
//	plugin =
{"pretty", "html:target/cucumber","json:target/cucumber.json"}
,
plugin =
{"pretty", "json:target/cucumber.json"}
,
tags=
{"@RegistrationForm"}
)
public class Runnertest 
{
}
Attachment containing the actual json file created.
But you could see two feature files are executed, though i have configured only one feature in above.

**Comment by damianszczepanik** [comment]
Above configuration is not plugin configuration but cucumber-jvm. You can check job logs for details

**Comment by udayanem** [comment]
Hi,

Thanks for your reply.

I further nail down this problem and came to know that the problem is because the json file in jenkin's workspace is not getting updated.
`Ex: C:\Users\user\.jenkins\workspace\XXX_V2\target\**cucumber.json**`

Though my project's file directory is `E:\Frameworks\XXX_V2`

By chance do you have any ideas why this workspace is not getting updated? What configurations need to take care of?

Thanks,
Uday

**Comment by damianszczepanik** [comment]
If the problem is with JSON, this is not plugin problem which expects the JSON to be correct
