### ISSUE TITLE
ReportBuilder feature envy

### ISSUE THREAD

**Issue by anoordover** [damianszczepanik/cucumber-reporting#51]
I think that the class ReportBuilder does to much.
It prepares variables for the reports.
It starts the merging with a Freemarker template.
It writes the result to a file.
I think writing tests for this class is therefore to hard.
Should we use mockito to do the unittest?
How can we enhance testability?
Instantiation of classes is much harder to mock.
Should we use use powermockito or use factories which can be injected for mocking purposes?

**Comment by damianszczepanik** [comment]
Have been improved and will be even better in version 1.x.x
