### ISSUE TITLE
Scenario Description is not displayed

### ISSUE THREAD

**Issue by skemptner** [damianszczepanik/cucumber-reporting#510]
[Maven JVM]
Sometimes it makes sense to add information to a Feature or Scenario that is also displayed in the report.

The cucumber reports (both json and html) support this in form of a description.
However, in the reports of this plugin only Feature descriptions are displayed. **Scenario descriptions are not displayed**.

My RunnerClass looks like this:
```
@RunWith(Cucumber.class)
@CucumberOptions(
        glue={"myStepDefsi"},
        plugin={"json:target/cucumber/cucumber.json","html:target/cucumber/cucumberHtml/"},
        features={"src/test/resources/features"})
public class RunCukesTest {
}
```

When running following Scenario:
```
Feature: This is a feature
  This is a feature description that should be shown in the report

  Scenario: a scenario
    This is a scenario description that should be shown in the report

    Given a person with name "Hans"
    When asking the person for its name
    Then the persons response is "Hans"
```

I get following reports:

Json:
```
[
  {
    "line": 1,
    "elements": [
      {
        "line": 4,
        "name": "a scenario",
        "description": "This is a scenario description that should be shown in the report",
        "id": "this-is-a-feature;a-scenario",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          ...
          ],
    "name": "This is a feature",
    "description": "This is a feature description that should be shown in the report",
    "id": "this-is-a-feature",
    "keyword": "Feature",
    "uri": "aFeature.feature"
  }
]
```
Cucumber html report:
![cucumberhtml](https://cloud.githubusercontent.com/assets/19508640/17779540/4fc13dc4-6568-11e6-8575-890fd097f9ab.png)

Html report with this plugin:
![customhtml](https://cloud.githubusercontent.com/assets/19508640/17779542/51ab33ec-6568-11e6-8f43-2ab7033e1186.png)

**Comment by damianszczepanik** [comment]
As you can see below, description is supposed and displayed. Upgrade the plugin and try again

https://raw.githubusercontent.com/damianszczepanik/cucumber-reporting/master/.README/feature-failed.png
