### ISSUE TITLE
Include result percentage in reports table (and graphs?)

### ISSUE THREAD

**Issue by romansmat** [damianszczepanik/cucumber-reporting#515]
This is an enhancement request.

Could you please consider adding a percentage in the reports table (and perhaps the diagrams) here:  cucumber-reporting/src/main/resources/templates/macros/report/statsTable.vm 

It is much easier to identify the status of the run through percentage numbers. Please see attached image for details. It needs some attention to rounding the number (e.g. in my screenshot it does not add up to 100%) but it should be fairly straight forward.

![selection_405](https://cloud.githubusercontent.com/assets/11835789/18047933/02370d8a-6de8-11e6-8e64-a1da02a37ac3.png)

**Comment by damianszczepanik** [comment]
Where would you like to see such information? Attach screenshot with updated data so I can handle it.

**Comment by romansmat** [comment]
Thanks for reaching back to me. 
I am attaching a new screenshot but you can also have a look at the one that I attached in the first place (has more details in the table footer).
Ideally we would like to have the percentage in the pie charts (while hovering the mouse next to each number) but the most crucial thing would be to have them in the table footers. More specifically that would be:
Scenarios - Passed (passed scenarios against total scenarios)
Scenarios - Failed (failed scenarios against total scenarios)
Steps Passed (passed steps against total steps) etc.

**Note:** 0% and rounding could need special handling.

Let me know if I can help you in any other way!
![screenshot from 2016-08-29 14 37 31](https://cloud.githubusercontent.com/assets/11835789/18050423/2b9b1d9c-6df7-11e6-9a2d-abe5730a7007.png)

**Comment by damianszczepanik** [comment]
I don't feel comfortable having two values in one cell so how about having another row? With some gaps where having percentage value does not make sense.

![chart](https://cloud.githubusercontent.com/assets/9612911/18106740/4323cd42-6f05-11e6-9bbd-11646bbe625d.png)

**Comment by damianszczepanik** [comment]
Also provide 33% or 33,56% ? What precision would be the best? Think about values such as 50% but also 3.44%

**Comment by romansmat** [comment]
Hello,

Regarding your questions:
- Having a second row is fine by me - This is only an aesthetic issue so if you feel more comfortable with that approach, please go ahead as such.
- I would prefer having one decimal value (e.g. 33.5 %) if possible. If you think this is not feasible or believe it looks wrong, then please go ahead with 2 decimal values (e.g. 33.45 %).

Is there any chance we have the percentage in the donut charts? 
When are you expecting this to be on a public version?

Thanks!

**Comment by damianszczepanik** [comment]
Percentage values will be provided for features scenarios and steps. For tags it is more complicated because tags are presented only as percentage values so recovering absolute values will fail.. 

I release every few weeks.

**Comment by romansmat** [comment]
Sounds good!

Thanks!
