### ISSUE TITLE
The mimetype 'application/zip' doesn't support

### ISSUE THREAD

**Issue by Hunterok1** [damianszczepanik/cucumber-reporting#523]
The mimetype 'application/zip' doesn't support. Could you add supporting of mimetype 'application/zip' to attach zip-archive into Cucumber-jvm Report?
Expected usage:  scenario.embed(dataArchive, "application/zip");

**Comment by damianszczepanik** [comment]
It is not difficult so I encourage you to add this support by preparing update. There are two files that you need to update. 
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/json/Embedding.java
https://github.com/damianszczepanik/cucumber-reporting/blob/e741f140c7304ca600d24c8f35b38ff7aaf6f4a6/src/main/resources/templates/macros/report/embeddings.vm

**Comment by Hunterok1** [comment]
It would be great if these fixes are included in next library version
'cucumber-java'. I mean v.1.2.5. Is it possible?

2016-09-20 20:14 GMT+03:00 Damian Szczepanik <notifications@github.com>:

**Comment by damianszczepanik** [comment]
Rather cucumber-reporting than cucumber-java

**Comment by Hunterok1** [comment]
When the cucumber-reporting can be updated with this fix? Could you help
with fast fix?

20 Сен 2016 г. 23:05 пользователь "Damian Szczepanik" <
notifications@github.com> написал:

**Comment by damianszczepanik** [comment]
Decide which library should be updated and if this one, prepare PR so I can merge it and release soon

**Comment by Hunterok1** [comment]
Could you add this fix into cucumber-java lib?
