### ISSUE TITLE
Descriptions and preformatted text

### ISSUE THREAD

**Issue by fredizzimo** [damianszczepanik/cucumber-reporting#537]
I'm trying fix the json output of Python Behave to generate output that is compatible with Cucumber Reporting. However I ran into an issue with descriptions containing new lines, they are ignored.

For error messages, I can see that you add `<pre>` tags so that they are formatted correctly, but the same doesn't seem to be the case with descriptions.

So my question is, how is multi-line descriptions supposed to be given in the json format?  Or is there a bug in the report templates, and the `<pre>` element should be there? I haven't tested the behaviour when viewing reports generated by Cucumber-JVM.

**Comment by damianszczepanik** [comment]
What would you like me to add to make description compatible with EOL but also wrap description for those who prefer this type of formatting?

**Comment by fredizzimo** [comment]
Thanks for the answer,

So if I understand you correctly, the description should wrap automatically if it's long enough. So I guess that probably means that I should remove the line breaks and let it wrap automatically. That shouldn't be a problem.

And no I don't think the default reporting behaviour needs to be changed, if that's the way it's supposed to work, If line breaks are really needed we could just insert html line breaks directly when writing the description, our manually surround them with `<pre>` tags

It's also of course possible to do that when generating the json, so that everything is automatically wrapped. And even to run the description through something like [pandoc](http://pandoc.org/) and generate html to support markdown in the description.

So I consider this a non-issue, and closing it.
