### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded in newer versions

### ISSUE THREAD

**Issue by Ryxmedia** [damianszczepanik/cucumber-reporting#545]
Hi,

after I updated from version 2.6.3 to 3.1.0 I suddenly got a "java.lang.OutOfMemoryError: GC overhead limit exceeded" exception on Jenkins.
My reports that I'm creating have about 200 test cases and I haven't any memory problems before.
I also tested with version 2.8.0, but got the same issue. Switching back to 2.6.3 fixed it.

I know that solving the issue on Jenkins could be by giving Maven more memory, but maybe there is another solution to use less memory again like in previous versions?
Also I know, that my reports will get bigger and bigger with time because I will add more test cases to the test runs.

Kind regards,
RyxMedia

**Comment by damianszczepanik** [comment]
So far i don't see how this is related to the plugin because this error can be caused by many reasons.

**Comment by Ryxmedia** [comment]
The error appears when the report gets generated via the generate report method of the plugin.

**Comment by damianszczepanik** [comment]
O need information to reproduce the issue.  Attach all data

**Comment by Ryxmedia** [comment]
I can't really give you all data.
Basically it is a huge test suite with 34 features, 192 scenarios and 2580 steps.
After all feature tests are run, I call the following method for generating the cucumber report:

`
public static void main(final String[] args) throws VelocityException, IOException, ParseException {
		// Create cucumber html report
		final List<String> cucumberJsonReportsList = new ArrayList<String>();
		try {
			Files.walk(Paths.get("target/cucumber")).forEach(filePath -> {
				if (Files.isRegularFile(filePath)) {
					cucumberJsonReportsList.add(filePath.toString());
				}
			});
			final File dir = new File("target/cucumber/cucumber-html-report");
			dir.mkdir();
			final File reportOutputDirectory = new File("target/cucumber/cucumber-html-report");
			String buildNumber = System.getProperty("buildNumber");
			final String projectName = "CMP";
			final String jenkinsBasePath = "";
			final boolean runWithJenkins = false;
			final boolean parallelTesting = true;
			// If we didn't get a buildnumber, we declare that run as a local one by setting the build number to 0
			if (buildNumber == null) {
				buildNumber = "0";
			}
			final Configuration configuration = new Configuration(reportOutputDirectory, projectName);
			// optionally only if you need
			configuration.setParallelTesting(parallelTesting);
			configuration.setJenkinsBasePath(jenkinsBasePath);
			configuration.setRunWithJenkins(runWithJenkins);
			configuration.setBuildNumber(buildNumber);
			// Create report
			final ReportBuilder reportBuilder = new ReportBuilder(cucumberJsonReportsList, configuration);
			reportBuilder.generateReports();
			// Upload cucumber report to report server if it is not a local run
			if (!buildNumber.equals("0")) {
				ReportsHelper.uploadCucumberReportToServer("cmp", "cucumber", "", buildNumber);
			}
		} catch (final NoSuchFileException e) {
			LOG.info("No Cucumber report found.");
		}
	}
`

At "reportBuilder.generateReports();" the "java.lang.OutOfMemoryError: GC overhead limit exceeded" exception occurs.
I run the same test suite with version 2.6.3 = no issues, but with 2.8.0 or 3.1.0 = memory error.

**Comment by damianszczepanik** [comment]
I don't think this is related to number of features, scenarios or steps because I'm running bigger report without any problem. Thus my idea is that the problem happens before the report is generated. And as I see you have written some code so you can analyze it. I need the stack trace

**Comment by amitsoni13** [comment]
I am also seeing this error. any recommendation around how to get it fixed?

**Comment by tutaidalal** [comment]
Facing the similar issue, I have attached the JSON file which has been generated before  creating cucumber report.

Started by user unknown or anonymous
Building in workspace /root/jenkins/jobs/report-generator/workspace
[CucumberReport] Preparing Cucumber Reports
[CucumberReport] Copied 1 json files from workspace "/root/reportPath" to reports directory "/root/jenkins/jobs/report-generator/builds/3/cucumber-html-reports/.cache"
[CucumberReport] Filtered out 1 json files:
[CucumberReport] /root/jenkins/jobs/report-generator/builds/3/cucumber-html-reports/.cache/RunSelectedTests.json
FATAL: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.zip.ZipCoder.getBytes(ZipCoder.java:80)
	at java.util.zip.ZipFile.getEntry(ZipFile.java:310)
	at java.util.jar.JarFile.getEntry(JarFile.java:240)
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1005)
	at sun.misc.URLClassPath$JarLoader.findResource(URLClassPath.java:983)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:188)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:569)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:567)



[RunSelectedTests.zip](https://github.com/damianszczepanik/cucumber-reporting/files/3539913/RunSelectedTests.zip)
