### ISSUE TITLE
Error showing DocStrings containing html character

### ISSUE THREAD

**Issue by fmarmar** [damianszczepanik/cucumber-reporting#556]
Hi, 

If a DocString content is an xml, reporter fail to show the DocString value.

**Comment by damianszczepanik** [comment]
Provide json report so I can take a look

**Comment by fmarmar** [comment]
Sorry, here it goes. I just made a pull request to fix the issue #557 


[sample-xml.txt](https://github.com/damianszczepanik/cucumber-reporting/files/572741/sample-xml.txt)

**Comment by mpkorstanje** [comment]
This has been fixed in version 3.4.0 with #576 and #584. I think we can close this.
