### ISSUE TITLE
Tag Statistics are wrong

### ISSUE THREAD

**Issue by dumitruc** [damianszczepanik/cucumber-reporting#56]
The tag statistic seem to encompase EVERYTHING, not just per tag results.

Here are some results:
![tags1](https://f.cloud.github.com/assets/5132659/2228882/499f1e22-9ae3-11e3-9e56-531909861058.PNG)
You can see in steps all the tags have the same numbers. Here is the feature file content which show the tag distribution.
![feature](https://f.cloud.github.com/assets/5132659/2228900/8770c58e-9ae3-11e3-89ea-92cf75cf2412.PNG)

(I noticed this on stand alone version including the cucumber-sandwich project)

**Comment by damianszczepanik** [comment]
Works fine with 0.2.2
