### ISSUE TITLE
Include screenshots in Cucumber report

### ISSUE THREAD

**Issue by shtraker** [damianszczepanik/cucumber-reporting#563]
Hi Damian,

Is it possible to include screenshots in cucumber report for the specific test scenario , so when you open to see the result you can see the screenshot where it is failed ? Also another great idea is to document your test and functionality by creating several screenshots during the test and then this to be visualized in the cucumber report. Is there such functionality , if yes , give an example how to do it please. If there isn't can you add this to the project it will be very usefull.

Thanks,
Br,
Ceco

**Comment by mpkorstanje** [comment]
You can use scenario.embed for this. If you need to take screen shots during the test you'll have to use the before or after hooks to store the current scenario in a class variable.

```java
public class AfterBrowserSteps implements En {

    public AfterBrowserSteps(WebDriver driver) {

        After((Scenario scenario) -> {
            if (!scenario.isFailed()) {
                return;
            }

            scenario.write("url: " + driver.getCurrentUrl());

            if (driver instanceof TakesScreenshot) {
                TakesScreenshot camera = (TakesScreenshot) driver;
                byte[] screenshot = camera.getScreenshotAs(BYTES);
                scenario.embed(screenshot, "image/png");
            }

            scenario.write(Utils.htmlEscape(driver.getPageSource()));
        });
    }
}
```

**Comment by vveliev** [comment]
This is more of how to use cucumber rather than cucumber report.

```.embed(srs, mime_type, label)```

**Comment by yogitasn** [comment]
Hi,

My project is using BDD framework(Cucumber) automated using Protractor/Selenium with Typescript as scripting language. It would be of great help if someone be able to provide code to attach screenshots using Typescript language. I researched a lot but could only find implementations in all other languages but Typescript/Javascript. 
Thanks in advance.

**Comment by mpkorstanje** [comment]
You are looking in the wrong place. Check the documentation at the cucumber-js. This plugin just creates reports.

https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/attachments.md

**Comment by Ranjeetshiva** [comment]
@After
  public void endTest(Scenario scenario) {
     if (scenario.isFailed()) {
            try {
               logger.info(scenario.getName() + " is Failed");
               final byte[] screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
              scenario.attach(screenshot , "image/png", "Taking Screen Shot");
              logger.info("This is an Info");
            } catch (WebDriverException e) {
                e.printStackTrace();
         }
       }

After Cucumber 6 we have use  "**scenario.attach**" I'm using 6.10 cucumber version
