### ISSUE TITLE
Unable to create report

### ISSUE THREAD

**Issue by Ryxmedia** [damianszczepanik/cucumber-reporting#565]
EDIT: Sorry for formating, I don't know why it doesn't work properly...

I'm trying to execute the following main method for creating the cucumber report:

` public static void main(final String[] args) {
		LOG.info("Create Cucumber HTML report");
		final List<String> cucumberJsonReportsList = new ArrayList<String>();
		try {
			Files.walk(Paths.get("target" + File.separator + "cucumber")).forEach(filePath -> {
				if (Files.isRegularFile(filePath)) {
					cucumberJsonReportsList.add(filePath.toString());
				}
			});
		} catch (final IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		final File dir = new File("target" + File.separator + "cucumber");
		dir.mkdir();
		final File reportOutputDirectory = new File("target" + File.separator + "cucumber");
		String buildNumber = System.getProperty("buildNumber");
		final String projectName = System.getProperty("projectName");
		final boolean runWithJenkins = false;
		final boolean parallelTesting = true;
		// If we didn't get a buildnumber, we declare that run as a local one by setting the build number to 0
		if (buildNumber == null) {
			buildNumber = "0";
		}
		final Configuration configuration = new Configuration(reportOutputDirectory, projectName);
		// optionally only if you need
		configuration.setParallelTesting(parallelTesting);
		configuration.setRunWithJenkins(runWithJenkins);
		configuration.setBuildNumber(buildNumber);
		// Create report
		final ReportBuilder reportBuilder = new ReportBuilder(cucumberJsonReportsList, configuration);
		reportBuilder.generateReports();
} `

I execute the method at the end of my build via the exec-maven-plugin:

`<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<version>${exec-maven-plugin.version}</version>
						<executions>
							<execution>
								<id>cucumber</id>
								<phase>post-integration-test</phase>
								<goals>
									<goal>java</goal>
								</goals>
								<configuration>
									<mainClass>xxx.selenium.reporter.CreateCucumberReport</mainClass>
									<classpathScope>compile</classpathScope>
									<cleanupDaemonThreads>false</cleanupDaemonThreads>
									<systemProperties>
										<systemProperty>
											<key>projectName</key>
											<value>ClientPortal</value>
										</systemProperty>
									</systemProperties>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>`

Content of my "cucumber-report.json":

`[
  {
    "comments": [
      {
        "line": 1,
        "value": "#encoding: UTF-8"
      }
    ],
    "line": 3,
    "elements": [
      {
        "before": [
          {
            "result": {
              "duration": 43245441,
              "status": "passed"
            },
            "match": {
              "location": "EmployeeTeamGlobalSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 4600305,
              "status": "passed"
            },
            "match": {
              "location": "OrganisationResearchSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 3687899,
              "status": "passed"
            },
            "match": {
              "location": "NavigationSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 4383238,
              "status": "passed"
            },
            "match": {
              "location": "AdminSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 12125563,
              "status": "passed"
            },
            "match": {
              "location": "ContactProfileGlobalSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 10993856,
              "status": "passed"
            },
            "match": {
              "location": "RecommendationsSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 5572217,
              "status": "passed"
            },
            "match": {
              "location": "ContactProfileSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 8908674,
              "status": "passed"
            },
            "match": {
              "location": "DisclosuresSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 11436090,
              "status": "passed"
            },
            "match": {
              "location": "QuicksearchSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 7013740,
              "status": "passed"
            },
            "match": {
              "location": "EmployeeProfileSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 2890312,
              "status": "passed"
            },
            "match": {
              "location": "OrganisationTradingSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 2759569,
              "status": "passed"
            },
            "match": {
              "location": "TeamsSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 3903010,
              "status": "passed"
            },
            "match": {
              "location": "ContactCoverageSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 9885335,
              "status": "passed"
            },
            "match": {
              "location": "EmployeeContactsGlobalSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 8096559,
              "status": "passed"
            },
            "match": {
              "location": "EmployeeMeetingsAndNotesSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 7126045,
              "status": "passed"
            },
            "match": {
              "location": "EmployeeProfileGlobalSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 3594591,
              "status": "passed"
            },
            "match": {
              "location": "OrganisationOverviewGlobalSteps.initializePageObjects(Scenario)"
            }
          },
          {
            "result": {
              "duration": 2801194,
              "status": "passed"
            },
            "match": {
              "location": "OrganisationOverviewSteps.initializePageObjects(Scenario)"
            }
          }
        ],
        "line": 6,
        "name": "Performing an action on the logo - TestCaseId[10022]",
        "description": "",
        "id": "global---navigation;performing-an-action-on-the-logo---testcaseid[10022]",
        "after": [
          {
            "result": {
              "duration": 183822,
              "status": "passed"
            },
            "match": {
              "location": "NavigationSteps.addScreenshotToFailedScenario(Scenario)"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 2010863392,
              "status": "passed"
            },
            "line": 7,
            "name": "the user is on the homepage",
            "match": {
              "location": "NavigationSteps.the_user_is_on_the_homepage()"
            },
            "keyword": "Given "
          },
          {
            "result": {
              "duration": 138065593,
              "status": "passed"
            },
            "line": 8,
            "name": "he performs an action on the logo",
            "match": {
              "location": "NavigationSteps.he_performs_an_action_on_the_logo()"
            },
            "keyword": "When "
          },
          {
            "result": {
              "duration": 1415448612,
              "status": "passed"
            },
            "line": 9,
            "name": "he gets navigated to his own employee profile page",
            "match": {
              "location": "NavigationSteps.he_gets_navigated_to_his_own_employee_profile_page()"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "line": 5,
            "name": "@ID_10022"
          },
          {
            "line": 5,
            "name": "@PRIORITY_HIGH"
          },
          {
            "line": 5,
            "name": "@AUTOMATED"
          },
          {
            "line": 5,
            "name": "@ACTIVE"
          },
          {
            "line": 5,
            "name": "@DEV"
          }
        ]
      }
    ],
    "name": "Global - Navigation",
    "description": "",
    "id": "global---navigation",
    "keyword": "Feature",
    "uri": "global/Navigation.feature",
    "tags": [
      {
        "line": 2,
        "name": "@GLOBAL_NAVIGATION"
      }
    ]
  }
]`

After the build I get the following error:

`2016-11-30|16:25:02.375|INFO |d.b.c.s.r.CreateCucumberReport:Create Cucumber HTML report
2016-11-30|16:25:03.740|INFO |net.masterthought.cucumber.ReportParser:File 'target\cucumber\cucumber-report.json' contain 1 features
PANIC : Velocity cannot find any of the specified or default logging systems in the classpath, or the classpath doesn't contain the necessary classes to support them. Please consult the documentation regarding logging. Exception : java.lang.NoClassDefFoundError: org/apache/log/format/Formatter
PANIC : Velocity cannot find any of the specified or default logging systems in the classpath, or the classpath doesn't contain the necessary classes to support them. Please consult the documentation regarding logging. Exception : java.lang.NoClassDefFoundError: org/apache/log/format/Formatter
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/apache/log/format/Formatter
	at org.apache.velocity.runtime.log.LogManager.createLogSystem(LogManager.java:162)
	at org.apache.velocity.runtime.RuntimeInstance.initializeLogger(RuntimeInstance.java:553)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:226)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:461)
	at org.apache.velocity.app.VelocityEngine.init(VelocityEngine.java:106)
	at net.masterthought.cucumber.generators.AbstractPage.<init>(AbstractPage.java:49)
	at net.masterthought.cucumber.generators.FeaturesOverviewPage.<init>(FeaturesOverviewPage.java:12)
	at net.masterthought.cucumber.ReportBuilder.collectPages(ReportBuilder.java:125)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:79)
	at xxx.selenium.reporter.CreateCucumberReport.main(CreateCucumberReport.java:59)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.log.format.Formatter
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more`

If I run the main method directly, I get the following error:

`2016-11-30|16:34:47.488|INFO |d.b.c.s.r.CreateCucumberReport:Create Cucumber HTML report
2016-11-30|16:34:48.708|INFO |net.masterthought.cucumber.ReportParser:File 'target\cucumber\cucumber-report.json' contain 1 features
2016-11-30|16:34:48.947|INFO |net.masterthought.cucumber.ReportBuilder:org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource '/templates/headers.vm'
Exception in thread "main" org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource '/templates/headers.vm'
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:458)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:341)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:831)
	at org.apache.velocity.runtime.directive.Parse.render(Parse.java:141)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:114)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:230)
	at org.apache.velocity.Template.merge(Template.java:256)
	at net.masterthought.cucumber.generators.AbstractPage.generateReport(AbstractPage.java:70)
	at net.masterthought.cucumber.generators.AbstractPage.generatePage(AbstractPage.java:55)
	at net.masterthought.cucumber.ReportBuilder.generateErrorPage(ReportBuilder.java:197)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:86)
	at de.berenberg.clientportal.selenium.reporter.CreateCucumberReport.main(CreateCucumberReport.java:59)`

**Comment by Ryxmedia** [comment]
Fixed it and can be closed.
There was a dependency problem with: org.uncommons.reportng
Had to exclude "velocity" from that dependency and now it works.

**Comment by damianszczepanik** [comment]
Thanks for the clarification!

**Comment by kubecloudsinc** [comment]
yeah thanks @Ryxmedia helped me resolve an issue after 4 years 👍
