### ISSUE TITLE
Not able to merge the report from multiple JSONs of same feature

### ISSUE THREAD

**Issue by rajeshsharma05** [damianszczepanik/cucumber-reporting#577]
Hi Damian Szczepanik,

Thanks for the nice reporting plugin. It's really helpful. However i am facing a weird issue in my final reports if you can please help. Here is my problem statement:

I have used cucumber JVM parallel plugin: https://github.com/temyers/cucumber-jvm-parallel-plugin to run all my scenarios in parallel. This plugin generates multiple JSON files for each scenario in the feature file. 

I am using your maven-cucumber-reporting plugin to generate a final report for me. However in the Features tab this plugin is not able to merge the multiple JSON files (which are for a single feature) in one and give a me a single consolidated report i.e. show one line as "Feature XXX" for all scenarios run for the same feature, instead it shows multiple lines with same Feature which link to one scenario each. This works in Tag report tab where even if the same tag is part of separate json reports it shows only 1 line item for same tag say "@Tag1". I also tried using the setting "parallelTesting" as true, however it does not make any difference in this case.

Can you provide a fix or a work around for this please ?

Many thanks in advance,
Rajesh 

P.S. I have attached a screenshot as well which is showing a feature e..g Store Detail Page report in multiple line instead of a consolidated single row.

![pasted image at 2016_12_15 01_24 pm](https://cloud.githubusercontent.com/assets/18593962/21215996/698eeb2e-c2ca-11e6-8502-6312b2b15641.png)

**Comment by damianszczepanik** [comment]
From the report point of view it's hard to guess if you have the same features running on different devices or different features running on same device. That's why it treats each json file as independent result.

This is problem that happens not only to you but as long as I'm not able to add perfect improvement that has no regression I'm keeping current implementation.

**Comment by damianszczepanik** [comment]
Similar jenkinsci/cucumber-reports-plugin/pull/98

**Comment by guptaakhil** [comment]
is there any update related this issue , we are facing the same issue if it's got resolved please do let me know..
