### ISSUE TITLE
Use label for attachment files 

### ISSUE THREAD

**Issue by vveliev** [damianszczepanik/cucumber-reporting#582]
I believe as of today this is missing in the standard Cucumber Json formatter, but i don't see why not add it and make your reports more readable.

If embeddings will include label/title tag use it for naming attachment files rather than indexing them with ```Attachment #```

Ex:
```json
embeddings[{"mime_type":"image/png","lable":"Login_page_HTML","data":"iVBORw0KGgoAAAANSUhEUgAAB2wAAAPdCAYAAABGI5gD"}]
``` 
![new_report](https://cloud.githubusercontent.com/assets/5420655/21458816/9550a57a-c907-11e6-84b9-d90ae758939b.png)

I have added it in my code and it's working just fine I can also provide example json file.

[https://github.com/cucumber/cucumber-ruby/issues/1066](https://github.com/cucumber/cucumber-ruby/issues/1066)

**Comment by damianszczepanik** [comment]
Won't be supported as long as JSON report won't officially support it.
