### ISSUE TITLE
Enhancement: Append scenario.write(...) output in Report

### ISSUE THREAD

**Issue by mschwehl** [damianszczepanik/cucumber-reporting#587]
Hello everyone,

I love this plugin but one feature is missing. In a step i create a new user with the user-id.
The user-Id is written with scenario.write(userid)

in json there is a new section

            "output": [
              "UserID:123"
            ]

It would be great if the report show it 

Feature -> some Feature -> Scenario -> Steps -> 'When user is created'

here in this step e.g. a dropdown that displays the scenario.write() output

greetings martin

**Comment by damianszczepanik** [comment]
It should work. Show me json file

**Comment by mschwehl** [comment]
I tested again and it worked as expected.  

May help this for anyone that dont' know this feature :-)

Best regards
