### ISSUE TITLE
NewLine Characters In Json File Not Been Respected In HTML Report

### ISSUE THREAD

**Issue by bhreinb** [damianszczepanik/cucumber-reporting#588]
Hi There,

I submitting a minor issue which I hope you can help resolve.

I have the following JSON file 

[cucumber.zip](https://github.com/damianszczepanik/cucumber-reporting/files/689747/cucumber.zip)

their is three description items in the file

(Top Level -> EPIC Level)
"description": "  Epic Requirement:\n  TEST-3029 -> http://sdlc.devcentral.equifax.com/jira/browse/TEST-3029",

(Test Scenario 1 -> Individual PBIs/Bugs)
"description": "  PBI/Bug Requirement:\n  TEST-467 -> http://sdlc.devcentral.equifax.com/jira/browse/TEST-467",

(Test Scenario 2 -> Individual PBIs/Bugs)
"description": "  PBI/BUG Requirement:\n  TEST-3276 -> http://sdlc.devcentral.equifax.com/jira/browse/TEST-3276",

This in turn generates the following report

![reportgenerated](https://cloud.githubusercontent.com/assets/20628685/21716473/9d75011e-d402-11e6-8a8d-299ca4fc7d18.png)

It would be great in the report if the '\n' characters in the JSON are respected and actually generate a new line. We use the reports to show to BAs\Product owners so would be great if this could be added as it is easier to show tractability of business requirements etc. We can still do this in its current form but it would be nicer with this feature request added.

Thoughts? Many thanks in advance.

**Comment by mpkorstanje** [comment]
This may have been resolved in #560 already.

**Comment by bhreinb** [comment]
Hi @mpkorstanje I just the latest edition released last night and you are correct this is resolved in that version. I should have checked the new version before submitting this issue. I'm going to close this ticket and thanks for responding to this. All the best.
