### ISSUE TITLE
Text in "Error message" blocks is not being HTML-escaped

### ISSUE THREAD

**Issue by mrec** [damianszczepanik/cucumber-reporting#596]
Had a head-scratching moment today when a query URL reported in that block as failing worked fine when run directly. Turns out the URL was something like 

`http://example.com?arg='<foo></foo>'`

which shows up in the HTML report as 

`http://example.com?arg=''`

since HTML ignores unknown tags. Depending on where your test inputs are coming from this might also be an XSS vulnerability; I haven't tried.

Gradle version is `net.masterthought:cucumber-reporting:2.7.0`

**Comment by mpkorstanje** [comment]
This has been fixed in version 3.4.0 with #576 and #584.

**Comment by mrec** [comment]
Was there ever a 2-to-3 migration guide when 3 came out? I tried upgrading to 3.4.0 last night and a bunch of APIs we were calling have vanished without trace.

**Comment by damianszczepanik** [comment]
API has changed but not much. You can refer to readme file to chech how you should use it now.
