### ISSUE TITLE
Multiple Cucumber Runner classes - report only showing results for one of them

### ISSUE THREAD

**Issue by AshTappin** [damianszczepanik/cucumber-reporting#600]
Hello, 

I am not sure if this is a proper issue, but if in my project I had two cucumber classes:

`@RunWith(Cucumber.class)
@CucumberOptions(features = "path/to/feature-group-one")
public class RunnerOneIT
`

and 

`@RunWith(Cucumber.class)
@CucumberOptions(features = "path/to/feature-group-two")
public class RunnerTwoIT
`

When I build the project via maven, the tests run and the report gets generated. However it only shows the test results for feature files which get executed by RunnerTwoIT. If I @Ignore'd RunnerTwoIT, then the results for RunnerOneIT are shown. 

Am I right in thinking the plugin only assumes that you have one runner per project? In my project I had two distinct groups of features so it made sense to have two different runners.

I can provide more information if needed.

**Comment by damianszczepanik** [comment]
From the report point of view it does not matter how much runners you have. It takes json report as the input and process it.
