### ISSUE TITLE
Pending or Skipped status missing for scenario and feature

### ISSUE THREAD

**Issue by TimJD82** [damianszczepanik/cucumber-reporting#601]
When a scenario has pending  or skipped steps, the scenario and the feature are marked as failed in the html report, while no steps actually failed. This is not what I would expect as JUnit reports overall status as 'passed'. I would like to differentiate in the report between features/scenarios that failed or those that have pending steps.

**Comment by damianszczepanik** [comment]
Scenarios don't have other than pass/failed status. Only steps have.
