### ISSUE TITLE
Support following mimetype -  "image/gif" to be Embeded in the scenario

### ISSUE THREAD

**Issue by abhisheksreepal** [damianszczepanik/cucumber-reporting#602]
This is to enable animated gif to be embedded in the reports

**Comment by mpkorstanje** [comment]
You should write a pull request  that enables this.

**Comment by damianszczepanik** [comment]
Take a look at reference #551 and prepare PR so I will kindly merge it

**Comment by abhisheksreepal** [comment]
@damianszczepanik Created PR. Please review!
https://github.com/damianszczepanik/cucumber-reporting/pull/605

**Comment by damianszczepanik** [comment]
Merged, thanks!
