### ISSUE TITLE
how to merge 2 different html reports for different feature files ?

### ISSUE THREAD

**Issue by deepnirmal** [damianszczepanik/cucumber-reporting#606]
Is it possible to merge different html files into a single html file for different features ?
report-feature_file1-feature.html
report-feature_file2-feature.html ...together as report-feature.html

![image](https://cloud.githubusercontent.com/assets/11058925/23060336/4c2f8af8-f523-11e6-85d7-68121056e3ff.png)

**Comment by damianszczepanik** [comment]
https://github.com/jenkinsci/cucumber-reports-plugin/pull/98
