### ISSUE TITLE
Feature Duration not matching sum of steps duration

### ISSUE THREAD

**Issue by npgarcia** [damianszczepanik/cucumber-reporting#607]
I realized today that the feature duration time does not match the duration of the scenarios (which is the sum of steps, right?)

This is the example of a Feature duration:
![image](https://cloud.githubusercontent.com/assets/7768581/23676073/7a0b117a-0349-11e7-9498-a7c472e36f0e.png)

This feature has 4 scenarios:
Scenario 1
![image](https://cloud.githubusercontent.com/assets/7768581/23676110/9ff861b2-0349-11e7-8c17-1bcd35fad13c.png)

Scenario 2
![image](https://cloud.githubusercontent.com/assets/7768581/23676127/b0a42e10-0349-11e7-8dc8-17118cefe841.png)

Scenario 3
![image](https://cloud.githubusercontent.com/assets/7768581/23676159/c4347e44-0349-11e7-91b9-58e45247a8fa.png)

Scenario 4
![image](https://cloud.githubusercontent.com/assets/7768581/23676192/e191d6f8-0349-11e7-93a2-4bacf9d8db09.png)

Please note that the time of the scenarios does not match the time of the Feature. I am wondering if there is something else added to the feature time? Does it makes sense to make it only the duration of that specific feature ?

**Comment by damianszczepanik** [comment]
Attach json file

**Comment by mpkorstanje** [comment]
I'm seeing about 10 to 11 minutes in the listed times and not seeing all steps expanded in Scenario 1.

**Comment by npgarcia** [comment]
Yeah, you are probably right @mpkorstanje . 
I did not noticed some of the steps at the end that seems to be taking a lot of time.
So to make the report more clear, is it possible to have the duration of a scenario? I can change the name of the issue.

Here is a zipped json from other feature which I believe that the time does not add up, but might be wrong; the feature shared got destroyed in my last round of test.

[cucumber-regression-breadcrumbs.json.zip](https://github.com/damianszczepanik/cucumber-reporting/files/825846/cucumber-regression-breadcrumbs.json.zip)

**Comment by mpkorstanje** [comment]
@npgarcia If you implement the changes and create a pull request that should certainly be possible. Have a look at element.vm
