### ISSUE TITLE
Getting "Unable to find resource 'templates/errorPage.vm'" when trying to generate Cucumber Report

### ISSUE THREAD

**Issue by SWAR210A** [damianszczepanik/cucumber-reporting#608]
Hellos,

While trying to generated Cucumber reports we are getting the below mentioned exception:

E:\RunSVeetCucumber\jenkins\.jenkins\jobs\SP_OUT\builds\130\cucumber-html-reports
[CucumberReportPublisher] Found the following number of json files: 1
[CucumberReportPublisher] 0. Found a json file: sveetc_mtnsa_sitcr.json
[CucumberReportPublisher] Generating HTML reports
[CucumberReportPublisher] there was an error generating the reports: org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'templates/errorPage.vm'
org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
org.apache.velocity.run
time.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1514)
org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:373)
net.masterthought.cucumber.ReportBuilder.generateErrorPage(ReportBuilder.java:224)
net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:96)
net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:110)
hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
hudson.model.Build$BuildExecution.post2(Build.java:186)
hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
hudson.model.Run.execute(Run.java:1753)
hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
hudson.model.ResourceController.execute(ResourceController.java:98)
hudson.model.Executor.run(Executor.java:405)
Build step 'Publish cucumber results as a report' changed build result to FAILURE

**Requesting assistance to overcome this issue.
Could not attach the JSON file hence i have added the JSON content into text file and attached it to this issue.**

[CucumberJSONContent.txt](https://github.com/damianszczepanik/cucumber-reporting/files/833667/CucumberJSONContent.txt)

**Comment by damianszczepanik** [comment]
Something wrong with your local workspace or configuration
