### ISSUE TITLE
File not found exception : cucumber.json (No such file or directory)

### ISSUE THREAD

**Issue by rajesh825** [damianszczepanik/cucumber-reporting#61]
Hello,

I'm seeing following error, on trying to run cucumber tests using cucumber-reporting.

[INFO] --- maven-cucumber-reporting:0.0.5:generate (execution) @ mygovscot_alpha ---
About to generate
java.io.FileNotFoundException: /Users/IdeaProjects/projectalpha/target/cucumber.json (No such file or directory)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.252 s
[INFO] Finished at: 2014-05-29T13:18:22+00:00
[INFO] Final Memory: 20M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.masterthought:maven-cucumber-reporting:0.0.5:generate (execution) on project project_alpha: Error Found: NullPointerException -> [Help 1]
[ERROR] 

I've following settings in pom.xml.  

    <repositories>
        <repository>
            <id>repo.bodar.com</id>
            <url>http://repo.bodar.com</url>
        </repository>

        <repository>
            <id>sonatype-releases</id>
            <url>https://oss.sonatype.org/content/repositories/releases/</url>
        </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                 <version>2.16</version>
                 <configuration>
                     <testFailureIgnore>true</testFailureIgnore>
                 </configuration>
             </plugin>
             <plugin>
                <groupId>net.masterthought</groupId>
                 <artifactId>maven-cucumber-reporting</artifactId>
                 <version>${maven.cucumber.reporting.version}</version>
                 <executions>
                    <execution>
                        <id>execution</id>
                         <phase>verify</phase>
                        <goals>
                             <goal>generate</goal>
                         </goals>
                         <configuration>
                             <projectName>${project.name}</projectName>
                             <outputDirectory>${project.build.directory}/cucumber-html-reports</outputDirectory>
                             <cucumberOutput>${project.build.directory}/cucumber.json</cucumberOutput>
                             <enableFlashCharts>true</enableFlashCharts>
                         </configuration>
                     </execution>
                 </executions>
             </plugin>
         </plugins>
     </build>

Following dependencies are included in pom.xml.

 

        <dependency>
            <groupId>net.masterthought</groupId>
            <artifactId>maven-cucumber-reporting</artifactId>
            <version>${maven.cucumber.reporting.version}</version>
        </dependency>

        <dependency>
            <groupId>net.masterthought</groupId>
            <artifactId>cucumber-reporting</artifactId>
            <version>${cucumber.reporting.version}</version>
        </dependency>

        <dependency>
            <groupId>com.googlecode.totallylazy</groupId>
            <artifactId>totallylazy</artifactId>
            <version>1077</version>
        </dependency>

        <dependency>
            <groupId>com.beust</groupId>
            <artifactId>jcommander</artifactId>
            <version>1.25</version>
        </dependency>

           <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>${org.hamcrest.hamcrest-all}</version>
           </dependency>

Could you please advise, if any one had seen this issue before. I've not configured any json file, please advise if any json file need to be configured to use this plugin.

I did search in the net to find similar issues, can't find any such & Not able to post any queries in cucumber-reporting user group.  Apologies if this is not real issue, just need change in configuration.

if so, Kindly could you advise on configuration changes to fix this issue. 

Thanks,
Raja

**Comment by frol2103** [comment]
I had the same issue, fixed it by adding  "json:target/cucumber.json" in : 
@CucumberOptions(plugin = {"pretty","html:target/html", "json:target/cucumber.json"})

Feel free to ask for a more complete answer

**Comment by damianszczepanik** [comment]
Cucuumber-jwm problem, not the cucumber-reports
