### ISSUE TITLE
Classifications should not be escaped

### ISSUE THREAD

**Issue by damianszczepanik** [damianszczepanik/cucumber-reporting#612]
Classifications should not be HTML escaped so I can pass HTML code such as hyperlink from Jenkins to the report and display direct link to the repository, task or other external system

@mpkorstanje Can you work on this?

**Comment by mpkorstanje** [comment]
Certainly. In #613 we sanitize the input but allow hyperlinks. 

Though I think you may want to extend this with url detection so url like values in the value are also turned into urls.
