### ISSUE TITLE
In my project I have multiple .json files for capabilities. But after execution, cucumber jvm report could not able to generate.

### ISSUE THREAD

**Issue by EBtransversal** [damianszczepanik/cucumber-reporting#625]
I am using cucumber jvm report in my jenkins.
and below are the logs.

14:30:58 [CucumberReportPublisher] Found 8 json files.
14:30:58 [CucumberReportPublisher] 1. Found a json file: **grid/capabilities/device1.json**
14:30:58 [CucumberReportPublisher] 2. Found a json file: **grid/capabilities/device2.json**
14:30:58 [CucumberReportPublisher] 3. Found a json file: **grid/capabilities/device3.json**
14:30:58 [CucumberReportPublisher] 4. Found a json file: **grid/capabilities/device4.json**
14:30:58 [CucumberReportPublisher] 5. Found a json file: **grid/capabilities/device5.json**
14:30:58 [CucumberReportPublisher] 6. Found a json file: **grid/capabilities/device6.json**
14:30:58 [CucumberReportPublisher] 7. Found a json file: result/Grid_Execution/Cucumber_Report/HTML_Reports/**web_test1.json**
14:30:58 [CucumberReportPublisher] 8. Found a json file: result/Grid_Execution/Cucumber_Report/HTML_Reports/**web_test2.json**
14:30:58 [CucumberReportPublisher] Generating HTML reports
14:30:58 Build step 'Cucumber-jvm reports' changed build result to FAILURE

**Comment by damianszczepanik** [comment]
Attach json files

**Comment by damianszczepanik** [comment]
I'm not sure if you understand the goal of this project. If so please reply for previous comment

**Comment by EBtransversal** [comment]
No I shared my thought that is it..
is there any other way to say to cucumber_jvm_report that where is the pretty json output.

**Comment by mpkorstanje** [comment]
Assuming you are using Jenkins, you can use the file include pattern:

https://github.com/jenkinsci/cucumber-reports-plugin/wiki/Detailed-Configuration#2-cucumber-jvm---open-the-configuration-page-for-your-job
