### ISSUE TITLE
Skipped steps leads to failed scenario 

### ISSUE THREAD

**Issue by lbovet** [damianszczepanik/cucumber-reporting#629]
When a single step is skipped, the scenario (and feature) is rendered as failiing.
Would it not be correct to allow skipped steps in a scenario? (e.g. via a configuration flag)

**Comment by damianszczepanik** [comment]
You can configure final result but this case is implemented by design

**Comment by lbovet** [comment]
"You can configure final result", you mean it is already possible to consider skipped tests as non-failing?

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/ReportResult.java#L64

**Comment by lbovet** [comment]
Would you accept a PR allowing to specify in the Configuration which statuses are considered as success? Default would be as it is today (only passed).
Additionally, this should be checkbox-configurable in the jenkins plugin as well. (another PR in jenkins plugin project).

**Comment by damianszczepanik** [comment]
I'm not hap[y about it because the PR you are talking about is the way how old cucumber was working and it was quite confusing for users. Tell me how would you like to manager not passing statuses that should be marked as passing?
