### ISSUE TITLE
Any way to not show Before and After method in the reports? 

### ISSUE THREAD

**Issue by reach2jeyan** [damianszczepanik/cucumber-reporting#630]
I use `hooks.rb` to have some `before` and `After` conditions like if a scenario fails, grab and embed screenshots and logs. Also, before starting a scenario, change the device locale.

These are appearing in the reports and disturbs the whole UI. I just want the screenshot appearing just below my feature file, below the step it has failed. Currently, I have to click an other tab called `After` in the reports, which I dont want to.

Any idea how to ? I don't find much help online on the customisation.

**Comment by damianszczepanik** [comment]
Hooks are closed as long as they are passing and I don't have plan for additional feature about it as most uses don't complain about it
