### ISSUE TITLE
velocity logging excessive

### ISSUE THREAD

**Issue by msillence** [damianszczepanik/cucumber-reporting#631]
Hi,

Not quite sure if this is the right forum but.
I can't find a way to configure the velocity logging and it seems to be causing sever performance issues.

Thanks
M

**Comment by damianszczepanik** [comment]
It is not

**Comment by msillence** [comment]
Where would be more appropriate for this question?
I maybe should have said that this is causing problems when generating the cucumber report...
The reports are taking a very long time to generate and when profiling it all seems to be in logging

**Comment by mpkorstanje** [comment]
You didn't provide that many details on the how of it.

Ensure the following file is on your class path: 

**velocity.properties**
```
runtime.log.logsystem.class = org.apache.velocity.runtime.log.NullLogSystem
```

**Comment by msillence** [comment]
Thanks, the bit I was missing is this file seems to have to be in the package: 
org/apache/velocity/runtime/defaults/velocity.properties

Performance initially looks a lot better thanks
