### ISSUE TITLE
cucumber html report generate after fails scenario but console output shows BUILD SUCCESS even after some scenario fails 

### ISSUE THREAD

**Issue by shohilbagdai** [damianszczepanik/cucumber-reporting#634]
I have added this to pom.xml
< groupId>org.apache.maven.plugins< /groupId>
< artifactId>maven-surefire-plugin< /artifactId>
< version>2.19.1< /version>
< configuration >
< testFailureIgnore>true< /testFailureIgnore>

and its generating report now but just found out something that its giving me buils uccess notification even after scenario fails

Tests run: 29, Failures: 2, Errors: 0, Skipped: 0

[ERROR] There are test failures.

Please refer to C:\Users******************\admin\target\surefire-reports for the individual test results.
[INFO]
[INFO] --- maven-cucumber-reporting:3.7.0:generate (execution) @ admin ---
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
[INFO] About to generate Cucumber report.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:31 min
[INFO] Finished at: 2017-05-25T14:42:20+01:00
[INFO] Final Memory: 40M/621M
[INFO] ------------------------------------------------------------------------

does any one face same issue?
has anyone know the sollution?

**Comment by damianszczepanik** [comment]
You can configure this, check readme with example
