### ISSUE TITLE
maven verify step fails

### ISSUE THREAD

**Issue by msillence** [damianszczepanik/cucumber-reporting#635]
Various tests seem to fail whilst trying to read the json report
They seem to be writing to the reports folder while another test is deleting the report folder
The verify step seems to run tests in parallel

```
        at net.masterthought.cucumber.json.TagTest.setUp(TagTest.java:18)
Caused by: net.masterthought.cucumber.ValidationException: java.nio.file.NoSuchFileException: ...target\test-classes\cucumber-html-reports\embeddings\embedding_-115657502.image
```

**Comment by damianszczepanik** [comment]
Show me JSON files

**Comment by msillence** [comment]
Steps to reproduce:

- check out project
- run:

`mvn verify`

problem json file:
https://github.com/damianszczepanik/cucumber-reporting/tree/master/src/cucumber-reporting\target\test-classes\json/sample.json

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/maven-cucumber-reporting should solve the problem
