### ISSUE TITLE
Parse and store "arguments", "line" & "comments"

### ISSUE THREAD

**Issue by slaout** [damianszczepanik/cucumber-reporting#638]
I depend on your library, so I can parse report.json: all classes to map to Java Beans are already created.

Would you mind to add "arguments", "line" & "comments" to the java bean objects?

For instance, this part of JSON:

        "steps": [
          {
            "line": 8,
            "match": {
              "arguments": [
                {
                  "val": "MyArg",
                  "offset": 50
                },
                {
                  "val": "42",
                  "offset": 65
                }
              ],

**Comment by damianszczepanik** [comment]
As long as this is not supported by Cucumber I will not support it. You can make fork and maintain your version
