### ISSUE TITLE
Reset Trend Statistic Build Number

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [damianszczepanik/cucumber-reporting#640]
I have one job in Jenkins with more than 253 builds and I would like to show the last 20. 

How can I reset this or set a parameter ?

**Comment by damianszczepanik** [comment]
You can configure how many records is presented

https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/Configuration.java#L91
