### ISSUE TITLE
Match class is missing arguments property

### ISSUE THREAD

**Issue by dbhaisota** [damianszczepanik/cucumber-reporting#643]
Hi,
In my project i have requirement to capture in line parameter given in step like below -
I enter <name> for in field <fieldName>

Cucumber produced json file provide "match" block inside "step". And inside "match" block "arguments" block is present. But in this API we are missing property inside Match class.

I need this parameters to be reported in customized excel report. If you can provide this then it would be so helpful.

Thanks,
Deepak

**Comment by damianszczepanik** [comment]
I have no idea what do you need, sorry
