### ISSUE TITLE
Customizable css

### ISSUE THREAD

**Issue by flowerrrr** [damianszczepanik/cucumber-reporting#649]
Hello,

our cucumber reports would greatly benefit from the possibility to fine-tune the css of the generated reports. 

We would need to assign a monospaced font-family to the css class **.description** from cucumber.css because the current rendering kind of destroys our scenario description which requires correct spacing to look OK.

Are there ways to customize the css?

Kind regards,

Oliver

**Comment by damianszczepanik** [comment]
There is no way to customize CSS but instead you can send pull request so if this is general improvement I would like to merge it and publish for everyone
