### ISSUE TITLE
No undefined, skipped and pending status for scenarios

### ISSUE THREAD

**Issue by tracylucky** [damianszczepanik/cucumber-reporting#65]
In cucumber framework, when one of steps is pending or undefined, the scenario will be marked as pending or undefined; when all steps are skipped, then the scenario will be marked as skipped, but in cucumber-reporting, no matter scenario is pending, undefined or skipped, it is always marked as failed. I have attached a simple json report, could someone help me? Thanks in advance
[
  {
    "keyword": "Feature",
    "name": "As a user",
    "line": 1,
    "description": " I want to know\n how scenario will show it's status",
    "id": "as-a-user",
    "uri": "features\\status_test.feature",
    "elements": [
      {
        "keyword": "Scenario",
        "name": "Varify undefined status",
        "line": 6,
        "description": "",
        "id": "as-a-user;varify-undefined-status",
        "type": "scenario",
        "steps": [
          {
            "keyword": "Given ",
            "name": "I have a step which is undefined",
            "line": 7,
            "match": {
              "location": "features\\status_test.feature:7"
            },
            "result": {
              "status": "undefined",
              "duration": 1000000
            }
          },
          {
            "keyword": "Then ",
            "name": "the scenario should be undefined",
            "line": 8,
            "match": {
              "location": "features\\status_test.feature:8"
            },
            "result": {
              "status": "undefined",
              "duration": 1000000
            }
          }
        ]
      },
      {
        "keyword": "Scenario",
        "name": "Varify pending status",
        "line": 10,
        "description": "",
        "id": "as-a-user;varify-pending-status",
        "type": "scenario",
        "steps": [
          {
            "keyword": "Given ",
            "name": "I have had a step which is pending",
            "line": 11,
            "match": {
              "location": "features/step_definition/status_steps.rb:16"
            },
            "result": {
              "status": "pending",
              "error_message": "TODO (Cucumber::Pending)\n./features/step_definition/status_steps.rb:17:in `/^I have had a step which is pending$/'\nfeatures\\status_test.feature:11:in `Given I have had a step which is pending'",
              "duration": 4000000
            }
          },
          {
            "keyword": "Then ",
            "name": "the scenario's status should be pending",
            "line": 12,
            "match": {
              "location": "features/step_definition/status_steps.rb:20"
            },
            "result": {
              "status": "skipped",
              "duration": 2000000
            }
          }
        ]
      }
    ]
  }
]

**Comment by damianszczepanik** [comment]
It's fixed with recent release.
