### ISSUE TITLE
Only one device

### ISSUE THREAD

**Issue by fdPoornima** [damianszczepanik/cucumber-reporting#651]
Hello.. Thank you for the wonderful report. However, while I am trying to use it, I am getting only one of my devices listed on the device tab in the overview-features report. I am using cucumber with Appium and I have parallel execution with multiple devices. Different jsons are getting created as expected, however, the overview-features lists only one device and I get only one html report for the device. What could I be doing wrong here? Would appreciate any help

**Comment by damianszczepanik** [comment]
Have you enabled parallel testing via configuration?

**Comment by fdPoornima** [comment]
I found the solution. Just gave the folder in the cucumber output in
pom.xml and it worked for me. I had enabled parellel testing .


Appreciate your quick response .

Regards,
Poornima

On Fri, Aug 11, 2017 at 9:53 AM, Damian Szczepanik <notifications@github.com

**Comment by fdPoornima** [comment]
closed as the solution was received

**Comment by LerryAlexander** [comment]
> I found the solution. Just gave the folder in the cucumber output in pom.xml and it worked for me. I had enabled parellel testing . Appreciate your quick response . Regards, Poornima
> […](#)

Hi! please, could you share with me your pom.xml file? I'm trying to do the same thing in my project
