### ISSUE TITLE
Parallel execution stores only last run data

### ISSUE THREAD

**Issue by DeChrish** [damianszczepanik/cucumber-reporting#652]
We are using mvn to trigger parallel tests using multiple test runner.
After each execution, last execution data is stored wiping out previous scenario test results.
How to append test results while doing parallel execution?

**Comment by damianszczepanik** [comment]
Tell me more about this problem

**Comment by laxersaz** [comment]
If you use the cucumber-reporting maven plugin, it works fine because it combines the json files from each run into one report.

**Comment by DeChrish** [comment]
@damianszczepanik @laxersaz  i was using same report name. closing the issue.
