### ISSUE TITLE
Extraneous closing span tag

### ISSUE THREAD

**Issue by racdev** [damianszczepanik/cucumber-reporting#653]
https://github.com/damianszczepanik/cucumber-reporting/blob/83fd179387fab30de3c74fe078d2445a5d8a53a9/src/main/resources/templates/generators/overviewFeatures.vm#L51

There is an extraneous closing span tag here that isn't valid HTML. Not a big problem in the grand scheme of things, however for our use case it is a problem.

We have a small utility app that parses cucumber reports as XML so that we can Xpath various bits of data to generate top level reports over multiple tests. 

This closing span makes the HTML also invalid XML, so we cant parse it.

**Comment by damianszczepanik** [comment]
Thanks, will be released soon
