### ISSUE TITLE
Pending scenarios are considered failed

### ISSUE THREAD

**Issue by laxersaz** [damianszczepanik/cucumber-reporting#654]
Hello Damian,

I noticed that when scenarios are pending, they are marked as failed in the cucumber-reporting reports. In my opinion, this should be configurable like in Cucumber itself (strict true vs false).
In our case this generates false results.
If you agree, I can certainly create a pull request for your project and change it.

All the best,
Benjamin

**Comment by droca-adaptive** [comment]
That's a feature that I would want to see implemented. +1

**Comment by laxersaz** [comment]
Just saw that this is already in this PR:
https://github.com/damianszczepanik/cucumber-reporting/pull/636

**Comment by damianszczepanik** [comment]
Duplicate of https://github.com/damianszczepanik/cucumber-reporting/pull/636
