### ISSUE TITLE
Include output in Hooks

### ISSUE THREAD

**Issue by fmarmar** [damianszczepanik/cucumber-reporting#656]
output node from hooks is not included in report.

**Comment by damianszczepanik** [comment]
Show me JSON file

**Comment by fmarmar** [comment]
Sorry, here it goes. 

I realized that the reporter doesn't process step hooks so even the json file contemplate the case for step hooks the issue should focus in the scenario hooks.


[simple.txt](https://github.com/damianszczepanik/cucumber-reporting/files/1266978/simple.txt)

**Comment by damianszczepanik** [comment]
What cucumber implementation are you using?

**Comment by fmarmar** [comment]
The cucumber implementation is ruby. Why do you ask?

**Comment by bajpaip1** [comment]
Hi,
As per my finding this issue also exists with cucumber java. This issue arise when we update cucumber version to 2.0.1.
Reason:- New cucumber version writes output field in JSON under the section after if Scenario.write(..) is called in after hook, so if its in after method it will add in after section of JSON, which was not the case with earlier cucumber . Earlier cucumber version used to write output field in step section whether its called from after hook or not, this is where reporting problem starts, output field is present in Step class to map with JSON when we convert JSON to object, and in new cucumber its written in after section which is mapped to Hook class, so ideally Hook class should have some output field to map the data. That is why we are not able to see anything in report which is written using Scenario.write(..) in after method.

[TestRunner.txt](https://github.com/damianszczepanik/cucumber-reporting/files/1411877/TestRunner.txt)

**Comment by damianszczepanik** [comment]
Different implementations cause some problem with maintain but anyway I should update deserializer and add support for this!

**Comment by bajpaip1** [comment]
Hi,
Just in curiosity want to check, when are you planning to have next release with this change?

**Comment by pavelpp** [comment]
Hi, yes I'd really like to see this supported. Can't output relevant info in case scenario fails.

**Comment by damianszczepanik** [comment]
Support added, will be released soon
