### ISSUE TITLE
Report does not update status after scenario re-run?

### ISSUE THREAD

**Issue by reach2jeyan** [damianszczepanik/cucumber-reporting#659]
I have a suite of tests that runs in the Jenkins, and the second time, cucumber runs the failed tests again on an attempt to eliminate the intermittent failures.

A lot of tests passes in the second attempt, but the cucumber reports, does not update the status of the re-run test in the report.

Any idea, if I have to do a seperate configuration for this? I am not able to find anything about it on any documentations.

I am using this command for re-running the scenarios
`cucumber --tags @Database --format json --out report.json --format pretty -f rerun --out rerun.txt || cucumber @rerun.txt`

I see that the tests in the reports marked as pass in the re-run, but the summarized report marks them as fail.

First run = 5 total test, 3 pass , 2 fail
Second run = 2 tests, 2 pass

Summarized report = 7 tests , 2 fail . TESTS FAILED.

**Comment by fmarmar** [comment]
Hi, 

This tool gets a bunch of cucumber reports in json format an aggregates them in a single html report, so its works as expected.

As I understand correctly, what you need is to merge the reports. We have a similar use case and I made a little tool to merge two cucumber reports in a single one.  It will be interesting to integrate this functionality.

**Comment by reach2jeyan** [comment]
@fmarmar Thanks for getting back. I get it.
Is there a work around script currently, to validate the re-runs and have them merged?

**Comment by damianszczepanik** [comment]
Report displays what you pass as the input. If you want to merge JSONs into single file you need to apply this in advance using rules you like.
