### ISSUE TITLE
Trends not scaling properly

### ISSUE THREAD

**Issue by PascalGit1** [damianszczepanik/cucumber-reporting#661]
I'm using these reports in Jenkins for my cucumber test and i'm really loving it.
Now I'm not sure if this is an actual issues but the trends tab doesn't seem to scale properly by the amount of tests ran and amount of scenario's and it becomes almost unreadable:

![135gsers231](https://user-images.githubusercontent.com/22746723/29973644-972aea1e-8f30-11e7-930a-80bc85600a9f.png)

Similair problem at the tags tab:

![135gsers231](https://user-images.githubusercontent.com/22746723/29973773-fbfc7354-8f30-11e7-9eba-35a221b19b67.png)

Is there a way to change the scaling manually?

**Comment by damianszczepanik** [comment]
Yes, there is some limitation if you want to display long trends history but I did not investigate it.
