### ISSUE TITLE
Failure on number-looking buildNumber that is not an int

### ISSUE THREAD

**Issue by melon3r** [damianszczepanik/cucumber-reporting#666]
My build numbers look like "20170919.3", which is a valid number (a float), which makes `NumberUtils.isCreatable(buildNumber)` return `true` in AbstractPage's `buildGeneralParameters`, but then it's treated as an int in `Integer.parseInt(buildNumber)`, making it fail with an exception.

I'd make a PR to add a try&catch block around `parseInt`, but I don't know the code to tell if that'd break anything.

**Comment by damianszczepanik** [comment]
How it is possible that build is numbered as float and not number?

**Comment by melon3r** [comment]
It's actually a valid number, according to `NumberUtils.isCreatable(buildNumber)`. But it's then treated as an Integer, which it isn't. See:

https://github.com/damianszczepanik/cucumber-reporting/blob/11c8c240c37ea73067fe0f7d1cc3ccbb938c01dd/src/main/java/net/masterthought/cucumber/generators/AbstractPage.java#L110-L118

**Comment by melon3r** [comment]
I'd propose something like:
```java
 // build number is not mandatory 
 String buildNumber = configuration.getBuildNumber(); 
 if (buildNumber != null) { 
     try { 
         context.put("build_previous_number", Integer.parseInt(buildNumber) - 1); 
     } catch (NumberFormatException e) { 
         LOG.info("Could not parse build number: {}.", configuration.getBuildNumber()); 
     } 
} 
```

**Comment by damianszczepanik** [comment]
Build number comes from http://javadoc.jenkins-ci.org/hudson/model/Run.html#getNumber-- which is int value. How did you get the float then?

**Comment by melon3r** [comment]
I'm not using Jenkins. I'm setting the buildNumber through gradle, and it looks like [date].[counter].

This is my code:
```groovy
def config = new XmlSlurper().parse(file('config.xml'))
if(config.projectName == null) {
    throw new InvalidUserDataException('Missing value in config.xml: \"projectName\"!')
}

if(config.buildNumber == null) {
    throw new InvalidUserDataException('Missing value in config.xml: \"buildNumber\"!')
}

boolean runWithJenkins = false
boolean parallelTesting = false

net.masterthought.cucumber.Configuration configuration = new net.masterthought.cucumber.Configuration(reportOutputDirectory, config.projectName.toString())

configuration.setParallelTesting(parallelTesting)
configuration.setRunWithJenkins(runWithJenkins)
configuration.setBuildNumber(config.buildNumber.toString())
ReportBuilder reportBuilder = new ReportBuilder(jsonReportFiles, configuration)
reportBuilder.generateReports()
```

**Comment by damianszczepanik** [comment]
This is interesting case. What then do you expect to have as the previous build? It could not be calculated automatically.

**Comment by melon3r** [comment]
Nothing at all really, as it's only used when `runWithJenkins` is `true`, and in my case it's false. Also, 
I store reports separately, and so navigating them wouldn't work.

https://github.com/damianszczepanik/cucumber-reporting/blob/d05232535cbf5638b211e9b6d5349d996fab6779/src/main/resources/templates/macros/page/navigation.vm#L7-L13

Maybe this code should check if it's running with Jenkins:
```java
if (configuration.isRunWithJenkins()) {
    // build number is not mandatory
    String buildNumber = configuration.getBuildNumber();
    if (buildNumber != null) {
        if (NumberUtils.isCreatable(buildNumber)) {
            context.put("build_previous_number", Integer.parseInt(buildNumber) - 1);
        } else {
            LOG.info("Could not parse build number: {}.", configuration.getBuildNumber());
        }
    }
}
```

**Comment by damianszczepanik** [comment]
Now if you set `setRunWithJenkins` to false, you can pass any string you like. It will be displayed at the top table as the build number but won't be parsed for previous build.

**Comment by melon3r** [comment]
Thank you @damianszczepanik :) When can I expect a new release?

**Comment by damianszczepanik** [comment]
Very 4-6 weeks. But if you now set runWithJenkins to false it should work fine
