### ISSUE TITLE
cucumber jvm embedded image not shown/attached to report

### ISSUE THREAD

**Issue by a1dutch** [damianszczepanik/cucumber-reporting#668]
Hi
Im using cucumber jvm 2.0.1 & selenium 3.6.0 and my embedded screenshots are not getting attached to the report, i think the difference/problem is that https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/resources/json/sample.json has `embeddings` and in my json file they are under `embedding` so are not getting parsed correctly.

Not sure if this should be reported here, cucumber or selenium.

Cheers

Andy

**Comment by a1dutch** [comment]
just found this is anyone has hit the same problem https://github.com/cucumber/cucumber-jvm/issues/1235

**Comment by damianszczepanik** [comment]
Let's wait for their feedback. I can implement additional https://github.com/damianszczepanik/cucumber-reporting/tree/master/src/main/java/net/masterthought/cucumber/json/deserializers to make support for both versions but in that case I introduce some kind of code smell into my project. This makes me worry.

**Comment by a1dutch** [comment]
i've managed to work round it locally, i just do a find/replace inside the json files. i merge my json files as a pre step before passing the merged json file into this library.
