### ISSUE TITLE
Scenario is marked as failed when steps are skipped

### ISSUE THREAD

**Issue by sudokar** [damianszczepanik/cucumber-reporting#669]
When we have all the steps (including before steps) are marked as skipped, we expect to ignore the scenario status from the overall status.  Maybe we can include one more status column for scenarios to mark the scenario is skipped when all the steps in the scenario are marked as skipped

**Comment by damianszczepanik** [comment]
This is by design and it was already discussed in other requests. Take a look and review them (issues probably closed now)
