### ISSUE TITLE
Unable to use Cucumber-Reporting in my cucumber project

### ISSUE THREAD

**Issue by mechingineer** [damianszczepanik/cucumber-reporting#671]
Hi Damian,

I am not able to use this plugin to create a consolidated report. I do understand that this plugin takes all the JSON created as outputs from various test runners from parallel execution and then creates a consolidated HTML report.

My only question is where to include the code provided in the readme.md?

If I include the code(which calls method to generate HTML) in the @AfterClass customrunner.vm then it says 2.json is not a valid Cucumber output and fails to generate the report.

I do understand that I need to create a separate class that would include the provided code but my question is how would I call the method after the complete execution of the multiple test runners ?

Please help me as this would be great help.

**Comment by damianszczepanik** [comment]
I don't think this is right place for such question as I maintain only report generation and let developers us it as they want: standalone, maven plugin, pojo or jenkins
