### ISSUE TITLE
Support for cucumber 2.0.x

### ISSUE THREAD

**Issue by pavelpp** [damianszczepanik/cucumber-reporting#676]
I'm in the process of migrating to cucumber 2.0.1 and looks like .json report format changed a bit. As a result my embeddings / text output from before/after hooks are not included into reports. This is a showstopper for me as I can't migrate without proper support in the reporting plugin.

**Comment by mpkorstanje** [comment]
This has been fixed with https://github.com/cucumber/cucumber-jvm/pull/1236. Currently not yet released.

**Comment by pavelpp** [comment]
good to know! Then I guess this can be closed.
