### ISSUE TITLE
Add ability to link reports to Jenkins test reports

### ISSUE THREAD

**Issue by mdentremont** [damianszczepanik/cucumber-reporting#68]
Our team was looking into your Jenkins plugin, and we were thinking about adding the possibility to linking your cucumber reports to the test report for the same Jenkins build.

I have managed to shim a quick solution, which probably isn't the nicest :), I'll include the code in case you are interested and/or it helps explain what we were trying to do.

    diff --git src/main/resources/templates/featureReport.vm src/main/resources/templates/featureReport.vm
    index 958bca2..67275d5 100755
    --- src/main/resources/templates/featureReport.vm
    +++ src/main/resources/templates/featureReport.vm
    @@ -204,8 +204,13 @@ table.data-table td {
                $feature.getDescription()
    
                #foreach($scenario in $scenarios)
    +                #set ($featureJunitReportPath = $feature.getRawName())
    +                #set ($scenarioJunitReportPath = $scenario.getRawName().replaceAll(" ", "_"))
    +
                    $scenario.getTagsList()
    -                $scenario.getName()
    +                <a href="${jenkins_base}job/$build_project/$build_number/testReport/(root)/$featureJunitReportPath/$scenarioJunitReportPath">
    +                    $scenario.getName()
    +                </a>
                    #foreach($step in $scenario.getSteps().toList())
                    $step.getName()
                        $step.getDocStringOrNothing()

**Comment by damianszczepanik** [comment]
Done #94
