### ISSUE TITLE
It's possible introduce another time format? 

### ISSUE THREAD

**Issue by vitamotus** [damianszczepanik/cucumber-reporting#688]
Hi, 
 
It's possible introduce new time format? For example: 

`private static final PeriodFormatter TIME_FORMATTER = new PeriodFormatterBuilder()
            .appendHours()
            .appendSeparator(":")
            .appendMinutes()
            .appendSeparator(":")
            .appendSeconds()
            .appendSeparator(".")
            .minimumPrintedDigits(3)
            .appendMillis()
            .toFormatter();`

It's be very helpful for us. Maybe it's possible somehow override existing format from our side? 
We are using maven-cucumber-reporting as plugin, and can't override Util class in cucumber-reporting.

Thanks in advance!

**Comment by damianszczepanik** [comment]
How about #689 ? I added leading zero for milliseconds.

**Comment by vitamotus** [comment]
Hi!

It would be great if you can release that changes. Of course if it not a big problem for you. 

Thanks in advance!
