### ISSUE TITLE
Extra scenario getting added for scenario outline in cucumber reports

### ISSUE THREAD

**Issue by sandeepJois** [damianszczepanik/cucumber-reporting#70]
@kingsleyh : I am using 0.0.23 cucmber-report plugin , 0.0.2 Cucumber Plugin with our Jenkins for the report generation . And I have a cucumber plugin of 1.1.8 with my IntelliJ IDE .

As we can see in the attached image , the extra dummy scenario is getting populated in Jenkins report for every *scenario outline* . So even there are only 6 scenarios (indicated green in the attached image) , the cucumber-report shows 9 count under the scenarios .

Could you please take a look into this and let us know if we are missing anything here .

Thanks in advance !

Cucumber-Report Link :
![cucumber_jvm_html_reports_feature](https://cloud.githubusercontent.com/assets/6798233/4183501/6d79c062-373d-11e4-894b-2366e92aaa1a.png)

Example scenario outline link :
![screen shot 2014-09-08 at 3 19 05 pm](https://cloud.githubusercontent.com/assets/6798233/4183506/78777928-373d-11e4-8110-d31588cdf17d.png)

**Comment by robin-carry** [comment]
This is basically handling Scenario Outline. Is this supported with the TOOLING?

**Comment by damianszczepanik** [comment]
This should work fine with recent version. If not provide json file so I can handle this problem
