### ISSUE TITLE
How can I fix the "cucumber.json is not proper cucumber report" error?

### ISSUE THREAD

**Issue by nahinaz** [damianszczepanik/cucumber-reporting#701]
Please help me out with this error i'm getting. I really like the way this plugin generates the html report. 

Here is my pom.xml file - 

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>

		<dependency>
			<groupId>com.saucelabs</groupId>
			<artifactId>sauce-connect</artifactId>
			<version>3.1.32</version>
		</dependency>
		<dependency>
			<groupId>com.saucelabs</groupId>
			<artifactId>ci-sauce</artifactId>
			<version>1.75</version>
		</dependency>
		<dependency>
			<groupId>jtds</groupId>
			<artifactId>jtds</artifactId>
			<version>1.3.1</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-picocontainer</artifactId>
			<version>1.2.5</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-jvm</artifactId>
			<version>1.2.5</version>
			<type>pom</type>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.5</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.7.1</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-remote-driver</artifactId>
			<version>3.7.1</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-api</artifactId>
			<version>3.7.1</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>3.7.1</version>
		</dependency>
		<dependency>
			<groupId>org.picocontainer</groupId>
			<artifactId>picocontainer</artifactId>
			<version>2.14.3</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.11</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.9</version>
		</dependency>

		<dependency>
			<groupId>net.coobird</groupId>
			<artifactId>thumbnailator</artifactId>
			<version>0.4.1</version>
		</dependency>
		<dependency>
    		<groupId>net.masterthought</groupId>
		    <artifactId>cucumber-reporting</artifactId>
		    <version>3.13.0</version>
		</dependency>

	</dependencies>

And here is my cucumber.json file

[
  {
    "line": 2,
    "elements": [
      {
        "before": [
          {
            "result": {
              "duration": 261955436,
              "status": "passed"
            },
            "match": {
              "location": "StepDefinitions.setupCucumber(Scenario)"
            }
          }
        ],
        "line": 14,
        "name": "######################",
        "description": "",
        "id": "##################",
        "after": [
          {
            "result": {
              "duration": 151828,
              "status": "passed"
            },
            "match": {
              "location": "AreaComparison.afterTest(Scenario)"
            }
          },
          {
            "result": {
              "duration": 19922,
              "status": "passed"
            },
            "match": {
              "location": "LocationSummary.afterTest(Scenario)"
            }
          },
          {
            "result": {
              "duration": 607629034,
              "status": "passed"
            },
            "match": {
              "location": "StepDefinitions.tearDown(Scenario)"
            }
          },
          {
            "result": {
              "duration": 610424730,
              "status": "passed"
            },
            "match": {
              "location": "StepDefinitions.afterTest(Scenario)"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 3000273171,
              "status": "passed"
            },
            "line": 15,
            "name": "Launch Browser and go to Homepage",
            "match": {
              "location": "LocationSummary.Launch_Browser_and_go_to_Homepage()"
            },
            "keyword": "Given "
          }
        ],
        "tags": [
          {
            "line": 13,
            "name": "@aboutPage1"
          }
        ]
      }
    ],
    "name": "################",
    "description": "",
    "id": "#######################",
    "keyword": "Feature",
    "uri": "features/TestCase_6.feature",
    "tags": [
      {
        "line": 1,
        "name": "@aboutPage"
      },
      {
        "line": 1,
        "name": "@functionalTest"
      }
    ]
  }
]

**Comment by damianszczepanik** [comment]
Report is correct. Check if what you attached is really what you are trying to generate report from.
