### ISSUE TITLE
[Feature Request] ReRuned Scenarios to be displayed only once

### ISSUE THREAD

**Issue by szabolcslevay** [damianszczepanik/cucumber-reporting#705]
**Problem**
There are libraries which permits to re-run failed Cucumber scenarios, e.g. [Cucumber Reports](http://mkolisnyk.github.io/cucumber-reports/).  In case of re-execution the resulting `cucumber.json` will contain multiple results for the same `Scenario`. 
**Example**: a scenario is failing and a flag is set to retry the execution 2 times; for the first try will fail again, but will pass for the second retry; the generated report will contain all the results, not only the last one and this way the result will be polluted by intermediate results.

**Request**
The request would be to consider only the latest result for the re-executed scenario (or a `Boolean` flag in [cucumber-reporting](https://github.com/damianszczepanik/cucumber-reporting) and/or [cucumber-reports-plugin](https://github.com/jenkinsci/cucumber-reports-plugin) to decide how the user wants the report: only with the latest result or the complete execution including the retries).

Here is a `cucumber.json` example where the same scenario has multiple results based on the retry count:

```javascript
[
  {
    "line": 1,
    "elements": [
      {
        "line": 7,
        "name": "Test Scenario 2",
        "description": "",
        "id": "test-feature;test-scenario-2",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 230914077,
              "error_message": "java.lang.AssertionError: Failing the test case.\r\n\tat org.junit.Assert.fail(Assert.java:88)\r\n\tat org.junit.Assert.assertTrue(Assert.java:41)\r\n\tat steps.TestSteps.stepIs(TestSteps.java:31)\r\n\tat ✽.When step is \"failed\"(features/Test.feature:8)\r\n",
              "status": "failed"
            },
            "line": 8,
            "name": "step is \"failed\"",
            "match": {
              "arguments": [
                {
                  "val": "failed",
                  "offset": 9
                }
              ],
              "location": "TestSteps.stepIs(String)"
            },
            "keyword": "When "
          }
        ]
      },
      {
        "line": 7,
        "name": "Test Scenario 2",
        "description": "",
        "id": "test-feature;test-scenario-2",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 565993, 
              "error_message": "java.lang.AssertionError: Failing the test case.\r\n\tat org.junit.Assert.fail(Assert.java:88)\r\n\tat org.junit.Assert.assertTrue(Assert.java:41)\r\n\tat steps.TestSteps.stepIs(TestSteps.java:31)\r\n\tat ✽.When step is \"failed\"(features/Test.feature:8)\r\n",
              "status": "failed"
            },
            "line": 8,
            "name": "step is \"failed\"",
            "match": {
              "arguments": [
                {
                  "val": "failed",
                  "offset": 9
                }
              ],
              "location": "TestSteps.stepIs(String)"
            },
            "keyword": "When "
          }
        ]
      },
      {
        "line": 7,
        "name": "Test Scenario 2",
        "description": "",
        "id": "test-feature;test-scenario-2",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 733638,
              "error_message": "java.lang.AssertionError: Failing the test case.\r\n\tat org.junit.Assert.fail(Assert.java:88)\r\n\tat org.junit.Assert.assertTrue(Assert.java:41)\r\n\tat steps.TestSteps.stepIs(TestSteps.java:31)\r\n\tat ✽.When step is \"failed\"(features/Test.feature:8)\r\n",
              "status": "failed"
            },
            "line": 8,
            "name": "step is \"failed\"",
            "match": {
              "arguments": [
                {
                  "val": "failed",
                  "offset": 9
                }
              ],
              "location": "TestSteps.stepIs(String)"
            },
            "keyword": "When "
          }
        ]
      }
    ],
    "name": "Test Feature",
    "description": "",
    "id": "test-feature",
    "keyword": "Feature",
    "uri": "features/Test.feature"
  }
]
```

Thank you,

**Comment by damianszczepanik** [comment]
I disagree, the reality is not as easy as you wrote:
1. IF there are more json files which are presented in single report, how do you know which one was the latest
2. If the same scenario is executed with different parameters how would you combine results?
3. If same scenario is executed for different browsers can you combine then and treat as same?

If you want to combine scenarios in single you should do it by yourself..

**Comment by szabolcslevay** [comment]
Unfortunately I do not have answers to your questions and haven't dived that deep into the consequences. The thoughts started from my use case, where I have (almost) always a single `json` file as an output result file (and I know it's name/path) and this is the one I provide to Jenkins Cucumber Report Plugin. Also, I'm not combining different browsers in the same test execution.

I did not assume it would be easy. It's something I need right now (and I needed years ago as well) and I was curios if it's doable somehow/someway in the `cucumber-reporting` and/or `cucumber-reports-plugin`.

Thanks for your time and keep up the good work!
