### ISSUE TITLE
application/xml mime type is not supported in the cucumber report

### ISSUE THREAD

**Issue by prajakala** [damianszczepanik/cucumber-reporting#711]
Able to embed xml with mimetype 'application/xml' in the report. The XML is embedded successfully. However, when I try to view the XML embedded in the report, it shows a message asking me to file a bug so this mime type can be supported. 

Note: I am able to download the attached XML from the report.

**Comment by mpkorstanje** [comment]
As a work around you can try `text/xml` for now. 

It would appear that [the mime type is missing here](https://github.com/damianszczepanik/cucumber-reporting/blob/a8684595c0e84fb34d63b7ec1318ea0fe2dfc949/src/main/resources/templates/macros/json/embeddings.vm#L22).

And it would also appear that [several recognized formats are not also embeded](https://github.com/damianszczepanik/cucumber-reporting/blame/a8684595c0e84fb34d63b7ec1318ea0fe2dfc949/src/main/java/net/masterthought/cucumber/json/Embedding.java#L63). I believe most browsers can even handle PDF now  these days.

**Comment by damianszczepanik** [comment]
You can prepare PR what is very simple as some developers already extended list of supported mime types
