### ISSUE TITLE
undefined status as result after generate json files 

### ISSUE THREAD

**Issue by CarotUnima** [damianszczepanik/cucumber-reporting#715]
After I generate my feature files to json files I get alway for all steps undefined status as result in json while I can run the same features in command line without any undefined status!
can you plz help me how can I fix it?!

###  JSON - cucumber.json
`[
  {
    "line": 1,
    "elements": [
      {
        "line": 3,
        "name": "",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "result": {
              "status": "undefined"
            },
            "line": 4,
            "name": "callonce read('common.feature')",
            "match": {},
            "keyword": "* "
          },
          {
            "result": {
              "status": "undefined"
            },
            "line": 5,
            "name": "url appUrlBase",
            "match": {},
            "keyword": "* "
          },
          {
            "result": {
              "status": "undefined"
            },
            "line": 6,
            "name": "def funCreateTask =",
            "match": {},
            "keyword": "* ",
            "doc_string": {
              "content_type": "",
              "line": 7,
              "value": "function(){  \n  var res = []; \n  for (var i = 0; i < 5; i++) {\n    var res1 = karate.call('create-task.feature');\n    res.push(res1.response);\n  }\n  return res; \n}"
            }
          },
          {
            "result": {
              "status": "undefined"
            },
            "line": 18,
            "name": "def funStartAndCompletedTask =",
            "match": {},
            "keyword": "* ",
            "doc_string": {
              "content_type": "",
              "line": 19,
              "value": "function(arr){  \n  var res = [];\n  for (var i = 0; i < arr.length; i++) {\n  \tvar res1 = karate.call('start-and-completed-task.feature',{taskId : arr[i].task.id});\n  \tres.push(res1.response);\n  }\n  return res; \n}"
            }
          }
        ]
      },
      {
        "line": 29,
        "name": "Create Multiple task",
        "description": "",
        "id": "create-multiple-task-then-start-and-completed;create-multiple-task",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "status": "undefined"
            },
            "line": 31,
            "name": "def response1 = funCreateTask()",
            "match": {},
            "keyword": "* "
          },
          {
            "result": {
              "status": "undefined"
            },
            "line": 32,
            "name": "def response2 = funStartAndCompletedTask(response1)",
            "match": {},
            "keyword": "* "
          }
        ]
      }
    ],
    "name": "Create multiple task then start and completed",
    "description": "",
    "id": "create-multiple-task-then-start-and-completed",
    "keyword": "Feature",
    "uri": "wimo/wimo-case-create-multiple-task.feature"
  }
]`

### CODE create json file
`@RunWith(Cucumber.class)
@CucumberOptions(plugin = {"pretty", "html:target/cucumber", "json:target/cucumber.json"}
,  features = "classpath:blabla"
, tags = {"~@ignore"})`

`
@BeforeClass
	public static void before() {
		Properties props = System.getProperties();
    	String env = props.getProperty("env", "dev");
		System.setProperty("karate.env", env);
	}

@Test
    public void testParallel() {
        String karateOutputPath = "target/surefire-reports";
        KarateStats stats = CucumberRunner.parallel(getClass(), 1);
        
        generateReport(karateOutputPath);
        assertTrue("there are scenario failures", stats.getFailCount() == 0);        
    }
    
    private static void generateReport(String karateOutputPath) {
        Collection<File> jsonFiles = FileUtils.listFiles(new File(karateOutputPath), new String[] {"json"}, true);
        List<String> jsonPaths = new ArrayList(jsonFiles.size());
		for (File file : jsonFiles) {
				jsonPaths.add(file.getAbsolutePath());
		}
        Configuration config = new Configuration(new File("target"), "Wimo Backend");
        ReportBuilder reportBuilder = new ReportBuilder(jsonPaths, config);
        reportBuilder.generateReports();        
    }`
##  Test case children
`@CucumberOptions(features = 
		"classpath:wimo/blabla.feature"
)`

`@Test
    public void testParallel() {
        String karateOutputPath = "target/surefire-reports";
        KarateStats stats = CucumberRunner.parallel(getClass(), 1, karateOutputPath);
        generateReport(karateOutputPath);
        assertTrue("there are scenario failures", stats.getFailCount() == 0);        
    }
    
	private static void generateReport(String karateOutputPath) {
		Collection<File> jsonFiles = FileUtils.listFiles(new File(karateOutputPath), new String[] { "json" }, true);
		final List<String> jsonPaths = new ArrayList(jsonFiles.size());
		for (File file : jsonFiles) {
			if (file.getName().contains("blabla")) {
				jsonPaths.add(file.getAbsolutePath());
				break;
			}
		}
		Configuration config = new Configuration(new File("target"), "Wimo Backend");
		ReportBuilder reportBuilder = new ReportBuilder(jsonPaths, config);
		reportBuilder.generateReports();
	}`

**Comment by damianszczepanik** [comment]
Not sure what the problem is

**Comment by CarotUnima** [comment]
So what can I do with it?

**Comment by damianszczepanik** [comment]
Explain the problem?

**Comment by CarotUnima** [comment]
- I'm using eclipse to run before publishing to jenkins.
- On eclipse I run the **.feature file and export the html file. Everything is great (See the code below)
`@CucumberOptions(features = 
		"classpath:blabla/***blabla.feature")
  public class TestCaseRunner {
    @Test
    public void testParallel() {
        String karateOutputPath = "target/surefire-reports";
        KarateStats stats = CucumberRunner.parallel(getClass(), 1, karateOutputPath);
        generateReport(karateOutputPath);
        assertTrue("there are scenario failures", stats.getFailCount() == 0);        
    }

    private static void generateReport(String karateOutputPath) {
		Collection<File> jsonFiles = FileUtils.listFiles(new File(karateOutputPath), new String[] { 
                "json"}, true);
		final List<String> jsonPaths = new ArrayList(jsonFiles.size());
		for (File file : jsonFiles) {
			if (file.getName().contains("***blabla")) {
				jsonPaths.add(file.getAbsolutePath());
				break;
			}
		}
		Configuration config = new Configuration(new File("target"), "Blala");
		ReportBuilder reportBuilder = new ReportBuilder(jsonPaths, config);
		reportBuilder.generateReports();
	}
}
`
But when I change the code to export json file (cucumber.json) not export html reporting
After I generate my feature files to json files I get alway for all steps undefined status as result in json while I can run the same features in command line without any undefined status!

### Code export cucumber.json
`@RunWith(Cucumber.class) 
@CucumberOptions(plugin = {"pretty", "html:target/cucumber", "json:target/cucumber.json"}
, features = "classpath:blabla/***blabla.feature" 
, tags = {"~@ignore"})
public class  TestCaseRunner {}`

### Version cucumber-reporting 
`<dependency>
		<groupId>net.masterthought</groupId>
		<artifactId>cucumber-reporting</artifactId>
		<version>3.16.0</version>
		<scope>test</scope>
	</dependency>`

**Comment by CarotUnima** [comment]
Thank you, i got it
### This is solution
- Instead of using the code below to export the json file
`@RunWith(Cucumber.class) @CucumberOptions(plugin = {"pretty", "html:target/cucumber", "json:target/cucumber.json"} , features = "classpath:blabla/***blabla.feature" , tags = {"~@ignore"}) public class TestCaseRunner {}`

- I have merge all json files of ``@cucumberoptions(features ="classpath:blabla/***blabla.feature")` 
### CODE merge all json

`@CucumberOptions(features = "classpath:blabla", tags = {"~@ignore"}) // important: do not use @RunWith(Karate.class) !
public class TestRunner{
    
	@BeforeClass
	public static void before() {
		// do some thing
	}
	
    @Test
    public void testParallel() {
        String karateOutputPath = "target/surefire-reports";
        KarateStats stats = CucumberRunner.parallel(getClass(), 1);
        generateReport(karateOutputPath);
        assertTrue("there are scenario failures", stats.getFailCount() == 0);        
    }
    
    private static void generateReport(String karateOutputPath) {
        Collection<File> jsonFiles = FileUtils.listFiles(new File(karateOutputPath), new String[] {"json"}, true);
        String jsonReport = "";
        int number = 0;
		for (File file : jsonFiles) {
			String temp = readUsingBufferedReader(file.getAbsolutePath());	
			if (!TextUtils.isEmpty(temp)){
				if( number == 0){
					jsonReport = temp.substring(0, temp.lastIndexOf("]")) + ",";
				}else if(number == jsonFiles.size() - 1){
					jsonReport = jsonReport + temp.substring(temp.indexOf("[")+1, temp.length());
				}else {
					jsonReport = jsonReport + temp.substring(temp.indexOf("[")+1, temp.lastIndexOf("]")) + ",";
				}
			}
			number += 1;
			
		}
		writeSmsToFile(jsonReport, "target/cucumber.json");    
    }
    
    
    private static void writeSmsToFile(String data, String fileName) {
        synchronized (WimoAndroidTestRunner.class) {
            try {
                OutputStreamWriter outputStreamWriter = new OutputStreamWriter(new FileOutputStream(fileName, true));
                outputStreamWriter.append(data);
                outputStreamWriter.close();
            } catch (IOException ignored) {
            }
        }
    }
 
	private static String readUsingBufferedReader(String fileName) {
		BufferedReader reader = null;
		StringBuilder stringBuilder = new StringBuilder();

		try {
			reader = new BufferedReader(new FileReader(fileName));
			String line = null;
			String ls = System.getProperty("line.separator");
			while ((line = reader.readLine()) != null) {
				stringBuilder.append(line);
				stringBuilder.append(ls);
			}
			// delete the last ls
			stringBuilder.deleteCharAt(stringBuilder.length() - 1);
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			if (reader != null)
				try {
					reader.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
		}

		return stringBuilder.toString();
	}
    
}`
