### ISSUE TITLE
Capturing ScreenShots for failed steps

### ISSUE THREAD

**Issue by ssharmaexp** [damianszczepanik/cucumber-reporting#716]
First and Foremost- Thank you so so much for such a Gr8 work!
I would not call it an issue, instead this is more of a Question or adding new feature if not already available. 
I have implemented this report recently in our project, all seems Cool so far.  Now next requirement is to have screenshots captured and embed in reports for each failed step. I did not find any info here on how to get it done so it will be great if someone can help on it.

Thanks in Advance,
Satya.

**Comment by damianszczepanik** [comment]
This is for presenting the report not for performing tests which generate report
