### ISSUE TITLE
Unable to generate consolidated or an aggregated report from the parent project out of sub modules

### ISSUE THREAD

**Issue by Ravi2605** [damianszczepanik/cucumber-reporting#720]
Iam facing an issue while trying to understand on how to create an aggregated cucumber report out of mulitple cucumber json generated from sub modules having individual runners

Project A(parent)
--------> project B (sub module )--runner generates b.json
-------->project C(sub module)---runner generates c.json

Need to generate a consolidate report for project A through jenkins >any help on this will be highly appreciated.

**Comment by damianszczepanik** [comment]
This plugin does not generate JSON. It takes JSON as the input.

**Comment by Ravi2605** [comment]
sorry for the confusion on my above question ,my question is i have json input ready which i am going to supply to the plugin but what i want in the report is a collated result report of all the sub modules json which i supply for project A as a whole
