### ISSUE TITLE
cucumber-html-reports not generating.

### ISSUE THREAD

**Issue by kirshru** [damianszczepanik/cucumber-reporting#728]
used plugin = {"pretty","html:target/cucumber-html-report","json:target/cucumber.json"
has the entry 

<groupID>net.masterthought<groupID>
<artificatid>maven-cucumber-reporting</artifactid>
<VERSION>3.5.0</version>
and other POM tags 
verify phase has "generate" goal

I run MVN verify ... I don;t see feature.html reports generated.. only .json file is generated

**Comment by damianszczepanik** [comment]
Sorry but this is standalone, you probably need https://github.com/damianszczepanik/maven-cucumber-reporting
