### ISSUE TITLE
featureChartCarousel can't be paused

### ISSUE THREAD

**Issue by ghost** [damianszczepanik/cucumber-reporting#729]
First off, love the reporter. Just a request from one of my product managers. We want to be able to pause the featureChartCarousel after clicking on it or something like that since we display the report on a large tv screen. The movement of the carousel becomes distracting. Can you please add a way to stop the carousel from autosliding? Thank you

![6-3-2018 10-46-54 pm](https://user-images.githubusercontent.com/37546183/40896007-8fc94c7e-6780-11e8-9dcb-775d388d11a5.png)

**Comment by imtiazhossain** [comment]
Please delete this issue. I changed github accounts. Thank you. Sorry for the inconvenience
