### ISSUE TITLE
Group relevant output text with relevant attachment

### ISSUE THREAD

**Issue by imtiazhossain** [damianszczepanik/cucumber-reporting#730]
This plug in groups all of the output text together and all of the attachments together. I'd like them to be shown when they are called as its done in the basic html cucumber reporter.

Your cucumber reporter
![6-4-2018 3-15-44 pm](https://user-images.githubusercontent.com/7926510/40937559-087efd30-680d-11e8-9d26-3771fc24091d.png)

The basic reporter
![6-4-2018 3-16-22 pm](https://user-images.githubusercontent.com/7926510/40937590-1faf18e6-680d-11e8-95b0-20359ee18dbb.png)

Thanks

**Comment by damianszczepanik** [comment]
I don't understand your intention

**Comment by imtiazhossain** [comment]
I basically just want to be able to place relevant "output" with relevant "screenshots" similar to the way that the cucumber reporter does it.

**Comment by damianszczepanik** [comment]
Sorry but the report generates content based on the json file. Nothing more and nothing less
