### ISSUE TITLE
featureChartCarousel can't be paused

### ISSUE THREAD

**Issue by imtiazhossain** [damianszczepanik/cucumber-reporting#731]
First off, love the reporter. Just a request from one of my product managers. We want to be able to pause the featureChartCarousel after clicking on it or something like that since we display the report on a large tv screen. The movement of the carousel becomes distracting. Can you please add a way to stop the carousel from autosliding? Thank you

![6-3-2018 10-46-54 pm](https://user-images.githubusercontent.com/7926510/40941918-802a9e0e-681a-11e8-8e5d-2df7c58a2404.png)

**Comment by damianszczepanik** [comment]
Nice feature however I recommend to raise it to the library which I use http://www.chartjs.org/

**Comment by damianszczepanik** [comment]
OK, small update - I have updated the library and it pauses on mouse over :)
