### ISSUE TITLE
File log4j2.properties overrides existing configuration

### ISSUE THREAD

**Issue by alxdvlpr** [damianszczepanik/cucumber-reporting#734]
Including log4j2.properties into classpath breaks logic if you have configuration for instance in xml
See automatic [configuration](https://logging.apache.org/log4j/2.x/manual/configuration.html)

**Comment by damianszczepanik** [comment]
What is your expectation?

**Comment by alxdvlpr** [comment]
I think in that case there are 2 options:
- remove log4j2.properties file
- do not use logging by default, and use other names for the confuguration file

**Comment by damianszczepanik** [comment]
First option looks reasonable so then logging must be provided for https://github.com/jenkinsci/cucumber-reports-plugin
Would you like to prepare simple changes for both project?

**Comment by cbarath1986** [comment]
changing the "log4j.xml" to "log4j-test.xml" in my classpath resolved my issue. Thanks!

**Comment by magner58** [comment]
Also spend some time until I figured it out :)

It's actually not correct to include log4j configuration into a jar which is expected to be used as dependency by other projects https://www.mkyong.com/maven/maven-exclude-log4j-properties-in-jar-file

**Comment by damianszczepanik** [comment]
Honestly I don't need this file so let me remove it
