### ISSUE TITLE
Not getting the features report in jenkins 

### ISSUE THREAD

**Issue by rcodes01** [damianszczepanik/cucumber-reporting#747]
Hi
In jenkins I am getting the features statictics but not the features report.
Localy in my computer the report is produce in html format. 
This is my test class

import cdaf.helpers.AfterSuite;
import cdaf.helpers.BeforeSuite;
import cdaf.helpers.ExtendedCucumberRunner;
import cucumber.api.CucumberOptions;
import org.apache.log4j.Logger;
import org.junit.runner.RunWith;

@CucumberOptions(
        monochrome = true,
        features = "classpath:features",
        glue = {"classpath:cdaf.steps", "classpath:cdaf.runner"},
        plugin = {
                "pretty",
                "html:target/cucumber-html-report",
                "cdaf.formatter.XrayFormatter:xray-output.json",
                "json:target/cucumber.json",
                "junit:target/cucumber.xml",
                "usage:target/cucumber-usage.json",
                "cdaf.formatter.XrayFormatter:target/xray-output.json"
        }
)
@RunWith(ExtendedCucumberRunner.class)
public class RunE2EBrowserTest {

    protected static Logger log = Logger.getLogger(RunE2EBrowserTest.class);

    @BeforeSuite
    public static void setUp() {
        log.info("Before Test Suite execution");
    }

    @AfterSuite
    public static void tearDown() {
        log.info("After Test Suite execution");
    }
}

**Comment by damianszczepanik** [comment]
This has nothing in common with this project
