### ISSUE TITLE
ReadMe fails to explain any of the tags

### ISSUE THREAD

**Issue by telangn** [damianszczepanik/cucumber-reporting#750]
Many thanks for your help!

The ReadMe fails to explain any of the tags...

Mainly outputDirectory, cucumberOutput, parallelTesting, jsonParams.

Can you explain these as I am trying to set up parallel testing and don't know how to configure my pom with this plugin.

I feel like I got lucky in figuring out how to get this to work in the first place. 

many thanks in advance!

**Comment by damianszczepanik** [comment]
Well, this is true and even https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/Configuration.java was not fully documented. Should be better now
