### ISSUE TITLE
Overview-features.html declaration with Entity nbsp and end tags properly

### ISSUE THREAD

**Issue by sauravkumar05** [damianszczepanik/cucumber-reporting#752]
I am trying to convert the overview-features.html to png/pdf but I am running into issues since the HTML created has errors. There is a br tg in the HTML that doesnt end. Is it possible to remove it or end with appropriate tag. 
SAXParseException: the elemnet type br must be terminated by the matching end-tag

Also is it possible to declare the nbsp as below on the first line
<!DOCTYPE html [
                 <!ENTITY nbsp "&#160;">
]>

Is it possible for you to change other html also to make sure the tags are properly ended and the entity is declared

**Comment by damianszczepanik** [comment]
Delivered, sorry for delay
