### ISSUE TITLE
Can  columns displayed on feature and tags overview.html be customized ?

### ISSUE THREAD

**Issue by ssharmaexp** [damianszczepanik/cucumber-reporting#753]
Hi damianszczepanik,

I Run scripts for many countries in our project, so have a need of adding one more column i.e. **Country**  in the report table,
 so that Country wise data can be displayed. I want **@Tag** value to be displayed in this column  used in each scenario.
Plz let me know how to do this, if its possible?
Alternatively instead of having new column in report it will also do if - '**Device**' column can be renamed to **Country** and inputted with tag Values.

Or if not above, is it possible to Rename "tag" Column heading on tags.overview.html ? this can also serve my purpose for now.
And in this case can I have metaData table displayed on Tags overview also (by default it shows up only on features.overview page.

![reportsnap](https://user-images.githubusercontent.com/32358894/44520936-0ff66280-a6ef-11e8-8e61-b42debe699f4.PNG)

Plz  help in this regard, Thank you!

**Comment by damianszczepanik** [comment]
This is not supported and I don't have plan to do that.
