### ISSUE TITLE
Report not generating in-memory file system

### ISSUE THREAD

**Issue by ramanujd** [damianszczepanik/cucumber-reporting#755]
There is no support for in-memory file system to render report on the web server.
Either one need to have external context path or some way to write file from servlet container and that does not sound like the right approach for cloud apps.

Input json :

`public ReportBuilder(List<String> jsonFiles, Configuration configuration) {
        this.jsonFiles = jsonFiles;
        this.configuration = configuration;
        reportParser = new ReportParser(configuration);
    }`

Output report dir:

`   public Configuration(File reportDirectory, String projectName) {
        this.reportDirectory = reportDirectory;
        this.projectName = projectName;
    }`

in above both constructor - reportDirectory and jsonFiles are referred to java.io.File

so how can I render report on the web server, here I really mean lively publishing report online ?

I think the best way to do it allowing user to define their in-memory file system and support IO for 
[java.nio.file](https://docs.oracle.com/javase/7/docs/api/java/nio/file/package-summary.html)

**Comment by damianszczepanik** [comment]
I don't have plan for supporting this but you can send PR if you like
