### ISSUE TITLE
Is this report supports Parallel execution using Selenium Grid

### ISSUE THREAD

**Issue by ssharmaexp** [damianszczepanik/cucumber-reporting#756]
When I ran my tests/classes in paralle using selenium Grid, I'm not getting consolidated reports.
For example if I have two classes to be run in parallel, its just displaying results report for one class only which ever listed frist in TestNG xml.

for ex if I'm running below:
 `<test name=" Grid Regression Test" parallel="classes" thread-count="2">
        <classes>
            <class name="cukesRunnerClasses.CucumberRunnerClassAU"/>
            <class name="cukesRunnerClasses.CucumberRunnerClassNZ"/>
        </classes>
    </test>`

It displays report for classAU only, However I can see both browser runing perfectly and execution both classes in Parallel.
It will be really help full if any one can clarify if Parallel run is not supported by this report or I'm missing anything ..?

**Comment by damianszczepanik** [comment]
There is flag for that but due to the some problems with parallel testing I tread it more as legacy than support
