### ISSUE TITLE
Time format options?

### ISSUE THREAD

**Issue by beamanbr** [damianszczepanik/cucumber-reporting#758]
On Nov 16, 2017, you introduced a new time format for the report, to address issue #689.
This changed the "duration" column from a format like "2m 46s 54ms" to "2:46.054"

However some of us preferred the format which included units.  After feedback from management, I rolled back my cucumber-reporting version to 3.12.0 in order to restore this functionality.

Its all good for now, but I'd like to eventually come back to the current version for bug fixes and added features.  Is there any chance you can include a way for us to format the time ourselves?

**Comment by damianszczepanik** [comment]
I will accept PR about it but won't do it myself
