### ISSUE TITLE
Step Statistics View should show the step name

### ISSUE THREAD

**Issue by wilsonr990** [damianszczepanik/cucumber-reporting#760]
Hi I would like to see the name of the steps in the step statistics page. I'm using that page to be able to identify the steps that are taking to long (so that I can focus on improving them and the tests performance).
Location gives information but forces me to navigate to the code to identify what the step does; and also, someone that doesn't write the tests is not able to identify the critical steps nor read the table at all.

**Comment by damianszczepanik** [comment]
Can you add screenshot with notes what information should be put where?

**Comment by wilsonr990** [comment]
Hi Damian, yes. Below is the image of the steps statistics page of my project... As you can see, the implementation column contains the path to the step and it's not easy to identify what every step does without going to the code. 

![image](https://user-images.githubusercontent.com/7474566/45836207-c9862a80-bcd1-11e8-8c09-8d8b623512ed.png)

I want to add a new column with the step name so that I can read what step corresponds to every time.

**Comment by damianszczepanik** [comment]
That would be easy for steps but also hooks provide duration and they have no name
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/resources/json/sample.json#L275

for would you like to see for them?

**Comment by Downright-Development** [comment]
@damianszczepanik using this plugin for java naturally reports the name of the step.

**Comment by damianszczepanik** [comment]
and fo the hooks?

**Comment by damianszczepanik** [comment]
also the step name might be different for same implementation and then it's hard to decide how to present results
