### ISSUE TITLE
When all steps in a scenario are skipped then the scenario should be marked as skipped

### ISSUE THREAD

**Issue by SM-Rahman** [damianszczepanik/cucumber-reporting#761]
We have a requirement in E2E, where we skip scenarios based on the previous failures. But that is not captured in the report. We are making the step pending and it is captured in the steps but not in the scenario report. How to add a new column "skipped" in scenarios and add all the scenarios where the steps are skipped.

**Comment by damianszczepanik** [comment]
There is no logic for that as when this is implemented many others unclear status should be updated
