### ISSUE TITLE
[BUG] Trends not showing the correct passing feature amount (shows total features)

### ISSUE THREAD

**Issue by Downright-Development** [damianszczepanik/cucumber-reporting#762]
**Note: This is cross posted on the jenkins plugin repository.**

What appears to be happening is the context of "passed features" is not being set in the map on the trend generator, this then results in the plugin writing out the "total features" in the trend, rather than the passed amount.

(i.e. I had 50 features fail, 31 features passed, on the trend line It has two dots, one at 50 (marked as failure and colored red) and one at 81 (marked as passing and colored green...even has the worked "Passed:" next to it.)) 

In the above scenario I'd expect my two dots to be at 31 and 50 to accurately show what's failed and passed. 

When I get time, I'll see if I can create a PR for this.

**Comment by damianszczepanik** [comment]
In the job directory you can find https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/resources/cucumber-trends.json - send it back for analyze
