### ISSUE TITLE
docString not picked up

### ISSUE THREAD

**Issue by mfulton26** [damianszczepanik/cucumber-reporting#767]
I'm using cucumber-js so maybe the generated JSON report is slightly different. A docString from it shows up under `$[*].elements[*].steps[*].arguments[*].content` while, if I understand correctly, `cucumber-reporting` expects it to be under `$[*].elements[*].steps[*].doc_string.value`.

Can support be added to recognize both variants and include them?

Thank you.

**Currently Supported**

```json
[
  {
    "elements": [
      {
        "steps": [
          {
            "doc_string": {
              "content_type": "",
              "line": 10,
              "value": "doc string content goes here"
            }
          }
        ]
      }
    ]
  }
]
```

**Desired to be Supported**

```json
[
  {
    "elements": [
      {
        "steps": [
          {
            "arguments": [
              {
                "content": "doc string content goes here",
                "line": 10
              }
            ]
          }
        ]
      }
    ]
  }
]
```

**Comment by damianszczepanik** [comment]
Then this is content, not docString - tell me more how this should be treated and what does it refer to (in tests)
