### ISSUE TITLE
Expand passed scenarios

### ISSUE THREAD

**Issue by bgruha** [damianszczepanik/cucumber-reporting#768]
Hi,

Is there a way to expand the passed scenarios by default on the detailed html report.

Thanks

**Comment by damianszczepanik** [comment]
This needs some development but I can drive you if you want to contribute and prepare PR

**Comment by Downright-Development** [comment]
@damianszczepanik I'm looking for a fun project, though my time may be scarce. Where would you start to accomplish such task?

**Comment by damianszczepanik** [comment]
look at element.vm file which decides if the scenario is open or not

**Comment by damianszczepanik** [comment]
@bgruha @Downright-Development As there were no action from your side, I have implemented feature which is now merged. You can build and test or wait for the next release.

**Comment by Downright-Development** [comment]
> @bgruha @Downright-Development As there were no action from your side, I have implemented feature which is now merged. You can build and test or wait for the next release.

Sorry for this, I actually moved jobs and they do not use Cucumber so I did not have a need for such. Also, life got a little hectic moving jobs.  Glad you got something implemented!
