### ISSUE TITLE
Previously, we were getting Device column in the reports when the parallelTesting was true

### ISSUE THREAD

**Issue by violetastegaru** [damianszczepanik/cucumber-reporting#769]
Hi Damian, 

Please let us know how to use the latest changes in the cucumber-reporting Jenkins plugin to get the Device column in the final aggregated report (Jenkins Cucumber-reports v4.0.1). It is mentioned that the latest Jenkins plugin version has support for parallel testing, but we couldn't get the previous behavior in the aggregated report (v3.20)

**Jenkins - Cucumber reports plugin**
_Provides pretty html reports for Cucumber. Can be used anywhere a json report is generated (Java, Ruby, JavaScript and other implementations). Now with support for parallel testing. | 4.0.1_

  publishers {
            cucumberReportPublisher {
                jsonReportDirectory('')
                fileIncludePattern('**/*.json')
            }
        }
        configure {
            it / publishers / 'net.masterthought.jenkins.CucumberReportPublisher' << {
                sortingMethod 'ALPHABETICAL'
                parallelTesting 'true'
            }
        }

    step([$class: 'CucumberReportPublisher', fileIncludePattern: 'aggregate/**/*.json', sortingMethod: 'ALPHABETICAL', reducingMethod: 'NONE',  parallelTesting: true])
    }

We run a lot in parallel on different devices, that column was helping us to make a distinction between the same features being ran against different browsers/devices. 

Please help us if we are not configuring properly the DSL Job, it was mentioned that parallelTesting is true by default, but it doesn't work like before.

Thank you!
Violeta

**Comment by damianszczepanik** [comment]
It is not supported any more as it was confused. We can talk about how this should be supported in 4.x version

**Comment by violetastegaru** [comment]
[cucumber-html-reports.zip](https://github.com/damianszczepanik/cucumber-reporting/files/2486424/cucumber-html-reports.zip)
Hi Damian,

You could check in the attached archive the reports that were generated with 3.20 plugin version. 
If we upgrade, how to use the current setting to differentiate between the runs. The cucumber.json files will contain same features which were executed on several platforms. 

Thank you very much for your support!
Violeta

**Comment by damianszczepanik** [comment]
You could use formatter to provide tags for each platform. I believe this is not good idea to use file name as Device - also sometimes it could not be Device but Platform etc

**Comment by abardallis** [comment]
@damianszczepanik We're facing this issue as well. We have multiple mobile devices running a suite of scenarios in parallel. The scenarios are _split up_, sent to different devices, and then those generate multiple JSON reports. The devices are _sharing_ the responsibility of the suite (i.e. not all scenarios run on all devices). Because of this, it's very helpful to glance at the report and see this column to know what checks ran on what devices.

**a)** Can you please clarify what you mean by "you could use formatter to provide tags for each platform"? Apologies for my ignorance. 
**b)** If **a** doesn't apply to our use case, do you have any other ideas on how we could regain this visibility?
**c)** You mentioned, "I believe this is not good idea to use file name as Device - also sometimes it could not be Device but Platform etc" – is this the only reason you believe this to not be a good idea (because "Device" may apply to us in mobile testing but "Platform" is more applicable to folks running checks on Chrome, Firefox, etc.) If that's the case, would it be possible to have a default column label but give the option to customize the column label via some key:value in the configuration block?

Greatly appreciate your insight.

**Comment by pavelpp** [comment]
We use Device column to specify Scenario name, as we break each feature file into multiple scenarios and run them in parallel. Now we can't see which scenario name it was, as multiple rows have the same Feature name in them. Such a basic thing as Scenario column should definitely be supported

**Comment by damianszczepanik** [comment]
I'm waiting for the idea how to solve this problem

**Comment by pavelpp** [comment]
@damianszczepanik which problem are you referring to exactly? json files contains scenario names. Is there something that makes it impossible to include these into report summary?

**Comment by damianszczepanik** [comment]
Scenario names are already there but I believe this is not enough for you. How would you like to decide how to manage this and how to display it

**Comment by pavelpp** [comment]
@damianszczepanik not sure I follow. Current view with the latest version does not include scenario names on the overview page.

**Comment by abardallis** [comment]
@pavelpp and I are having the same problem but with different use cases. Ultimately, the name of the JSON file (for us, it represents the mobile device under test that led to the report being generated, for @pavelpp it's the scenario name) is not being displayed on the cucumber report dashboard. 

@damianszczepanik you mentioned:
> I believe this is not good idea to use file name as Device - also sometimes it could not be Device but Platform etc.

This is true and I appreciate that you wouldn't want to generate a "Device" column populated with data that isn't the name of the device. **Would it be possible to restore the Device column behavior but to customize the column label via some key:value in the configuration block?**

**Comment by damianszczepanik** [comment]
Looks like idea worth to discuss - tell me more details about your vision

**Comment by abardallis** [comment]
All in theory but to start the discussion, could be something like this...

An example block in Jenkinsfile that controls cucumber-reporting plugin behavior is as follows:

```
      cucumber buildStatus: 'UNSTABLE',
               jsonReportDirectory: './reports',
               fileIncludePattern: '*.json',
               trendsLimit: 100,
               parallelTesting: 'true',
               classificationsFilePattern: '**/*.properties'
```

Would it be possible to introduce a new `key:value` here for the purpose of defining a relevant label based on what is being parallelized (devices, scenarios, etc.)? For the purpose of this conversation, we'll say that key is `parallelTarget` (but perhaps you're better at naming things). That key would accept a string. Then the following logic could take place: 

If `parallelTesting: 'true'` and `parallelTarget` is specified...
The plugin would aggregate the reports as they are all ran in parallel and it would show a column populated with JSON file names. The column header would be contain whatever value was assigned to `parallelTarget` key. An example Pipeline config block would look like this:

```
      cucumber buildStatus: 'UNSTABLE',
               jsonReportDirectory: './reports',
               fileIncludePattern: '*.json',
               trendsLimit: 100,
               parallelTesting: 'true',
               parallelTarget: 'Device'
               classificationsFilePattern: '**/*.properties'
```

@damianszczepanik What are your ideas on if `parallelTarget` isn't specified? Should it have a default value and always show the column in the report populated w the JSON file names with some default column header. 
OR...
If `parallelTesting: 'true'` but `parallelTarget` isn't specified, there's no default value and the column isn't displayed at all. So if you want the column populated w JSON file names, you have to specify the column header via the `parallelTarget` value?

**Comment by damianszczepanik** [comment]
How would you like to decide which feature was assigned to which column? This sample does not answer for that crucial question.

**Comment by abardallis** [comment]
Not sure I understand the question. I presume that the feature would continue to be displayed in its own Feature column as it is now in the leftmost column in the report chart. 

Can you explain what you are asking in a bit more detail?

**Comment by daveysa** [comment]
Any progress on this issue? Or is that possible we can generate report separately with different name specified and show on Jenkins? (e.g. cucumber report Windows with reading all the reports-windows*.json and then have another tab cucubmer report MAC with reading all the reports-mac*.json)

**Comment by damianszczepanik** [comment]
Probably not via Jenkins but using this lib you can generate as many reports as you wish

**Comment by daveysa** [comment]
@abardallis @damianszczepanik 

In most of our cases, we ran same feature files against different test environment. Basically it means we run our test in parallel (based on different platform, different device/hardware, or whatever)

If we run test in parallel, we know what feature(s) ran and goes into which report.json file. Hence,  we can define the name of report.json file to be more reasonable name. For example, If we ran test based on platform, when the test ran and finished. we can name the report.json to be windows-report.json and ubuntu-report.json. 

And then, as @abardallis  suggested. We only need to have the "device" column back which also if possible we can define the column title. In this case, we can define that column as "platform". Then it will not confuse people.

      cucumber buildStatus: 'UNSTABLE',
               jsonReportDirectory: './reports',
               fileIncludePattern: '*.json',
               trendsLimit: 100,
               parallelTesting: 'true',
               parallelColumnTitle: 'platform'
               classificationsFilePattern: '**/*.properties'

Eventually, the previous "device" column can be any meaning fully title which makes sense

**Comment by damianszczepanik** [comment]
Let's talk about it. Some questions to define how it should work.

How would you present following JSONs:
```
/report/client/windows.json
/report/server/windows/json
/report/client/ubuntu.json
/report/server/ubuntu.json

**Comment by daveysa** [comment]
@damianszczepanik  I don't think the current cucumber report support ur cases any way. If I want to get all the result from parallel testing. I need to include all the json files created. In your case, I will just define my JSONs as follows:
/report/windows-client.json
/report/windows-server.json
/report/ubuntu-client.json
/report/ubuntu-server.json
I can even name my json to include feature file name
/report/windows-client-featureA.json
/report/windows-server-featureA.json
/report/ubuntu-client-featureA.json
/report/ubuntu-server-featureA.json

Then I can use the previous supported "device" column as a reference column to know which feature runs on which platform. Again, it really helpful and good enough to have the "device" tab to let us know what we test and test on where by just looking at the final cucumber report on Jenkins.

**Comment by violetastegaru** [comment]
Hi, 
I was also using the Device column as support for running in parallel the same feature on different platforms/browsers/brands. It was very helpful, to classify the reports. Now we are getting duplicates for the same features that run in parallel, and it's hard to make an immediate difference on failures based on the consolidated report. 
Thank you, Damian for your support on this!

    On Saturday, January 25, 2020, 01:00:18 AM GMT+1, daveysa <notifications@github.com> wrote:  
 
 
@damianszczepanik I don't think the current cucumber report support ur cases any way. If I want to get all the result from parallel testing. I need to include all the json files created. In your case, I will just define my JSONs as follows:
/report/windows-client.json
/report/windows-server.json
/report/ubuntu-client.json
/report/ubuntu-server.json
I can even name my json to include feature file name
/report/windows-client-featureA.json
/report/windows-server-featureA.json
/report/ubuntu-client-featureA.json
/report/ubuntu-server-featureA.json

Then I can use the previous supported "device" column as a reference column to know which feature runs on which platform. Again, it really helpful and good enough to have the "device" tab to let us know what we test and test on where by just looking at the final cucumber report on Jenkins.

**Comment by damianszczepanik** [comment]
@daveysa @violetastegaru define requirements for this change so I can estimate what should be done and the effort

**Comment by daveysa** [comment]
@damianszczepanik 

Requirement: add new column on Jenkins cucumber report to show all the included reports*.json file names.

Previously the cucumber report has "device" column to show all the included reports*.json files names. We want this feature back and in additional the user can name the "device" column to be any title and if user doesn't type any customized title, the column title will still show as default "device"  (e.g. platform, browsers, and so on).

`                cucumber([
                    jsonReportDirectory: './e2e-tests/features/output-files/reports',
                    fileIncludePattern: 'reports*.json',
                    parallelTesting: true,
                    deviceColumnTitle: "platform"
                    buildStatus: 'UNSTABLE'
                ])`

![Screen Shot 2020-01-29 at 2 30 11 PM](https://user-images.githubusercontent.com/15385760/73403260-f40fcc80-42a3-11ea-8e38-35712cf75f61.png)

Like above sample, "Device" column is what I want it back and we can define that "device" column title, "00", "01", ... in that column is actually the "reports-00.json, reports-01.json" files name with truncated "reports"

**Comment by damianszczepanik** [comment]
* where this column should be added, when not
* what does 'customize title' mean
* what are the rules about content of this column, how this should be filled

**Comment by daveysa** [comment]
* where this column should be added, when not
- If we set "parallelTesting: true," the column will be added. Otherwise, it's not
* what does 'customize title' mean
- We have the ability to name this column's title (column's header name)
* what are the rules about content of this column, how this should be filled
- The content of this column will grep the reports*.json file's name.
e.g. If the cucumber reported is generated by 

<img width="514" alt="Screen Shot 2020-01-31 at 2 17 35 PM" src="https://user-images.githubusercontent.com/15385760/73578425-77602800-4434-11ea-9171-e48d5bdd9a44.png">

**Comment by damianszczepanik** [comment]
The first question was 'where' not 'when' :)

**Comment by daveysa** [comment]
@damianszczepanik  ah, my bad. Just like the table I show in previous comment. In between "Feature" and "Steps"

Like below red cycle:

![73479808-86b87600-434d-11ea-93e7-698ef7b03137](https://user-images.githubusercontent.com/15385760/73687586-37d94c00-467f-11ea-913a-24b7fb2cc26d.png)

**Comment by damianszczepanik** [comment]
What about page which presents tags? and steps?

**Comment by daveysa** [comment]
I don't think we need page. The information shows on features page is good enough for us.

**Comment by violetastegaru** [comment]
Hi, 
At the page containing the tags and steps, i think it will be good to have the platform (Device column's content) as a classification (Platform ?). Thank you!

**Comment by damianszczepanik** [comment]
![target](https://user-images.githubusercontent.com/9612911/73742191-28740480-474c-11ea-9ea7-fac7e54bd5b4.png)
Let's start from this tiny approach. I don't like 'device' name as this may have nothing common with device. Tests can be executed on the same device but different browsers or operating system or different CPU/RAM resources.

Then my proposal is to have more generic name 'target' but I'm open for suggestions. Maybe 'qualifier'?

For now I'm not going to add feature to customize this.

**Comment by daveysa** [comment]
@damianszczepanik  I am fine with 'Target'. :)

**Comment by damianszczepanik** [comment]
@dabogee after #916 I believe `ReportFeatureByIdMerger` must be updated as well. Will you help me with this?

**Comment by damianszczepanik** [comment]
Guys, let me know if this is enough to be published
http://damianszczepanik.github.io/cucumber-html-reports/overview-features.html

**Comment by daveysa** [comment]
@damianszczepanik  LGTM. Thank you so much for supporting this!

**Comment by damianszczepanik** [comment]
@dabogee will you update according to above change?
