### ISSUE TITLE
Trends page on Jenkins shows the wrong numbers for "Features" and "Scenarios"

### ISSUE THREAD

**Issue by sasssan** [damianszczepanik/cucumber-reporting#778]
Hi. I noticed the Trends page on Jenkins is showing the wrong passed numbers for features and scenarios. I have attached a screenshot as an example. In the screenshot, the number of passed features is "1" but it is showing "4" on the trends page. Same thing happens for scenarios. It seems it always shows the "total" number of features/scenarios for the passed features/scenarios. Thanks in advance.
**EDIT:** The trends chart works fine visually, it's just when you hover your mouse over the dots that it shows the wrong number.

![trends issue](https://user-images.githubusercontent.com/44690158/47891566-d8065b00-dea7-11e8-8c02-514cccb6fef3.jpg)

**Comment by damianszczepanik** [comment]
I believe this is what was recently fixed
https://github.com/damianszczepanik/cucumber-reporting/pull/765

**Comment by sasssan** [comment]
Hey @damianszczepanik . I'm using version 4.1.0 and it's still happening. Should I wait for the next release?

**Comment by damianszczepanik** [comment]
Yes please
