### ISSUE TITLE
Reports generated with no information of test results

### ISSUE THREAD

**Issue by FaiMal** [damianszczepanik/cucumber-reporting#78]
I am using cucumber reporting for generating html reports from JSON output file.
I have the following code in a method generateReports()

        File reportOutputDirectory = new File("./target/cucumber-html-reports");
		List<String> jsonReportFiles = new ArrayList<String>();
		jsonReportFiles.add("./target/JsonResults/cucumber.json");

		String buildNumber = "1";
		String buildProject = "VCI AATs";
		Boolean skippedFails = false;
		Boolean undefinedFails = false;
		Boolean flashCharts = true;
		Boolean runWithJenkins = false;
		Boolean artifactsEnabled = false;
		Boolean highCharts = false;
		String artifactConfig = "";
		String pluginUrlPath = "";
		ReportBuilder reportBuilder = new ReportBuilder(jsonReportFiles, reportOutputDirectory, pluginUrlPath, buildNumber, buildProject,
				skippedFails, undefinedFails, flashCharts, runWithJenkins, artifactsEnabled, artifactConfig, highCharts);
		reportBuilder.generateReports();

I call this method in AfterClass
 
    @RunWith(Cucumber.class)
    @CucumberOptions(features = { "classpath:features/" }, format = { "json:target/JsonResults/cucumber.json" }, dryRun = false)
    public class CucumberTestsRun {

	@BeforeClass
	public static void setup() {
		System.out.println("Ran before");
	}

	@AfterClass
	public static void teardown() throws Exception {
		System.out.println("Ran after");
		GenerateReports.generateReports();
	}
}

I run the java project using JUnit and it generates the reports folder and the html files in it but when I open the files, they have no information about the scenarios that were run. I have checked the cucumber.json file and it has test results.
![reports_cucumber](https://cloud.githubusercontent.com/assets/8656524/4985407/0cbd9916-692d-11e4-924d-e8c020dbeb09.png)

What am I missing here? Is the cucumber.json file empty when @AfterClass is called and filled with data after that?

**Comment by grzechol** [comment]
Hi,
The problem is exactly what you said:

> Is the cucumber.json file empty when @AfterClass is called and filled with data after that? 

You can write a simple test to check this out:

```java
@AfterClass
public static void testJson() {
   File report = new File("target/cucumber.json");
   if (report.exists()) {
      System.out.println("cucumber.json size: " + report.length());
   } else {
      System.out.println("cucumber.json does not exist");
   }
}
```

In my case it prints:
`cucumber.json size: 0`

So the file is indeed empty when @AfterClass is called, and this is not related to cucumber-reporting. Perhaps you could open an issue in cucumber-junit or cucumber-jvm.

everything works perfectly fine with TestNG.

**Comment by FaiMal** [comment]
Thanks, I'll open an issue with cucumber-junit

**Comment by psrikrishna** [comment]
FaiMal, did you manage to find a solution/workaround for this?

**Comment by FaiMal** [comment]
No. I posted my question here on cukes group https://groups.google.com/forum/#!topic/cukes/XOlXxPritD8 but did not get any response.

**Comment by velanbabu** [comment]
I'm also facing same issue ,.. any solution is highly appreciated.

**Comment by damianszczepanik** [comment]
Give me json file, I will fix it

**Comment by velanbabu** [comment]
Thanks Damian. I unable to attach the json file so i'm pasting the content present in json.
[
  {
    "line": 1,
    "elements": [
      {
        "before": [
          {
            "result": {
              "duration": 10729123583,
              "status": "passed"
            },
            "match": {
              "location": "Hooks.openBrowser()"
            }
          }
        ],
        "line": 3,
        "name": "Opening Facebook application",
        "description": "",
        "id": "launching-application;opening-facebook-application",
        "after": [
          {
            "result": {
              "duration": 364220116,
              "status": "passed"
            },
            "match": {
              "location": "Hooks.tearDown(Scenario)"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 1774439849,
              "status": "passed"
            },
            "line": 4,
            "name": "I login the facebook url",
            "match": {
              "location": "StepDefs.i_login_the_facebook_url()"
            },
            "keyword": "Given "
          },
          {
            "result": {
              "duration": 833254222,
              "status": "passed"
            },
            "line": 5,
            "name": "I enter username",
            "match": {
              "location": "StepDefs.i_enter_username()"
            },
            "keyword": "And "
          },
          {
            "result": {
              "duration": 84003000,
              "status": "passed"
            },
            "line": 6,
            "name": "I enter password",
            "match": {
              "location": "StepDefs.i_enter_password()"
            },
            "keyword": "And "
          },
          {
            "result": {
              "duration": 5138040758,
              "status": "passed"
            },
            "line": 7,
            "name": "I click login button",
            "match": {
              "location": "StepDefs.i_click_login_button()"
            },
            "keyword": "And "
          },
          {
            "result": {
              "duration": 44901,
              "status": "passed"
            },
            "line": 8,
            "name": "Home page shown successfully",
            "match": {
              "location": "StepDefs.home_page_shown_successfully()"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "line": 2,
            "name": "@Facebook"
          }
        ]
      }
    ],
    "name": "Launching application",
    "description": "",
    "id": "launching-application",
    "keyword": "Feature",
    "uri": "samplefeature.feature"
  }
]

**Comment by damianszczepanik** [comment]
@velanbabu 
It works fine with my dev workspace so I need also screenshot from the report just to be sure that what you see is what I see it should be and also screenshot from the jenkins configuration page to be sure how did you setup the plugin

**Comment by velanbabu** [comment]
@damianszczepanik 
Actually I wrongly specified config.setting in Jenkins and After rectification,its working fine. Thanks a lot Damian.
