### ISSUE TITLE
NullPointerException for optional argument

### ISSUE THREAD

**Issue by biagiolampo** [damianszczepanik/cucumber-reporting#781]
We have a step like the following:
**@Then("^(\\d+) files(?: matching \"(.*)\")? have been failed to be collected for nodes in file (.*)")**

The second parameter is optional. 
It is managed by correctly Cucumber but when it is not provided we get NullPointerException while generating the report.

**JsonReport when the second parameter is not provided:**
`
           "name": "0 files have been failed to be collected for nodes in file BGF/FileCollectionNodes",
            "match": {
              "arguments": [
                {
                  "val": "0",
                  "offset": 0
                },
                {},
                {
                  "val": "BGF/FileCollectionNodes",
                  "offset": 59
                }
              ],
              "location": "FileCollectionResultNotificationSteps.verifyNumOfFilesToBeCollected(int,String,String)"
            },
`

**LOG:**
`
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'format' in  class net.masterthought.cucumber.util.StepNameFormatter threw exception java.lang.NullPointerException at /templates/macros/json/stepName.vm[line 3, column 47]

....
Caused by: java.lang.NullPointerException
	at net.masterthought.cucumber.util.StepNameFormatter.surroundArguments(StepNameFormatter.java:34)
	at net.masterthought.cucumber.util.StepNameFormatter.format(StepNameFormatter.java:19)
`

**JsonReport when the second parameter is provided:**
`
       "name": "2 files matching \"subscriptionType\u003dBSCRECORDINGS\" have been failed to be collected for nodes in file BSC/StatsFileCollectionNodes",
            "match": {
              "arguments": [
                {
                  "val": "2",
                  "offset": 0
                },
                {
                  "val": "subscriptionType\u003dBSCRECORDINGS",
                  "offset": 18
                },
                {
                  "val": "BSC/StatsFileCollectionNodes",
                  "offset": 101
                }
              ],
              "location": "FileCollectionResultNotificationSteps.verifyNumOfFilesToBeCollected(int,String,String)"
            },
`
     
It seems a regression coming with release 4.2.0

**Comment by damianszczepanik** [comment]
Which version have you used before?
Attach JSON file for reference

**Comment by damianszczepanik** [comment]
@ekalin looks like regression from  Highlight step arguments by making them bold. #771 

Can you take a look?

**Comment by biagiolampo** [comment]
4.1.0 works, so I can confirm it's a regression of latest 4.2.0

[FileCollectionIT.json.txt](https://github.com/damianszczepanik/cucumber-reporting/files/2571608/FileCollectionIT.json.txt)

**Comment by biagiolampo** [comment]
Sorry closed for a mistake.. reopening

**Comment by damianszczepanik** [comment]
Going to release fix version in next days

**Comment by biagiolampo** [comment]
Thanks
