### ISSUE TITLE
Trends page on Jenkins does not show passed/Failed "Scenarios"

### ISSUE THREAD

**Issue by sasssan** [damianszczepanik/cucumber-reporting#783]
Hi Damian. This one seems to be introduced as a result of https://github.com/damianszczepanik/cucumber-reporting/pull/765.
The "Scenarios" graph does not show anything until the failures are more than passed scenarios.
Please see the SC:
![image](https://user-images.githubusercontent.com/44690158/48445817-aa94a800-e7eb-11e8-845b-12fd1aec55f8.png)

Thanks.

**Comment by damianszczepanik** [comment]
Show me JSON file

**Comment by damianszczepanik** [comment]
Which plugin version do you have installed. JSON is mentioned in console log so you can find it easily

**Comment by sasssan** [comment]
Jenkins plugin is 4.2.0. Unfortunately company policy doesn't allow me to upload the test reports.
But again, when I switch to 4.1.0 the graphs are corrected. Cheers.

**Comment by sasssan** [comment]
Hey @damianszczepanik . I have masked all the steps so I'll be able to upload the JSON. Hope this helps:


[
  {
    "line": 3,
    "elements": [
      {
        "line": 11,
        "name": "some background",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "result": {
              "duration": 3310228930,
              "status": "passed"
            },
            "line": 12,
            "name": "some given statement",
            "match": {
              "location": "some location"
            },
            "rows": [
              {
                "cells": [
                  "NAME"
                ]
              },
              {
                "cells": [
                  "name one"
                ]
              },
              {
                "cells": [
                  "name two"
                ]
              },
              {
                "cells": [
                  "name three"
                ]
              },
              {
                "cells": [
                  "name four"
                ]
              }
            ],
            "keyword": "Given "
          }
        ]
      },
      {
        "line": 25,
        "name": "outline one",
        "description": "",
        "id": "some id",
        "after": [
          {
            "output": [
              "Test Passed."
            ],
            "result": {
              "duration": 44753,
              "status": "passed"
            },
            "match": {
              "location": "some location"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "duration": 2183511494,
              "status": "passed"
            },
            "line": 20,
            some when staement,
            "match": {
              "arguments": [
                {
                  "val": "name one",
                  "offset": 50
                },
                {
                  "val": "name five",
                  "offset": 69
                }
              ],
              "location": "some location"
            },
            "keyword": "When "
          },
          {
            "result": {
              "duration": 5239636,
              "status": "passed"
            },
            "line": 21,
            "name": "some then staement",
            "match": {
              "arguments": [
                {
                  "val": "block",
                  "offset": 50
                }
              ],
              "location": "some location"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "name": "@SomeTag"
          }
        ]
      },
      {
        "line": 11,
        "name": "some background",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "result": {
              "duration": 59376,
              "status": "passed"
            },
            "line": 12,
            "name": "some given statement",
            "match": {
              "location": "some location"
            },
            "rows": [
              {
                "cells": [
                  "NAME"
                ]
              },
              {
                "cells": [
                  "name one"
                ]
              },
              {
                "cells": [
                  "name two"
                ]
              },
              {
                "cells": [
                  "name three"
                ]
              },
              {
                "cells": [
                  "name four"
                ]
              }
            ],
            "keyword": "Given "
          }
        ]
      },
      {
        "line": 26,
        "name": "outline one",
        "description": "",
        "id": "some id",
        "after": [
          {
            "output": [
              "Test Passed."
            ],
            "result": {
              "duration": 27555,
              "status": "passed"
            },
            "match": {
              "location": "some location"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "duration": 15737157,
              "status": "passed"
            },
            "line": 20,
            some when staement,
            "match": {
              "arguments": [
                {
                  "val": "name six",
                  "offset": 50
                },
                {
                  "val": "name two",
                  "offset": 70
                }
              ],
              "location": "some location"
            },
            "keyword": "When "
          },
          {
            "result": {
              "duration": 4596278,
              "status": "passed"
            },
            "line": 21,
            "name": "some then staement",
            "match": {
              "arguments": [
                {
                  "val": "block",
                  "offset": 50
                }
              ],
              "location": "some location"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "name": "@SomeTag"
          }
        ]
      },
      {
        "line": 11,
        "name": "some background",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "result": {
              "duration": 50945,
              "status": "passed"
            },
            "line": 12,
            "name": "some given statement",
            "match": {
              "location": "some location"
            },
            "rows": [
              {
                "cells": [
                  "NAME"
                ]
              },
              {
                "cells": [
                  "name one"
                ]
              },
              {
                "cells": [
                  "name two"
                ]
              },
              {
                "cells": [
                  "name three"
                ]
              },
              {
                "cells": [
                  "name four"
                ]
              }
            ],
            "keyword": "Given "
          }
        ]
      },
      {
        "line": 27,
        "name": "outline one",
        "description": "",
        "id": "some id",
        "after": [
          {
            "output": [
              "Test Passed."
            ],
            "result": {
              "duration": 24743,
              "status": "passed"
            },
            "match": {
              "location": "some location"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "duration": 15318940,
              "status": "passed"
            },
            "line": 20,
            some when staement,
            "match": {
              "arguments": [
                {
                  "val": "name three",
                  "offset": 50
                },
                {
                  "val": "name four",
                  "offset": 72
                }
              ],
              "location": "some location"
            },
            "keyword": "When "
          },
          {
            "result": {
              "duration": 4509371,
              "status": "passed"
            },
            "line": 21,
            "name": "some then staement",
            "match": {
              "arguments": [
                {
                  "val": "block",
                  "offset": 50
                }
              ],
              "location": "some location"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "name": "@SomeTag"
          }
        ]
      },
      {
        "line": 11,
        "name": "some background",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "result": {
              "duration": 60724,
              "status": "passed"
            },
            "line": 12,
            "name": "some given statement",
            "match": {
              "location": "some location"
            },
            "rows": [
              {
                "cells": [
                  "NAME"
                ]
              },
              {
                "cells": [
                  "name one"
                ]
              },
              {
                "cells": [
                  "name two"
                ]
              },
              {
                "cells": [
                  "name three"
                ]
              },
              {
                "cells": [
                  "name four"
                ]
              }
            ],
            "keyword": "Given "
          }
        ]
      },
      {
        "line": 28,
        "name": "outline one",
        "description": "",
        "id": "some id",
        "after": [
          {
            "output": [
              "Test Passed."
            ],
            "result": {
              "duration": 40791,
              "status": "passed"
            },
            "match": {
              "location": "some location"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "duration": 14805729,
              "status": "passed"
            },
            "line": 20,
            some when staement,
            "match": {
              "arguments": [
                {
                  "val": "name four",
                  "offset": 50
                },
                {
                  "val": "name seven",
                  "offset": 71
                }
              ],
              "location": "some location"
            },
            "keyword": "When "
          },
          {
            "result": {
              "duration": 6139326,
              "status": "passed"
            },
            "line": 21,
            "name": "some then staement",
            "match": {
              "arguments": [
                {
                  "val": "block",
                  "offset": 50
                }
              ],
              "location": "some location"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "name": "@SomeTag"
          }
        ]
      },
      {
        "line": 11,
        "name": "some background",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "result": {
              "duration": 48584,
              "status": "passed"
            },
            "line": 12,
            "name": "some given statement",
            "match": {
              "location": "some location"
            },
            "rows": [
              {
                "cells": [
                  "NAME"
                ]
              },
              {
                "cells": [
                  "name one"
                ]
              },
              {
                "cells": [
                  "name two"
                ]
              },
              {
                "cells": [
                  "name three"
                ]
              },
              {
                "cells": [
                  "name four"
                ]
              }
            ],
            "keyword": "Given "
          }
        ]
      },
      {
        "line": 36,
        "name": "outline two",
        "description": "",
        "id": "some id",
        "after": [
          {
            "output": [
              "Test Passed."
            ],
            "result": {
              "duration": 29029,
              "status": "passed"
            },
            "match": {
              "location": "some location"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "duration": 16442505,
              "status": "passed"
            },
            "line": 31,
            some when staement,
            "match": {
              "arguments": [
                {
                  "val": "name six",
                  "offset": 50
                },
                {
                  "val": "name five",
                  "offset": 70
                }
              ],
              "location": "some location"
            },
            "keyword": "When "
          },
          {
            "result": {
              "duration": 6472857,
              "status": "passed"
            },
            "line": 32,
            "name": "some then staement",
            "match": {
              "arguments": [
                {
                  "val": "release",
                  "offset": 50
                }
              ],
              "location": "some location"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "name": "@SomeTag"
          }
        ]
      },
      {
        "line": 11,
        "name": "some background",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "result": {
              "duration": 54196,
              "status": "passed"
            },
            "line": 12,
            "name": "some given statement",
            "match": {
              "location": "some location"
            },
            "rows": [
              {
                "cells": [
                  "NAME"
                ]
              },
              {
                "cells": [
                  "name one"
                ]
              },
              {
                "cells": [
                  "name two"
                ]
              },
              {
                "cells": [
                  "name three"
                ]
              },
              {
                "cells": [
                  "name four"
                ]
              }
            ],
            "keyword": "Given "
          }
        ]
      },
      {
        "line": 37,
        "name": "outline two",
        "description": "",
        "id": "some id",
        "after": [
          {
            "output": [
              "Test Passed."
            ],
            "result": {
              "duration": 28739,
              "status": "passed"
            },
            "match": {
              "location": "some location"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "duration": 15507303,
              "status": "passed"
            },
            "line": 31,
            some when staement,
            "match": {
              "arguments": [
                {
                  "val": "name five",
                  "offset": 50
                },
                {
                  "val": "name eight",
                  "offset": 72
                }
              ],
              "location": "some location"
            },
            "keyword": "When "
          },
          {
            "result": {
              "duration": 5231739,
              "status": "passed"
            },
            "line": 32,
            "name": "some then staement",
            "match": {
              "arguments": [
                {
                  "val": "release",
                  "offset": 50
                }
              ],
              "location": "some location"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "name": "@SomeTag"
          }
        ]
      }
    ],
    "name": "some title for the feature file",
    "description": " some description",
    "id": "some id",
    "keyword": "Feature",
    "uri": "path t the feature file",
    "tags": [
      {
        "name": "@SomeTag",
        "type": "Tag",
        "location": {
          "line": 2,
          "column": 1
        }
      }
    ]
  }
]

**Comment by sasssan** [comment]
I don't think it's the JSON files. I added a trends file on my local machine:
{
  "buildNumbers" : [ "12", "1", "1", "1" ],
  "passedFeatures" : [ 0, 0, 0, 3 ],
  "failedFeatures" : [ 1, 1, 4, 1 ],
  "totalFeatures" : [ 1, 1, 4, 4 ],
  "passedScenarios" : [ 5, 0, 0, 39 ],
  "failedScenarios" : [ 1, 6, 45, 6 ],
  "totalScenarios" : [ 6, 6, 45, 45 ],
  "passedSteps" : [ 17, 0, 0, 130 ],
  "failedSteps" : [ 1, 6, 45, 6 ],
  "skippedSteps" : [ 0, 12, 97, 6 ],
  "pendingSteps" : [ 0, 0, 0, 0 ],
  "undefinedSteps" : [ 0, 0, 0, 0 ],
  "totalSteps" : [ 18, 18, 142, 142 ],
  "durations" : [ 5016359694, 18972614594, 137634947844, 30860964663 ]
}

Notice the results are correctly reflected on the feature page but not the trends page:
![image](https://user-images.githubusercontent.com/44690158/48456681-0c690800-e814-11e8-9538-c83c335b4eb7.png)

**Comment by damianszczepanik** [comment]
Fix is applied #784

**Comment by damianszczepanik** [comment]
Thanks for the reporting this bug!
