### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 32 at StepNameFormatter.java:40 using 4.2.2 version

### ISSUE THREAD

**Issue by biagiolampo** [damianszczepanik/cucumber-reporting#789]
Moving from 4.1.0 to 4.2.2 for testing 781 I got a different issue on another report

Please refer to attached json and html report.
[Cucumber_HTML_Report.zip](https://github.com/damianszczepanik/cucumber-reporting/files/2603155/Cucumber_HTML_Report.zip)
[SpectrumAnalyzerIT.json.txt](https://github.com/damianszczepanik/cucumber-reporting/files/2612230/SpectrumAnalyzerIT.json.txt)

NOTE: I suggest to improve the report to show what's the affected section of Json file in case of error like this or 781

**Comment by damianszczepanik** [comment]
@ekalin can fix it - JSON file is attached

**Comment by ekalin** [comment]
I've identified the problem and I'm working on a fix.

Can you post the step definition that leads to this step:
```
          {
            "line": 9,
            "name": "Restore the access to the Server",
            "match": {
              "arguments": [
                {
                  "val": "",
                  "offset": 32
                }
              ],
              "location": "CommonSteps.changeServerPermissions(String)"
            },
            "keyword": "And "
          }
```

**Comment by biagiolampo** [comment]
@Given("^(?:A|Restore the access to the) Server *(unreachable|which deny the access|)$")

**Comment by biagiolampo** [comment]
Thanks for the quick resolution 👍

**Comment by damianszczepanik** [comment]
delivered
