### ISSUE TITLE
calculateReportFileName() adds unnecessary numeration

### ISSUE THREAD

**Issue by foxhound91** [damianszczepanik/cucumber-reporting#806]
Scenario: Cucumber project generates a single json report
Given a project generates 1 JSON report
When the Jenkins Cucumber reports are generated
Then feature report file name contains unnecessary numeration

Whatever is causing could had been introduced with the 
revision number bbd17a03f7fea8bb62a691b7e035bfa7a0498cda on the 15/10/18 
or 7087cfad3556cd4ed4b52cc4ea4b2d827421d407 on the 25/10/18
by @damianszczepanik 

Example:
cucumber-html-reports/report-feature_features-DataDiscoveryService-feature.html
cucumber-html-reports/report-feature_1_features-GeolocationService-feature.html
cucumber-html-reports/report-feature_2_features-NotificationManagerService-feature.html

Jenkins console output
> [CucumberReport] Using Cucumber Reports version 4.3.0
> [CucumberReport] JSON report directory is "target"
> [CucumberReport] Copied 1 json files from workspace "/var/lib/jenkins/workspace/Marine - API Smoke Test/target" to reports directory "/var/lib/jenkins/jobs/Marine - API Smoke Test/builds/40/cucumber-html-reports/.cache"
> [CucumberReport] Copied 2 properties files from workspace "/var/lib/jenkins/workspace/Marine - API Smoke Test/target" to reports directory "/var/lib/jenkins/jobs/Marine - API Smoke Test/builds/40/cucumber-html-reports/.cache"
> [CucumberReport] Processing 1 json files:
> [CucumberReport] /var/lib/jenkins/jobs/Marine - API Smoke Test/builds/40/cucumber-html-reports/.cache/cucumber.json
> [CucumberReport] Found 1 failed steps, while expected not more than 0
> [CucumberReport] Build status is left unchanged

**Comment by damianszczepanik** [comment]
Why do you think this is 'unnecessary'?

**Comment by foxhound91** [comment]
Hi Damian, sorry for the lack of details.
I meant that given there is only one cucumber json results file then the numerations are not necessary at the file name.

so this:
> cucumber-html-reports/report-feature_features-DataDiscoveryService-feature.html
> cucumber-html-reports/report-feature_1_features-GeolocationService-feature.html
> cucumber-html-reports/report-feature_2_features-NotificationManagerService-feature.html
could be this:
> cucumber-html-reports/report-feature_features-DataDiscoveryService-feature.html
> cucumber-html-reports/report-feature_features-GeolocationService-feature.html
> cucumber-html-reports/report-feature_features-NotificationManagerService-feature.html

Please let me know if you need any further clarification, thanks

**Comment by damianszczepanik** [comment]
Numeration is needed
