### ISSUE TITLE
Add Sub Category Representation Of Tags Report

### ISSUE THREAD

**Issue by bhreinb** [damianszczepanik/cucumber-reporting#810]
Hi there,

I use tags for the following use cases when developing a test automation pattern with cucumber

1) User Story, Bug & Epic Requirements (@epic_xxx, @bug_xxx, @story_xxx)
2) Test Execution Types (@smoke_xxx, @nightly_xxx)
3) Setup & TearDown (@setup_xxx, @teardown_xxx)
4) Browsers (@chrome_xxx, @firefox_xxx, @ie_xxx)
5) Feature Toggles (@toggle_xxx)

As you can see their is quiet a few tags with different uses cases. I have a step at the end of a test run to remove tags I don't want rendered to the report but if I choose to render all five categories above then the content of the tags report gets very busy. Would you be open to a new feature whereby we have sub categories to represent Product Requirements, Test Execution Types etc.

The sub categories would be defined in config somewhere plus each sub category could be a tab under the Tags page. The content of the tab would be more or less the same as what the tags report show now. Thoughts?

**Comment by damianszczepanik** [comment]
Why don't you use two tags instead of single which combines all information? It looks like the way how you have implemented tags is not the way how tags are design to work.

**Comment by bhreinb** [comment]
I asked the question on the cucumber community slack channel...here is the answers I got back...

> Hi Folks,
> 
> I'm wondering what are peoples thoughts on my use of cucumber tags. I detail below. I use tags for the following use cases when developing a test automation pattern.
> 
> 1. User Story, Bug & Epic Requirements (@epic_xxx, @bug_xxx, @story_xxx) [xxx corresponds to a Jira ticket]
> 2. Test Execution Types (@smoke, @regression)
> 3. Setup & TearDown (@setup_xxx, @teardown_xxx) [xxx corresponds to dynamic label to setup/teardown for a particular test scenario]
> 4. Browsers (@chrome, @firefox, @ie)
> 5. Feature Toggles (@toggle_xxx) [xxx corresponds to a Jira ticket to toggle a feature]
> 
> Their is 5 categories which I'm probably at the limit of using with regards tags. Any more categories would be in fairness be too much. What I detail above is that typical usage of tags or are they not designed to work in the above way. Thanks in advance for any help with the above.
> 
> Answers below:
> 
> **Answer 1:**
> I think tag usage varies widely depending on what’s being automated, how it’s being used, and what sort of runs you need to have. 
> For example:
> We don’t add setup and teardown tags. Certain types of tests may have a specific setup/teardown, but those are usually are specified as a background step/steps. This is mostly because there’s no generic “setup” that needs to happen. It all depends on the features tested. 
> Additionally, we leverage tags to indicate the functional module being tested (related set of features in this case). So you may see tags like ‘@auth’ for login/logout type features, etc.
> 
> **Answer 2:**
> Currently tags are used to mark ownership. Team responsible for the feature gets pinged when it breaks.
> 
> And its used to mark certain types of tests. Tests with external dependencies are tagged and reported differently.
> 
> **Answer 3:**
> I only traditionally use tags for positive / negative markers (For business people to see what kind of test it is), and for JIRA / trello links for bugs.
> 
> For features/types I use the name / descriptions,.
> 
> **Answer 4:**
> See, we do use setup/teardown tags as we create (and if all goes well delete) test queues in hooks. They werent tagged before which resulted in way too many queues being created and not properly cleaned up, causing flakiness..

Based on the above I'm of the thinking that my usage isn't that untypical. Thoughts?

**Comment by damianszczepanik** [comment]
I gave you some idea how to solve problem you have. It's up to you if and how you solve it but I don't see space to add feature you requested as this is very specific one

**Comment by bhreinb** [comment]
I don't think the suggestion you offered with respect solves it however...it wouldn't make sense to combine the five categories to two as you say...as the content of the tags in some cases can be dynamic (namely they refer to a jira ticket item etc...answer 3 backs that)...however the question posed in any case was whether this could be a viable feature added to the library...I have that answer now...thanks for input on this.
