### ISSUE TITLE
Any way to display logs for each step in the report?

### ISSUE THREAD

**Issue by GoldenEagle19** [damianszczepanik/cucumber-reporting#811]
Hello, and thank you so much for such a great tool. It's greatly appreciated.

I wanted to know if there is a built-in way to display logs for each step of the scenario  (not only the failure stack trace) or at least show some logs that preceded that failure. We are using Cucumber for API testing and it would be very useful to see what happened in the test before the failure, which requests and with what data were sent.

I understand that this may not be implemented at the time, if that's the case I would appreciate if you could suggest something to help implement that.

**Comment by damianszczepanik** [comment]
Attach JSON file
