### ISSUE TITLE
is it possible to move the background steps to the scenario itself and get rid of background section in the report

### ISSUE THREAD

**Issue by cbarath1986** [damianszczepanik/cucumber-reporting#815]
is it possible to move the background steps to the scenario itself and get rid of background section in the report? i use cucumber with java and testng and implemented latest version of net.masterthought cucumber report. My business users wanted to have all the steps related to background at the top of scenario steps as its confusing them if they execute multiple test scenarios in feature file.

The hierarchy in the report right now is

| Background
| scenario
| Background
| Scenario

so they want the steps from BG to be included into scenario steps in right hierarchy. Is it possible to do with current version?

or i have only option which is edit the json file to have these change which is kind of tedious. PLease let me know. Thank you!

**Comment by damianszczepanik** [comment]
If they decide to have background in feature file they should respectively understand that report prints out result similar

**Comment by cbarath1986** [comment]
Yes i tried to make them understand but they are just new to BDD with cucumber and they wanted to this change atleast for sometime till they get familiarize with the report. any other option?

**Comment by damianszczepanik** [comment]
Does not look like reasonable argument for this change

**Comment by cbarath1986** [comment]
Most of the companies in the industry are in transformation phase to use BDD tools which seems reasonable for me. i agree you are the sole decision maker on this but still i cant agree with you on this. im going to look into another plugin. Thank you!

**Comment by damianszczepanik** [comment]
This is plugin and it's based on cucumber implementations. If you need such change you should request to change the cucumber implementation not the plugin otherwise you are using the plugin not along how it was designed to be used
