### ISSUE TITLE
Problem with creating report in Intellij 2019.1 EAP

### ISSUE THREAD

**Issue by melnychukkr** [damianszczepanik/cucumber-reporting#826]
Hi! I found a problem with creating a report using Intellij IDEA 2019.1 EAP. Previous versions don't have such issue.

I found that this problem is related to `net.masterthought.cucumber.generators.AbstractPage#generateReport`
I resolved this issue in debug mode by using the following:
```
Template template = engine.getTemplate("templates/generators/" + templateFileName);
template.initDocument();
```

The last line is responsible for creating missing folder in the `target` folder.

**Comment by damianszczepanik** [comment]
`target` directory is created by maven and this is how I run the project in IDEA
