### ISSUE TITLE
Integrate feature comments in the cucumber reporting

### ISSUE THREAD

**Issue by ouquoi** [damianszczepanik/cucumber-reporting#828]
Is there a way to add the comment in feature file to the html report ?
Thanks for your help.

**Comment by damianszczepanik** [comment]
Do you have sample JSON report with comments? Attach for reference

**Comment by damianszczepanik** [comment]
Closing as no feedback so far.

**Comment by jfougere** [comment]
Hi @damianszczepanik  just found this issue. I am actually looking for this feature also.

Below is an example of the json genrated by karate and which are the inputs for the cucumber reporting:

```
"step": {
            "comments": [
              "# Step 1: Subscribe to product"
            ],
           ....
          },
```

Such comment are present in the Karate reporting but I'd like to have such comments in the cucumber report.

Do you think this could be done ? It would be nice to have a display similar to feature descriptions.

**Comment by damianszczepanik** [comment]
Would be nice. You can prepare PR if you like so I can help

**Comment by jfougere** [comment]
Hi @damianszczepanik  my bad in fact Karate make those comments available only for the json produce for its own report but not for the json used as input for cucumber reporting.

Locally I prepared two changes one on Karate to add the comments and one on cucumber-reporting to use them and it works good. 

The result looks like this:
<img width="1430" alt="Capture d’écran 2021-07-10 à 08 43 27" src="https://user-images.githubusercontent.com/6061575/125146893-f2b22700-e15a-11eb-8308-2fb9c5bc2ad1.png">

So I will try on Karate side to see if they are open for a PR to add comments on the produced json.
