### ISSUE TITLE
There is a horizontal scrollbar on Failures page which should be removed

### ISSUE THREAD

**Issue by JiaYongfei** [damianszczepanik/cucumber-reporting#829]
Recently I'm working to use this cucumber report on Teamcity. When I switching between the different tabs (Features, Failures), the width of the report increased quickly to a huge number. I tried with a older version: 2.7.1 which doesn't have this problem. I think this is caused by the bootstrap class issue in expandAllButtons.vm file as we used the col-md-10 and col-md-offset-10 the same time which is not right.

Fix could be: Update the class col-md-10 to col-md-1 in expandAllButtons.vm file

**Comment by damianszczepanik** [comment]
Do you use it as the plugin or standalone version or maven port?
