### ISSUE TITLE
Support for 'text/csv' embeddings

### ISSUE THREAD

**Issue by shahrakesh** [damianszczepanik/cucumber-reporting#833]
Could support for mime type 'text/csv' be added for embeddings please?

**Comment by damianszczepanik** [comment]
How would you like to be supported? Or maybe you'd like to prepare change for that?

**Comment by shahrakesh** [comment]
At the moment, if I use mime type 'text/csv' then the file contents are not displayed and the attachment as downloaded as ".unknown". All I am looking for, is that file contents are displayed (as is) and file is downloaded as ".csv".

**Comment by damianszczepanik** [comment]
Then displaying as plain text is enough for you I guess.

**Comment by shahrakesh** [comment]
Yes, displaying as plain text and download as ".csv".

**Comment by damianszczepanik** [comment]
Looks like all we need is to copy and adapt https://github.com/damianszczepanik/cucumber-reporting/commit/a8684595c0e84fb34d63b7ec1318ea0fe2dfc949#diff-d66296b2c548e65099c0bb735eecd08c - would you like do that ?

**Comment by pavelpp** [comment]
I have the same issue with Excel spreadsheet. :(
