### ISSUE TITLE
Features page flickering issue

### ISSUE THREAD

**Issue by JiaYongfei** [damianszczepanik/cucumber-reporting#834]
The features page (can't reproduce for other pages) will start flickering when resizing the browser window (until the point when the vertical scrollbar appears/disappears). I found a similar [issue](https://github.com/chartjs/Chart.js/issues/4179) on stackoverflow which is related to chartjs and its suggested fix is using `overflow-y: overlay`.

**Comment by damianszczepanik** [comment]
Not going to fix it but if you prepare patch for that a I will be happy to merge it

**Comment by JiaYongfei** [comment]
#835
