### ISSUE TITLE
log4j log file is not generated when the plugin 4.4.0 used

### ISSUE THREAD

**Issue by cbarath1986** [damianszczepanik/cucumber-reporting#836]
The plugin 4.4.0 works really well with all the cases but except the log4j log file is not created when we use this plugin. Disabling the plugin generates log file successfully.
However console logging works in either case. Please help me, Thanks in advance!
 Please find below the details

Tech: Java with testng, cucumber
plugin: 

     <dependency> 
            <groupId>net.masterthought</groupId>
            <artifactId>cucumber-reporting</artifactId>
            <version>4.4.0</version>
        </dependency> 

log 4j:

		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.10.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.10.0</version>
		</dependency>

**Comment by damianszczepanik** [comment]
You should configure properly log4j.xml file so the output is printed when needed

**Comment by cbarath1986** [comment]
what do you mean by properly? how do you know i didnt do properly? it worked tilli implement this plug-in and report. it stopped working only after implementing this reporting.

**Comment by cbarath1986** [comment]
changing the "log4j.xml" to "log4j-test.xml" in my classpath resolved my issue. Thanks!
