### ISSUE TITLE
Selenide wrapper blocking the creation of cucumber-reporting files

### ISSUE THREAD

**Issue by osuser2018** [damianszczepanik/cucumber-reporting#839]
Recently I decided to try the Selenide wrapper to Selenium.  Integrating it was simple but I quickly saw that when implemented, I was not seeing the "cucumber-html-reports" folder containing all of the generated HTML files.  After removing the Selenide dependency from the POM.xml, everything went back to normal and the reports started generating again.

Has anyone encountered this?  Are there aspects to Selenide or the cucumber-reporting setup (which I might be missing) that can help this to work?  Is anyone using Selenide and these reports successfully?

I was using Selenium v 3.141.59, and Selenide 5.2.2

**Comment by damianszczepanik** [comment]
Does not look like problem with your code or way how you use it but rather dependency.

You can try to store report in different place which will be safe from deletion.
