### ISSUE TITLE
Remove / Disable Steps from the HTML report

### ISSUE THREAD

**Issue by madhushesharam** [damianszczepanik/cucumber-reporting#845]
Is there a way to remove the **Steps** from final HTML report ?

Below is what i would like the report to look like. Want just **Scenario/Feature**  in final HTML page  results.

![image](https://user-images.githubusercontent.com/9272894/58192661-e6bb3080-7c86-11e9-8874-c6b6e2f2301d.png)

Currently the report add all steps as shown below.

![image](https://user-images.githubusercontent.com/9272894/58192913-706afe00-7c87-11e9-99aa-5e4bbbe489b8.png)

Not sure it should go under a issue.

**Comment by damianszczepanik** [comment]
There is no support for that.
