### ISSUE TITLE
Skipped test should not be shown as failed.

### ISSUE THREAD

**Issue by iragoubi** [damianszczepanik/cucumber-reporting#852]
Hi, 
i have tests that are skipped when the payment is blocked but in the result i do not want it to be failed but skipped. If a scenario is skipped then it should not be shown as failed.
Is it possible that you add option like treatSkippedAsFailed=false  ? 
thanks

**Comment by damianszczepanik** [comment]
Discussion about this is https://github.com/damianszczepanik/cucumber-reporting/pull/636
