### ISSUE TITLE
Not able to get the total feature file count

### ISSUE THREAD

**Issue by KumarKola** [damianszczepanik/cucumber-reporting#859]
Hi @damianszczepanik  I am using 4.8 cucumber-reporting version and I  am merging multiple Json files to generate a single over-view html report. I am able to generate it but the Total count of features are not showing up. Could you please take a look. Thank you.

![image](https://user-images.githubusercontent.com/45509929/61658986-86e80280-ac94-11e9-9366-0c9fe62b6218.png)

 <dependency>
            <groupId>net.masterthought</groupId>
            <artifactId>cucumber-reporting</artifactId>
            <version>4.8.0</version>
        </dependency>

**Comment by damianszczepanik** [comment]
Have you tried with https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/reducers/ReducingMethod.java#L14 ?

**Comment by KumarKola** [comment]
> Have you tried with https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/reducers/ReducingMethod.java#L14 ?

@damianszczepanik  I have tried with merging the Json files.. pls find the below code that I used 

 public File reportOutputDirectory;
    public List<String> list;

    public HtmlReporter() {
        this.reportOutputDirectory = new File(System.getProperty("user.dir") + FileLocations.OUTPUT_DIRECTORY);
        this.list = new ArrayList();
    }

    public void listFilesForFolder(File folder) {
        File[] var2 = folder.listFiles();
        int var3 = var2.length;

        for(int var4 = 0; var4 < var3; ++var4) {
            File fileEntry = var2[var4];
            if (fileEntry.isDirectory()) {
                this.listFilesForFolder(fileEntry);
            } else if (fileEntry.getName().endsWith(".json")) {
                System.out.println("*******" + fileEntry.getName());
                this.list.add(this.reportOutputDirectory + "/reports/" + fileEntry.getName());
            }
        }

    }

    public void generateReports() throws VelocityException, IOException {
        this.listFilesForFolder(new File(System.getProperty("user.dir") + FileLocations.OUTPUT_DIRECTORY+ "/reports"));
        String jenkinsBasePath = "";
        String buildNumber = "1";
        String projectName = "cucumber-jvm";
        boolean runWithJenkins = false;
        boolean parallelTesting = false;
        Configuration configuration = new Configuration(this.reportOutputDirectory, projectName);
//        configuration.setParallelTesting(parallelTesting);
//        configuration.setRunWithJenkins(runWithJenkins);
        configuration.addPresentationModes(PresentationMode.RUN_WITH_JENKINS);
        configuration.setBuildNumber(buildNumber);
        ReportBuilder reportBuilder = new ReportBuilder(this.list, configuration);
        reportBuilder.generateReports();
    }

**Comment by damianszczepanik** [comment]
Check readme file and use above flag to merge features oroperly
