### ISSUE TITLE
101% tests were executed

### ISSUE THREAD

**Issue by damianszczepanik** [damianszczepanik/cucumber-reporting#86]
Having 2076 tests passed and 51 failed I can observe results with 97% pass and 4% failed what means I have executed 101% tests :)

Will try to find out whether this is plugin problem or cucumber-reporting.

**Comment by kingsleyh** [comment]
I guess it's the reporting - could be miscounting scenario outline or backgrounds 

If you don't mind maybe you could send me your cucumber json to kingsley at Masterthought dot net so I can investigate

**Comment by damianszczepanik** [comment]
I could not reproduce it without json files which I did not store... If it happens again I will handle this issue.

**Comment by msymons** [comment]
I am seeing this issue currently with Jenkins plugin v0.0.23.  I can provide the json files if it would help.  Just let me know where to send them (as I cannot attach them to a public issue tracker).

**Comment by damianszczepanik** [comment]
It would be. Tou can share by attaching the file or sharing by gist or github. Io

**Comment by damianszczepanik** [comment]
Should not happen after chart library upgrade
