### ISSUE TITLE
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonMappingException

### ISSUE THREAD

**Issue by jud55555** [damianszczepanik/cucumber-reporting#864]
Hello,

I added the following bit to pom.xml in order to generate an executable jar
```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <configuration>
			        <archive>
			        	<manifest>
			        		<mainClass>
			        			main
			        		</mainClass>
			        	</manifest>
			        </archive>
                </configuration>
            </plugin>
```
In the main class under src/main/java/main.java I put some code very similar to the one present under src/test/java/LiveDemoTest.java

After I created the jar file using `mvn clean package` and I run the runnable jar file with `java -jar target/cucumber-reporting-4.9.1-SNAPSHOT.jar` I get the following log:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonMappingException
	at main.main(main.java:29)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonMappingException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```
I have run into this every time, I have tried without changing the pom file and generating a regular jar and running it with `java -cp target/cucumber-reporting-4.9.1-SNAPSHOT.jar main`.

This issue has been addressed but I don't see how it is not working in my case.

Thanks.

**Comment by damianszczepanik** [comment]
You may try to run from `target/`  directory but I don't think I can help you with this as this is not normal way how this lib works
