### ISSUE TITLE
using html snippets in output

### ISSUE THREAD

**Issue by deepakbenny** [damianszczepanik/cucumber-reporting#871]
We use `scenario.write()` to add custom outputs to the html reports. But when we add strings with HTML tags to output, its coming as plain text without getting parsed.

Is there a way to parse html tags in custom output.
For eg: for something like this,
```
scenario.write("<a href='https://google.com'> Hello World </a>")
```
 I'm expecting a hyperlink for Hello World.

**Comment by damianszczepanik** [comment]
If you write it as base64 you can have HTML https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/resources/json/sample.json#L505-L507
