### ISSUE TITLE
EXPAND_ALL_STEPS doesn't expand output/embed contents

### ISSUE THREAD

**Issue by deepakbenny** [damianszczepanik/cucumber-reporting#872]
Currently if we use the config EXPAND_ALL_STEPS, only steps gets expanded whereas output/ embed contents doesn't expand. Since user is explicitly specifying this setting, I think it would be ideal to expand output and embed contents too.

Thoughts? I can help with a PR if this is approved.

**Comment by deepakbenny** [comment]
@damianszczepanik can you please let me know if this is something that can be added?

**Comment by damianszczepanik** [comment]
It can and it should be. You can prepare PR if you can so I can merge it
