### ISSUE TITLE
How can I add configuration by jenkins pipeline

### ISSUE THREAD

**Issue by RobertoPegoraro** [damianszczepanik/cucumber-reporting#875]
If I use code for generate the report, I can use configuration like this:
    configuration.addClassifications("Browser", "Firefox");

But I need do the same, using jenkins pipeline, is it possible?

**Comment by damianszczepanik** [comment]
Well it should be but it is not - would you like to prepare PR for this?

**Comment by damianszczepanik** [comment]
My bad, possible now
https://github.com/jenkinsci/cucumber-reports-plugin/blob/master/README.md#pipeline-usage
