### ISSUE TITLE
Duration reported doesn't match clock on the wall

### ISSUE THREAD

**Issue by dmreda** [damianszczepanik/cucumber-reporting#876]
Hi, we have cronjobs (for CentOS) and task scheduler tasks (for Win10) that kick off our regression scripts every night at midnight.

Based on log entries and file modification timestamps, we can see when they start and when they finish.

What we're seeing is that the tests will run about 11+ hours of real time, but the total duration on the overview-features.html is about 2 hours LESS than the actual duration.

Is there something that is happening in the test (maybe our Explicit Waits ?) which the tool is purposefully omitting when it calculates test duration?

Is there something else that may be contributing to the difference in reported vs actual time?

The log file appears to have the correct value, such as

479 Scenarios 
2906 Steps 
680m44.655s

(this is about 11 hours, 20 minutes, 44 seconds)

But the overview-features.html file has this row at the bottom:

2813 | 43 | 50 | 0 | 0 | 2906 | 432 | 47 | 479 | 9:34:42.627 | 42

2906 total steps in 479 scenarios across 42 feature files, but only 9 hours 34 minutes 42 seconds duration.

Any help is appreciated!

Thanks!
Dennis

**Comment by damianszczepanik** [comment]
This is sum of the tests run and not the time for test execution

**Comment by dmreda** [comment]
Thanks. Can you clarify what actions/activity is counted in "test execution" but not in "test run" ? The terms seem interchangeable. 

Thanks!

**Comment by damianszczepanik** [comment]
time between tests
