### ISSUE TITLE
Where should I call the generateReports method in CucumberTestRunner ?

### ISSUE THREAD

**Issue by kishore-marramreddy** [damianszczepanik/cucumber-reporting#878]
Should I call the report generating code in @AfterClass in CucumberTestRunner ?

I mean, where should I call this code ?

File reportOutputDirectory = new File("target");
List<String> jsonFiles = new ArrayList<>();
jsonFiles.add("cucumber-report-1.json");
jsonFiles.add("cucumber-report-2.json");

String buildNumber = "1";
String projectName = "cucumberProject";

Configuration configuration = new Configuration(reportOutputDirectory, projectName);
// optional configuration - check javadoc for details
configuration.addPresentationModes(PresentationMode.RUN_WITH_JENKINS);
// do not make scenario failed when step has status SKIPPED
configuration.setNotFailingStatuses(Collections.singleton(Status.SKIPPED));
configuration.setBuildNumber(buildNumber);
// addidtional metadata presented on main page
configuration.addClassifications("Platform", "Windows");
configuration.addClassifications("Browser", "Firefox");
configuration.addClassifications("Branch", "release/1.0");

// optionally add metadata presented on main page via properties file
List<String> classificationFiles = new ArrayList<>();
classificationFiles.add("properties-1.properties");
classificationFiles.add("properties-2.properties");
configuration.addClassificationFiles(classificationFiles);

ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
Reportable result = reportBuilder.generateReports();
// and here validate 'result' to decide what to do if report has failed

I tried this but the cucumber json report length is 0 at this time. not sure when to call this method. I am pretty sure there should be a simple way but don'r know how ?

**Comment by damianszczepanik** [comment]
This is completely separate from the test phase so you can call whenever you want

**Comment by kishore-marramreddy** [comment]
Thanks for your quick response.
