### ISSUE TITLE
Is there way to remove footer from the cucumber html report : Footer "generate Cucumber HTML reports via:  Jenkins Plugin | Standalone | Sandwich | Maven "

### ISSUE THREAD

**Issue by ivnaresh** [damianszczepanik/cucumber-reporting#879]
Is there way to remove footer from the cucumber html report

"generate Cucumber HTML reports via:  Jenkins Plugin | Standalone | Sandwich | Maven "

**Comment by damianszczepanik** [comment]
Nope, this is like branding
