### ISSUE TITLE
The month language is Chinese in Date

### ISSUE THREAD

**Issue by ryuwfn** [damianszczepanik/cucumber-reporting#882]
Hi,
 
The month language is Chinese in Date, Please refer to the screenshot for more details:
Version: 3.20.0
![image](https://user-images.githubusercontent.com/49050884/66997333-d3f93a80-f104-11e9-9108-3f8e993fcaa9.png)

Thanks Very much
Ryuwfn

**Comment by damianszczepanik** [comment]
Then change Jenkins agent location and locale to the place which fits your expectation :)

**Comment by ryuwfn** [comment]
> Then change Jenkins agent location and locale to the place which fits your expectation :)

Thanks your reply.  But the report be generated in my local PC, not in Jenkins. Should I change my PC location?

**Comment by damianszczepanik** [comment]
If you don't like Chinese :)

**Comment by ryuwfn** [comment]
> If you don't like Chinese :)

Thanks your reply.
I just want to make the language the same :). 
Because the report be generated in my PC, and my PC location setting managed by my organization, I will try to change Jenkins agent location when I deploy Jenkins.

**Comment by ryuwfn** [comment]
> Then change Jenkins agent location and locale to the place which fits your expectation :)

I change the setting in my PC, and be resolved: 
![image](https://user-images.githubusercontent.com/49050884/67255164-57bf7800-f4b3-11e9-8528-29adbfbedae3.png)

![image](https://user-images.githubusercontent.com/49050884/67255201-7c1b5480-f4b3-11e9-9fa7-e4f4daa3e90e.png)

Thank you again.
