### ISSUE TITLE
Optionally allow to hide steps statistics in overview table

### ISSUE THREAD

**Issue by motivatedmind** [damianszczepanik/cucumber-reporting#888]
Hello,

Would you please consider optionally allowing/hiding steps statistics in overview table. The reason why I am proposing this ehancement is that serveral times we have observed that the higher management/non technical folks ends up in reading steps statistics as the scenarios statistics and question why higher failures. They just don't know that they are reading the steps statistics.

Moreover a number of steps failed in scenario is really not significant because the scenario is anyways failed.

![image](https://user-images.githubusercontent.com/53520137/68557826-2707a880-048b-11ea-8d55-aca693f52697.png)

**Comment by damianszczepanik** [comment]
I don't want to add some functionality only because some users don't understand presented matrix. We can talk how to improve it but not hide/delete

**Comment by motivatedmind** [comment]
Ok. Can we then try to make order of appearence like Features > Scenarios > Steps

**Comment by damianszczepanik** [comment]
I will have impact for all users who use this library
