### ISSUE TITLE
File "embeddings" not working correctly 

### ISSUE THREAD

**Issue by vveliev** [damianszczepanik/cucumber-reporting#89]
When json report have embeddings such as "mime_type": "text/plain" and I will assume any other but "image/jpeg" report failing to display content.  Also it would be  nice to have option open in new tab  any embeddings that are presented in json file. 

![screenshot from 2015-04-22 10 59 47](https://cloud.githubusercontent.com/assets/5420655/7277811/137a340c-e8e0-11e4-8f3f-deaa57a85918.png)
![screenshot from 2015-04-22 11 00 05](https://cloud.githubusercontent.com/assets/5420655/7277810/1375c94e-e8e0-11e4-9252-03d577e8964c.png)

part of the embeddings(screenshot 1):
               "embeddings": [
              {
                "mime_type": "text/plain",
                "data": "eyJvYmplY3QiPT4iZXZlbnQiLAogImFjdGlvbiI9PiJwb2xsIiwKICJwcm90b2NvbCI9PiJYQ1AiLAogImF0dHJpYnV0ZXMiPT57ImxpbWl0Ij0+NTAwfX0K"
              }

**Comment by kingsleyh** [comment]
There will be improvements

**Comment by BogdanLivadariu** [comment]
@vveliev if you want to put plain text, you could use scenario.write("text desired") and the text will appear in the report as a comment

**Comment by vveliev** [comment]
@BogdanLivadariu thanks!

**Comment by vveliev** [comment]
@BogdanLivadariu  Thanks! 

...Sorry for close/open ... :)

**Comment by BogdanLivadariu** [comment]
Check this out https://github.com/masterthought/cucumber-reporting/pull/91
