### ISSUE TITLE
Introducing new line or separators within steps of the report

### ISSUE THREAD

**Issue by tceu-mihirmehta** [damianszczepanik/cucumber-reporting#891]
I am using Karate to run some API tests and use cucumber reporting for the reports. Is there a way we can introduce new lines or any separator characters between steps in the report. 

Here is a screenshot:

![Step_Separation](https://user-images.githubusercontent.com/56083983/68679734-5cc69300-0558-11ea-800b-5e0e65d14f66.jpg)

The line in blue is where I wish to include either a new line or something like ********* to separate the steps.

This is how my generateReport code in the test runner looks like:

```
 private static void generateReport(String karateOutputPath) {
    	  Collection<File> jsonFiles = FileUtils.listFiles(new File(karateOutputPath), new String[] {"json"}, true);
          List<String> jsonPaths = new ArrayList<String>(jsonFiles.size());
          jsonFiles.forEach(file -> jsonPaths.add(file.getAbsolutePath()));
         
          jsonPaths.forEach(path -> {
        		Path fullPath = Paths.get(path);
        		try {
        			String content = new String(Files.readAllBytes(fullPath));
        			content = content.replaceAll("(X-API-Key: )(\\w*)", "X-API-Key: xxx");
        			Files.write(fullPath, content.getBytes());
        			
        		} catch (IOException e) {
        			e.printStackTrace();
        		}
          });
          Configuration config = new Configuration(new File("target"), "TCEU");
         
          ReportBuilder reportBuilder = new ReportBuilder(jsonPaths, config);
          reportBuilder.generateReports();        
    }
```

Can you kindly advice?

**Comment by damianszczepanik** [comment]
Good idea, would you like to send PR for that change?

**Comment by tceu-mihirmehta** [comment]
Hi Damian,

Sorry if I wasnt clear but I wanted to know if we could have the separators or some way of representing the separations. I did not mean I have actually implemented it. I assume PR is when I have implemented and seeking approval to be merged. I am a tester and dont think can implement it on my own.

**Comment by damianszczepanik** [comment]
So before second, third and others `Given` there should be additional space?

**Comment by tceu-mihirmehta** [comment]
Yes thats right. I've shown the blue lines in the pic accordingly. 

Also it could be a separate discussion but is there a way we can tag @Given @When and @Then and add a statement and that statement then appears in the report?

For example:
@Given ("As an admin I want to create a new user")
...
Framework specific code
...
@When(" I enter the right user details and save")
...
...
@And("the user is not already present")
....
....
@Then("A new user is created)
...
...

The report can then show these above statements. Frameworks like Karate can benefit a lot from such options as the reporting can then be for both business users and techical users. 

Let me know your thoughts.

**Comment by tceu-mihirmehta** [comment]
@damianszczepanik : Did you get a chance to have a look at this please?

**Comment by damianszczepanik** [comment]
Merged, wait for next release

**Comment by tceu-mihirmehta** [comment]
@damianszczepanik , @kingsleyh : Do we know when is the next release scheduled for?
