### ISSUE TITLE
Creating one more release of 4.x.x from the master

### ISSUE THREAD

**Issue by dabogee** [damianszczepanik/cucumber-reporting#900]
hi, @damianszczepanik !
Sorry to bother you. I don't know how to send a direct message to you. Could you please build a release of the code with 4.x.x version (for example, 4.12.1) from the master branch before the 5.x is released.

I really need that changes and I would like to add the MERGE_WITH_RETEST option to the maven-cucumber-plugin and jenkins plugin.

**Comment by damianszczepanik** [comment]
5.0.0 is released, includes MERGE_WITH_RETEST
