### ISSUE TITLE
Build Links

### ISSUE THREAD

**Issue by realdadfish** [damianszczepanik/cucumber-reporting#902]
We're using this fantastic plugin with some custom code that allows us to publish the report to Gitlab CI Pages.

Unforatunately there doesn't seem to be a way to configure a free-form build URL, but just a build number, which we cannot use as navigation between different build reports works inherently different there than on Jenkins.

So, therefor the request; Would you be able to add an option to the configuration to provide a free-form URL that points to the build / pipeline that generated the report?

Many thanks!

**Comment by realdadfish** [comment]
Was bored on the train, so I gave it a try myself :)

**Comment by damianszczepanik** [comment]
I've missed that request but not sure what do you mean.

**Comment by realdadfish** [comment]
Forgot to close the issue, PR is long closed.
