### ISSUE TITLE
Duplicating features in report

### ISSUE THREAD

**Issue by vijay0850** [damianszczepanik/cucumber-reporting#907]
I have executed only one feature file but in the report it showing two feature as same name like duplicate.

![image](https://user-images.githubusercontent.com/10095173/71686250-9bdacd00-2dc0-11ea-9bbf-f3bc32ef700e.png)

**Comment by damianszczepanik** [comment]
JSON file, configuration please

**Comment by vijay0850** [comment]
List<String> tags = Arrays.asList("~@ignore");
        List<String> features = Arrays.asList("classpath:features");
        String karateOutputPath = "target/surefire-reports";
        Results results = Runner.parallel(tags, features, 5, karateOutputPath);
        Collection<File> jsonFiles = FileUtils.listFiles(new File(karateOutputPath), new String[] { "json" }, true);
		List<String> jsonPaths = new ArrayList<String>(jsonFiles.size());
		Iterator<File> jsonFilesIterator = jsonFiles.iterator();
		while (jsonFilesIterator.hasNext()) {
			jsonPaths.add(jsonFilesIterator.next().getAbsolutePath());
		}
		jsonFiles.forEach(file -> jsonPaths.add(file.getAbsolutePath()));
		Configuration config = new Configuration(new File("target"), "Xtreme");
		ReportBuilder reportBuilder = new ReportBuilder(jsonPaths, config);
		reportBuilder.generateReports();

**Comment by damianszczepanik** [comment]
Based on that code I don't think there is only one JSON file/feature you have collected so double check please
