### ISSUE TITLE
Downloading an ambedding does not take filename into account

### ISSUE THREAD

**Issue by FloKaemmerer** [damianszczepanik/cucumber-reporting#909]
I have an pdf embedding in a report like so:

```
"embeddings": [{
	"data": "JVBERi0xLjQKJaqrrK0KMSAwIG9iago8PAovQ3JlYXR[...]",
	"mime_type": "application/pdf",
	"name": "Ticket.pdf"
	}
]
```

The file is correctly generated and stored (in my case in a S3 Bucket)

In the Report the Embedding is displayed like this:
![image](https://user-images.githubusercontent.com/20900866/72169445-69882b80-33cf-11ea-9b37-327bb992ccf2.png)
which is fine.

The downloadlink points to the correct file: 
![image](https://user-images.githubusercontent.com/20900866/72169613-c257c400-33cf-11ea-864a-c516a5878f8f.png)

but when I click download I endup with a file named "f.txt" (using chrome)

The File has the correct content (renaming it to .pdf)

Either the filename from the report or the embedding filename should be used for the download.

**Comment by damianszczepanik** [comment]
Provide JSON file

**Comment by FloKaemmerer** [comment]
I found the Bug.

it isn't in the generator, but was in the webserver which didn't set the `ContententDisposition` Header correctly.
