### ISSUE TITLE
Failed to parse plugin descriptor for net.masterthought:cucumber-reporting:5.0.1 

### ISSUE THREAD

**Issue by sunnysachdeva99** [damianszczepanik/cucumber-reporting#911]
HI ,

my maven is throwing error 
Failed to parse plugin descriptor for net.masterthought:cucumber-reporting:5.0.1 

I tried other versions, but same error.

Could you please help

**Comment by pehguerra** [comment]
Hi,

I am facing same error. I didn't find any solution so far.
Could anyone help please?

**Comment by damianszczepanik** [comment]
This project has nothing common with descriptor or plugin. Try https://github.com/damianszczepanik/maven-cucumber-reporting
