### ISSUE TITLE
ReducingMethod HIDE_EMPTY_HOOKS: Don't hide "outputs"

### ISSUE THREAD

**Issue by lvogt** [damianszczepanik/cucumber-reporting#912]
We use "outputs" to include sent requests/response in each step, which should not be considered empty.

So I would like to give my vote for https://github.com/damianszczepanik/cucumber-reporting/blob/1c09aade8d6dda8c4fd59aeff42264c2f922d04e/src/main/java/net/masterthought/cucumber/json/Hook.java#L56
as not empty :)

**Comment by damianszczepanik** [comment]
attach JSON file

**Comment by lvogt** [comment]
This is just a sample JSON file.

[reports.zip](https://github.com/damianszczepanik/cucumber-reporting/files/4116416/reports.zip)

**Comment by damianszczepanik** [comment]
Cannot reproduce, share configuration

**Comment by lvogt** [comment]
Sorry, I did not correctly check my example report.json file. 
Attached is a new sample file which correctly reflects our setup: We use "After" hooks to log/output data. All these hooks will be removed by the reducing method, but should not when they actual data.
In the example the hooks containing the "Before" step should be removed, but the hook containing the "After" step should not be kept since it contains output.
[reports_2.zip](https://github.com/damianszczepanik/cucumber-reporting/files/4147999/reports_2.zip)

**Comment by damianszczepanik** [comment]
And the configuration?

**Comment by lvogt** [comment]
excerpt from cucumberReport.groovy
```
File reportOutputDirectory = new File("build");
List<String> jsonFiles = new ArrayList<>();
jsonFiles.add("build/tmp/reports.json");

String buildNumber = "1";
String projectName = "cucumberProject";

PresentationMode presentationMode = PresentationMode.RUN_WITH_JENKINS;

Configuration configuration = new Configuration(reportOutputDirectory, projectName);
// optional configuration
configuration.addPresentationModes(presentationMode)
configuration.setBuildNumber(buildNumber);
// additional metadata presented on main page
configuration.addClassifications("Platform", "Windows");
configuration.addClassifications("Browser", "Firefox");
configuration.addClassifications("Branch", "release/1.0");
configuration.addReducingMethod(ReducingMethod.HIDE_EMPTY_HOOKS);

ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
Reportable result = reportBuilder.generateReports();
```

**Comment by damianszczepanik** [comment]
![obraz](https://user-images.githubusercontent.com/9612911/73761300-ef995700-476e-11ea-9b08-aa50de89c1ba.png)
everything is collapsed
