### ISSUE TITLE
Feature Request: Disable or speed up "Tags" page

### ISSUE THREAD

**Issue by mattventura** [damianszczepanik/cucumber-reporting#925]
Due to their size, our reports often take a while to generate (15+ seconds, sometimes as much as 40 seconds). I did some investigation and found that the majority of this time was spent in `ReportBuilder.generatePages` in this loop:

```
            for (TagObject tagObject : reportResult.getAllTags()) {
                new TagReportPage(reportResult, configuration, tagObject).generatePage();
            }
```

Since I don't use these pages anyway, I'd like to have an option to disable this completely. Using `configuration.setTagsToExcludeFromChart(".*")` resulted in an empty tags page, but did not improve performance noticeably. Commenting out the loop entirely was the only thing that had a significant performance gain.

Alternatively, if something could be done to improve the performance of the tags pages significantly, that would also be welcome.

**Comment by damianszczepanik** [comment]
@mattventura one more test before release? I fixed issue you have reported which was related to missing page.

**Comment by mattventura** [comment]
@damianszczepanik looks good to me.
