### ISSUE TITLE
Embedding screenshot as attachment

### ISSUE THREAD

**Issue by rarunp04** [damianszczepanik/cucumber-reporting#928]
Hi , Was trying to execute the maven cucumber reporting using maven plugin having 2 feature files . 
Both feature files have 2 scenarios as scenario outline to execute .

Both the scenarios failed in both the feature files respectively . Had used embed screenshot in afterHooks . 

For the first feature file - scenario 1 had the attachment and for the scenario2 the link was present with no attachment

For the second feature file - scenario 1 had the attachment and for the scenario2 also had

Also , in the embeddings folder also there were 3 screenshots instead of 4 . Can you please help me here

**Comment by damianszczepanik** [comment]
Attach JSON report and point screenshots which are broken
