### ISSUE TITLE
Sending the report as an email attachment

### ISSUE THREAD

**Issue by rarunp04** [damianszczepanik/cucumber-reporting#929]
Hi ,

Was trying to send the report as an email attachment . But the report doesnt contain anything related to execution . Can you please let me know what are the things to be included with reports during attachment

Has anyone tried sending report as attachment
This is how the report looks when opened from attachment

![image](https://user-images.githubusercontent.com/44132688/79890096-99a68800-841c-11ea-9762-f576410c7a01.png)

**Comment by damianszczepanik** [comment]
You need to pack whole directory, not single HTML page
