### ISSUE TITLE
Re-sending mail after mail job failed

### ISSUE THREAD

**Issue by rathod36** [damianszczepanik/cucumber-reporting#930]
We have 2 infrastructure for running job so mail trigger will happen from on prime. And all procces on cloud.
Now issue is sometimes it will not send mail after completing all stages . So how can create a separate recovery script kind of for rerun job and send cocumber reports. Written script can be appreciated.

**Comment by damianszczepanik** [comment]
I can hardly understand you but this project has no limitation about email so you can use it as you like
