### ISSUE TITLE
How to change qualifier field to be different than filename

### ISSUE THREAD

**Issue by kontownik** [damianszczepanik/cucumber-reporting#933]
Hello,

I have a question about the report customization, is there are some possibilities to change `qualifier` field?
- from what I understand qualifier = filename,
- `qualifier` field is kept inside `Feature` object? Do you have any plans to expose it to Report-related objects?

**Use case:**
multiple report files (generated in parallel), every file is named after device UDID `QWERTY.json` but in the Pretty HTML report I wanted to use a different, human-readable, qualifier like `Samsung S6`.

How to achieve that?

**Comment by damianszczepanik** [comment]
@shchukax can you help with this?

**Comment by shchukax** [comment]
> @shchukax can you help with this?

Presently it's not supported, however I think the easiest way to do it would be to add `qualifier` (with corresponding setters/getters) to `Configuration` class.  That way a client could set the qualifier to whatever they want.  Then in `ReportParser.parseForFeature` method, instead of simply setting the qualifier to the filename, configuration could be checked - and the value from it used if it's not null.  If it's still null, then continue with what's being done currently.

**Comment by kontownik** [comment]
Thanks for your quick reply, I will try to do that in the comming week, then I will create PR.

**Comment by kontownik** [comment]
@shchukax I think hashmap (filename to qualifier) inside the `Configuration` object will be more useful than just setting `qualifier` as a single field, wdyt?

**Comment by shchukax** [comment]
@kontownik Yes, true.  However I would encompass the implementation inside the Configuration class so that instead of setting a map, you'd set and get individual qualifiers.  Something like this:

```
public class Configuration {
    ...
    private Map<String, String> qualifiers = new HashTable<>();
    ...

    public void setQualifier(@NonNull String jsonFile, @NonNull String qualifier) {
        qualifiers.set(jsonFile, qualifier);
    }

    public String getQualifier(@NonNull String jsonFile) {
        return qualifiers.get(jsonFile);
    }

    public void removeQualifier(@NonNull String jsonFile) {
        qualifiers.remove(jsonFile);
    }

    ....
}
```

**Comment by shchukax** [comment]
Having written the above, I might as well just submit a PR for it, as I have the code written - just need to add unit tests for it.

**Comment by kontownik** [comment]
Thanks a lot :) that was quick
