### ISSUE TITLE
Add possibility to exclude specific tags from html report

### ISSUE THREAD

**Issue by pantoniotti** [damianszczepanik/cucumber-reporting#938]
At the moment, tags like @parallel=false show in the list of tags, but should not necessarily.
It would be great if there was an option to exclude tags in the output reports on demand

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/Configuration.java#L188
