### ISSUE TITLE
Remove the console log lines of INFO

### ISSUE THREAD

**Issue by mihirmehta** [damianszczepanik/cucumber-reporting#942]
When I run my tests using maven, I get the following lines as an output for every feature file

```
May 31, 2020 4:46:58 PM net.masterthought.cucumber.ReportParser parseJsonFiles
INFO: File 'C:\EclipseWorkspace\EC\target\cucumber-html-reports\EC.E2E_WNG.DateFilter_ByDC.json' contains 1 features
```
Is there a way to hide this from the console log? This happens for every feature file that is run or skipped and when we have hundreds of them, it is creating noise. 

Making maven quiet or writing something like:
```
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <Target>System.out</Target>
        <filter class="ch.qos.logback.classic.filter.LevelFilter">
            <level>WARN</level>
            <onMatch>ACCEPT</onMatch>
            <onMismatch>DENY</onMismatch>
        </filter>
        <encoder>
            <pattern>[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%level] %msg%n</pattern>
        </encoder>
    </appender>
```
does not help either. 
Any help here would be highly appreciated. Or if its an issue, we may need to resolve it?

**Comment by mihirmehta** [comment]
Having a look at the source code, is there a way to comment this line in the ReportParser.java file or do anything similar to resolve the issue I am facing?

```
LOG.log(Level.INFO, String.format("File '%s' contains %d features", jsonFile, features.length));
```

**Comment by damianszczepanik** [comment]
Have you tried to configure it via log4j?

**Comment by mihirmehta** [comment]
No I haven't. Is it possible to do it that way? Can you guide please?

**Comment by damianszczepanik** [comment]
Please read log4j documentation
