### ISSUE TITLE
cucumber-html-reports not getting latest report

### ISSUE THREAD

**Issue by Lavan21** [damianszczepanik/cucumber-reporting#944]
Dear Damian Szczepanik,

I have copied the latest Build details of POM. Xml and executed my cases. Still not able to get the latest HTML report including feature. After deleting the Cucumber-html report, tried to run and get the correct html report which shows only one module. When i tried to give tags to two modules and then run the same, it show the same html report which was already run in first module instead of latest report.

Kindly help to check the below script if I am wrong

**TestRunner.class**:
import org.junit.AfterClass;
import org.junit.runner.RunWith;
import java.io.File;
import Helpers.FileReaderHelper;
import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;

@RunWith(Cucumber.class)
@CucumberOptions(
        features = "src/test/resources/Features",
        glue = {"StepDefinitions"},
        tags = {"@DemoTest123"},
        //plugin = {"pretty","json:target/cucumber.json"},
        plugin = {"html:target/cucumber-html-report", "json:target/cucumber-reports/cucumber.json","junit:target/cucumber-reports/cucumber.xml"},
        monochrome = true
)

public class TestRunner {
    @AfterClass
    public static void tearDown() {
        HTMLReporter.main(new String[]{});
    }
}

**HTMLReporter.java:**
import io.cucumber.java.Scenario;
//import io.cucumber.core.api.Scenario;

import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;
import net.masterthought.cucumber.Reportable;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class HTMLReporter {
    // get generated cucumber json reports names
    public static List<String> getfilenames(){
        File folder = new File("output/cucumber");
        File[] listOfFiles = folder.listFiles();
        List<String> names = new ArrayList<>();
        for (int i = 0; i < listOfFiles.length; i++) {
            if (listOfFiles[i].isFile()) {
                if(listOfFiles[i].getName().contains(".json"))
                    names.add(listOfFiles[i].getName());
            }
        }
        return names;
    }

    public static void printText(Scenario scenario, String text) { scenario.write(text);
    }

    // To generate HTML reports from the json files
    public static void main (String[]args){
        File reportOutputDirectory = new File("output");
        List<String> jsonfiles = new ArrayList<>();
        List<String> names = getfilenames();
        for (String string : names) {
            jsonfiles.add("output/cucumber/" + string);
        }
        String projectName = "Cucumber Stoics-IT Project";
        Configuration configuration = new Configuration(reportOutputDirectory, projectName);
        ReportBuilder reportBuilder = new ReportBuilder(jsonfiles, configuration);
        Reportable result = reportBuilder.generateReports();
    }

}

**First module**:
![image](https://user-images.githubusercontent.com/55781854/84603337-4b0ceb80-aeab-11ea-8238-76db758baa62.png)

**Second module**:
![image](https://user-images.githubusercontent.com/55781854/84603324-303a7700-aeab-11ea-9e68-8538c03892a3.png)

**Report**:
![image](https://user-images.githubusercontent.com/55781854/84603420-033a9400-aeac-11ea-8da6-7e84b665ee53.png)

![image](https://user-images.githubusercontent.com/55781854/84603436-151c3700-aeac-11ea-8aa7-bd01d2ed5179.png)

**Comment by damianszczepanik** [comment]
There is something wrong then with your JSON report. HTML report looks correctly so find out what the cucumber does not produce proper JSON report.
