### ISSUE TITLE
How to integrate / add reports in Azure Devops?

### ISSUE THREAD

**Issue by anandbagmar** [damianszczepanik/cucumber-reporting#945]
Hi,
I have used these with Jenkins, but is there a way I can get the cucumber-reporting reports integrated with Azure Devops pipeline? 

Thanks!

**Comment by damianszczepanik** [comment]
https://github.com/jenkinsci/cucumber-reports-plugin this should help you

**Comment by iamsethi** [comment]
@damianszczepanik this https://github.com/jenkinsci/cucumber-reports-plugin is for Jenkins ,is there a way I can get the cucumber-reporting reports integrated with Azure Devops pipeline?
