### ISSUE TITLE
CucumberJS?

### ISSUE THREAD

**Issue by garethgreatrex** [damianszczepanik/cucumber-reporting#947]
Hi, is this plugin compatible with cucumberJs?

If it is I would like to use this plugin on Jenkins to generate reports.  Currently my solution generates a json results file from 'cucumber-html-reporter'.  Is it possible to add a command to the jenkins file to run 'cucumber-reporting' and generate the results to the Jenkins build folder?

If so what is the command?

**Comment by damianszczepanik** [comment]
I don't know CucumberJS but you can try https://github.com/jenkinsci/cucumber-reports-plugin
