### ISSUE TITLE
Can we display the list of scenarios and statistics in grid or table after opening one specific feature?

### ISSUE THREAD

**Issue by venkat675** [damianszczepanik/cucumber-reporting#948]
**Link1**: http://damianszczepanik.github.io/cucumber-html-reports/overview-features.html
Features overview page (Link1) looks good, it has good enough details.

**Link2**: http://damianszczepanik.github.io/cucumber-html-reports/report-feature_1920820787.html
But, is there way to display the list of scenarios and statistics in grid or table after opening one specific feature (Link2).
Displaying each scenario data(number of steps, pass/fail, duration) in grid will give clarity on feature.

**Comment by damianszczepanik** [comment]
No and I don't have plan for that.
