### ISSUE TITLE
Not able to generate report - missing start_timestamp field?

### ISSUE THREAD

**Issue by dsallen7** [damianszczepanik/cucumber-reporting#949]
Hi,

I am not able to complete the final step of generating the report. I am seeing the following error stacktrace:

Jun 30, 2020 10:44:06 AM net.masterthought.cucumber.ReportBuilder generateErrorPage
INFO: Unexpected error
java.lang.IllegalArgumentException: You are not able to use this type of results merge. The start_timestamp field should be part of element object. Please, update the cucumber-jvm version.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at net.masterthought.cucumber.reducers.ReportFeatureWithRetestMerger.updateElements(ReportFeatureWithRetestMerger.java:53)
	at net.masterthought.cucumber.reducers.ReportFeatureWithRetestMerger.merge(ReportFeatureWithRetestMerger.java:34)
	at net.masterthought.cucumber.ReportResult.<init>(ReportResult.java:49)

It appears that it is expecting a start_timestamp field in each scenario in the cucumber.json file. I checked and sure enough, that field does not appear anywhere in the file.

Can you advise what "cucumber-jvm" is exactly and what needs to be updated?

My pom.xml includes the following:

                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>5.0.0</version>

		    <groupId>info.cukes</groupId>
		    <artifactId>cucumber-java</artifactId>
		    <version>1.2.5</version>

		    <groupId>info.cukes</groupId>
		    <artifactId>cucumber-junit</artifactId>
		    <version>1.2.5</version>

Thanks!

**Comment by damianszczepanik** [comment]
Attach JSON file

**Comment by dsallen7** [comment]
[CucumberJson.zip](https://github.com/damianszczepanik/cucumber-reporting/files/4907354/CucumberJson.zip)

**Comment by damianszczepanik** [comment]
I could generate report without any problem
![obraz](https://user-images.githubusercontent.com/9612911/88717803-61040200-d121-11ea-88b9-bc94ea127d16.png)
