### ISSUE TITLE
Duration mismatch in the report while running the test as JUNIT 

### ISSUE THREAD

**Issue by vkowsaly** [damianszczepanik/cucumber-reporting#950]
hi, 

I am trying to run junit and generate this report , but junit gives me duration is seconds , but there is mismatch in the report. I am new to this .Can you please help. 
Also, I use test scenraios and test cases for manual execution. is it possible to rename scenarios to test case in the html report ?

**Comment by damianszczepanik** [comment]
Seconds is not the right unit. Check https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/resources/json/sample.json
