### ISSUE TITLE
Can you help providing an example how can we generate cucumber-reports using gradle plugin

### ISSUE THREAD

**Issue by chetanSrajiv** [damianszczepanik/cucumber-reporting#953]
i am able to successfully generate reports using maven plugin adding to pom.xml

so is it also possible to add this dependency in build.gradle and generate reports? if so what could be the plugin we need to apply and task to be executed to generated reports

currently this plugin is helping me to generate the reports https://github.com/alfa-laboratory/cucumber-reporting-gradle-plugin but i want to switch to the latest version of your plugin as it displays after step hooks for every gherkin step in reports generated through maven.

**Comment by damianszczepanik** [comment]
AFAIR gradle provides plugin to migrate from pom to gradle. It should help
