### ISSUE TITLE
Error screenshots are not appearing in overview-features.html reports for jenkins jobs...

### ISSUE THREAD

**Issue by sredischVibrent** [damianszczepanik/cucumber-reporting#956]
...but the same screenshots are appearing in the overview-features.html file when I run the tests locally. The dropdown area where the screenshots normally appear does not render at all, meaning the dropdown is not present.  If I delete the target/cucumber-html-reports/embeddings dir, as a comparison, then the screenshot dropdown does appear, but with an icon in place of the screenshot.
  My jenkins job is running the same version of cucumber-jvm as my project, so I am not running into the embedding(s) json formatter issue.
  Has anyone reported this issue yet?  I didn't see it listed. This is my plugin element:
            `            <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>${cucumber.reporting.version}</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <projectName>automation-test-project</projectName>
                            
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            <jsonFiles>
                                
                                <param>cucumber.json</param>
                            </jsonFiles>
                            
                            <checkBuildResult>true</checkBuildResult>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
`
  My current idea is that the absolute paths to the embedded images are not usable after the container is deleted when the jenkins job ends.  Have you come across this issue before?  All of the overview-features report is rendering successfully for the jenkins job except for the screenshot.

**Comment by sredischVibrent** [comment]
We inspected the s3 bucket that we are copying our target directory results into. The pre-copy directory does not contain an embeddings folder, which is expected to house the embedded images. Have you seen that before?

**Comment by damianszczepanik** [comment]
Attach JSON file with report

**Comment by sredischVibrent** [comment]
[cucumberJson.txt](https://github.com/damianszczepanik/cucumber-reporting/files/5086749/cucumberJson.txt)
This is a txt version of the cucumber.json file for the build.  Let me know if you need any other files.

**Comment by sredischVibrent** [comment]
@damianszczepanik is your team going to work on this?

**Comment by damianszczepanik** [comment]
This is because report does not have declared any image such as https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/resources/json/sample.json#L32
