### ISSUE TITLE
Issue with Excel (xlsx) embedding in report

### ISSUE THREAD

**Issue by HItesh007** [damianszczepanik/cucumber-reporting#966]
@damianszczepanik 

When I attach excel having extension as `.xlsx` and using mime type as `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` then in report it's not embedded properly. It looks like more of a conversion issue from json to xlsx. 

It is copied as `embedding_-732145017.unknown` inside of `embeddings` directory. 

Can you please take a look or if you are using other mime type for xlsx attachment?

**Comment by HItesh007** [comment]
@damianszczepanik ,

I have raised #967 PR for the issue I have mentioned earlier. Please review it and let me know if this can be merged with master or not. Do let me know if there are any further tests to be included.

Thanks,
Hitesh Prajapati

**Comment by damianszczepanik** [comment]
Merged, will be released soon
