### ISSUE TITLE
mvn net.masterthought:maven-cucumber-reporting:5.3.0:generate 

### ISSUE THREAD

**Issue by BLOPESLO** [damianszczepanik/cucumber-reporting#972]
Hi,
I need to execute comand maven mvn net.masterthought:maven-cucumber-reporting:5.3.0:generate to generate the report, but i getting the following error:
I suppose the 'jsonFiles' parameter is missing.
How can I pass this parameter in the maven command?

[ERROR] Failed to execute goal net.masterthought:maven-cucumber-reporting:5.3.0:generate (default-cli) on project template-web-CucumberSelenium: The parameters 'jsonFiles' for goal net.masterthought:maven-cucumber-reporting:5.3.0:generate are missing or invalid -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException

**Comment by BLOPESLO** [comment]
Hi try this:
mvn -DjsonFiles='/target/cucumber-reports/cucumber.json' net.masterthought:maven-cucumber-reporting:5.3.0:generate -X
But i getting the same error.
Any idea?

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/maven-cucumber-reporting

**Comment by BLOPESLO** [comment]
Hi, thanks for the answer,
but how can I pass the parameters in the maven command?
I tried it this way and it didn't work.

mvn -DjsonFiles='/target/cucumber-reports/cucumber.json' net.masterthought:maven-cucumber-reporting:5.3.0:generate


Any idea?
