### ISSUE TITLE
.

### ISSUE THREAD

**Issue by mejuhi** [damianszczepanik/cucumber-reporting#974]
.

**Comment by damianszczepanik** [comment]
Your intention is unclear to me

**Comment by mejuhi** [comment]
I wan to generate reports when cucumber is running  using `JUnitCore.main(RunCucumberTest.class.getName());`.

Even though i have added configuration in my Application code to generate report, i am not sure why report is not getting generated?

**Comment by damianszczepanik** [comment]
I don't know this library
