### ISSUE TITLE
Cant see screenshots properly

### ISSUE THREAD

**Issue by Ported** [damianszczepanik/cucumber-reporting#98]
After this change added max-width: 250px; the screenshots are so small that I can no longer see enough detail to see what has gone wrong.

https://github.com/masterthought/cucumber-reporting/commit/dfc170787ad59f705d590dadaa7ae535ff5116af#diff-1eeb2da981684473c263089457fbbca9R177

I can still insepect the element and remove the css to see the full image as a workaround, but it would be nice to have the screenshot at least the same width as the scenario above.

**Comment by damianszczepanik** [comment]
@Ported 
I need sample data with screenshot to verify change. Share yours or any other from web that will be appropriate for this issue.

**Comment by Ported** [comment]
Hi,

You can see sample data in the tests:

https://github.com/masterthought/cucumber-reporting/commit/dfc170787ad59f705d590dadaa7ae535ff5116af#diff-2ed1bc4674c1c57e280a4e51b6136078R128

Im not sure what else you need, the addition of "max-width: 250px;" will make the screenshots 250px wide whereas before they would have displayed at the width of the embedded image.

Hope that helps.

**Comment by damianszczepanik** [comment]
@Ported 
I can easily change the width to 100% so the screenshot is no longer small. However I found that the reason why this change was applied might be that you can simple click the image to see bigger one with all details and when having more than one screenshot per scenario now they are don't occupy whole page

So what is the reason for this change? Why clicking the image to see bigger one is not good solution for you?

**Comment by Ported** [comment]
Hi @damianszczepanik 

The version I am using (Cucumber-JVM Jenkins Report Plugin - version: cucumber-reporting-0.0.23 - 11-05-2015 06:52:11) does not have the functionality that enlarges the image when clicked on. Do you know if this is coming out in a future release?

Thanks.

**Comment by damianszczepanik** [comment]
I've just found that I also can't see this on production server. Let's wait with this PR and I will fix it once this is not useful enough (after new release).

Thanks

**Comment by kingsleyh** [comment]
Damian can you email me at kingsley at masterthought dot net

**Comment by Ported** [comment]
This issue is resolved in the latest update. I can now click the image and get a bigger version.

Suggestions for usability improvements:
* Now that its displaying thumbnails why default to having them expanded if a scenario fails, this will save a mouse click.
* The animation / fade in of the lightbox image feels pretty sluggish, I think this interrupts the flow of looking at the image, it could be much faster.

Thanks for the fix!
