### ISSUE TITLE
cucumber html report collapsible tags are always expanded by default

### ISSUE THREAD

**Issue by AajKaCoder** [damianszczepanik/cucumber-reporting#992]
When ever I click on the feature ,the failed test cases comes expanded by default.
area-expanded tag is always true by default.
can i have it as collapsed for all test cases, fail or pass, by default.

**Comment by damianszczepanik** [comment]
You have probably use this https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/java/LiveDemoTest.java#L35
