### ISSUE TITLE
Support for multiple reports?

### ISSUE THREAD

**Issue by nddipiazza** [damianszczepanik/cucumber-reporting#998]
Has anyone thought about support for a list of JSON files in some sort of combined report?

For example you have a test that runs daily. you would want to be able to see each test, or a summary of the tests for the last 30 runs? 

Very useful in situations where a failure happens then you can review the previous N builds and see if any previous failures looked similar, etc. 

Does that exist yet ?

**Comment by nddipiazza** [comment]
probably a duplicate of this 
https://github.com/damianszczepanik/cucumber-reporting/issues/648

**Comment by damianszczepanik** [comment]
Looks like you need to have history/audit - https://github.com/jenkinsci/cucumber-reports-plugin
