### ISSUE TITLE
Scenarios with Failed hooks (@After) are not present in overview-failures.html

### ISSUE THREAD

**Issue by stamtesteng** [damianszczepanik/cucumber-reporting#999]
After resolving an old issue https://github.com/damianszczepanik/cucumber-reporting/issues/497,
hooks that fail make also Scenarios to fail and this is also visible in both reports:
- _overview-features.html_
- _overview-steps.html_

Although, currently the scenarios that have failures in the hooks (@After) are not present in the 
- _overview-failures.html_

and this creates misunderstandings, because we are trying to see all failures one-by-one in this report and these tests are missing.

**Comment by damianszczepanik** [comment]
Attach JSON and its configuration for the report

**Comment by stamtesteng** [comment]
Thanks Damian

json and runner attached in zip file.
[issue-999.zip](https://github.com/damianszczepanik/cucumber-reporting/files/6257267/issue-999.zip)

The configuration in Jenkins pipeline job is 
- cucumber fileIncludePattern: '**/cucumber*.json', jsonReportDirectory: 'test-automation/', sortingMethod: 'ALPHABETICAL'

**Comment by damianszczepanik** [comment]
Interesting scenario but yes this is a bug

**Comment by damianszczepanik** [comment]
Fix will be published with next release
